### ISSUE TITLE
Test case bank::tests::test_bank_get_program_accounts fails occasionally

### ISSUE THREAD

**Issue by svenski123** [solana-labs/solana#10151]
#### Problem
Test case bank::tests::test_bank_get_program_accounts exhibits spurious failures; one example is below.

Command used to produce this:
```
$ while true; do RUST_BACKTRACE=full target/debug/deps/solana_runtime-e2e03d2fe5df40f7 test_bank_get_program_account || break; done
```

Test program was built with `cargo test -p solana-runtime` off a clean checkout of master; commit revision was:
```
$ git log -1 --oneline
5e43304 Bump byte-unit from 3.0.3 to 3.1.1 (#10098)
```

```
running 1 test
test bank::tests::test_bank_get_program_accounts ... FAILED

failures:

---- bank::tests::test_bank_get_program_accounts stdout ----
thread 'bank::tests::test_bank_get_program_accounts' panicked at 'assertion failed: `(left == right)`
  left: `[(2WjvxdAKc3Yv3c8GG84iZ3jfhHAc44AXa7xE1R9jqat6, Account { lamports: 1 data.len: 0 owner: 8qbHbw2BbbTHBW1sbeqakYXVKRQM8Ne7pLK7m6CVfeR executable: false rent_epoch: 0 })]`,
 right: `[]`', runtime/src/bank.rs:5868:9
stack backtrace:
   0:     0x5631252f1354 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x5631252f1354 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x5631252f1354 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5631252f1354 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x563125318c3c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x5631246e4305 - std::io::Write::write_fmt::hfbb72e22b78f9fe3
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/io/mod.rs:1426
   6:     0x5631252e6cb1 - std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt::h3f2853feac60bd2f
                               at src/libstd/io/impls.rs:156
   7:     0x5631252f4145 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   8:     0x5631252f4145 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   9:     0x5631252f4145 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
  10:     0x5631252f3e3b - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:221
  11:     0x5631252f47a2 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  12:     0x5631252f438b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  13:     0x5631252f42fb - std::panicking::begin_panic_fmt::h7c14cf40a8be97ee
                               at src/libstd/panicking.rs:332
  14:     0x563124358174 - solana_runtime::bank::tests::test_bank_get_program_accounts::h807a331b6420b6c0
                               at runtime/src/bank.rs:5868
  15:     0x563123f24eea - solana_runtime::bank::tests::test_bank_get_program_accounts::{{closure}}::h60fd3c7bcab6e1cb
                               at runtime/src/bank.rs:5829
  16:     0x563123efb54e - core::ops::function::FnOnce::call_once::h0918ad1b427fb781
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ops/function.rs:232
  17:     0x5631246f080f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h05730b9f37b3c471
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  18:     0x5631252fe067 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  19:     0x56312470bc6c - std::panicking::try::he43ff887a3a89d25
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panicking.rs:281
  20:     0x56312470bc6c - std::panic::catch_unwind::h1f3afce8d01e13a9
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panic.rs:394
  21:     0x56312470bc6c - test::run_test_in_process::h887aa42b0221916b
                               at src/libtest/lib.rs:542
  22:     0x56312470bc6c - test::run_test::run_test_inner::{{closure}}::h1c7590a2227f43bf
                               at src/libtest/lib.rs:451
  23:     0x5631246e3a36 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdbb9e844cc293a6c
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/sys_common/backtrace.rs:130
  24:     0x5631246e80c6 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h4127953596223430
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/mod.rs:475
  25:     0x5631246e80c6 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6f746ae13e636f5d
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panic.rs:318
  26:     0x5631246e80c6 - std::panicking::try::do_call::h4a99f6fd09b79f57
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panicking.rs:303
  27:     0x5631252fe067 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  28:     0x5631246e8ba6 - std::panicking::try::h850dc1b8a95bd3bc
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panicking.rs:281
  29:     0x5631246e8ba6 - std::panic::catch_unwind::h2fcdb2545a4d1edb
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panic.rs:394
  30:     0x5631246e8ba6 - std::thread::Builder::spawn_unchecked::{{closure}}::h37aae16e38f2c073
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/mod.rs:474
  31:     0x5631246e8ba6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h784db8e5e27e02df
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ops/function.rs:232
  32:     0x5631252e07af - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h36e46972b1b7f7b7
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  33:     0x5631252fd17d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hdde89c32ce6999de
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  34:     0x5631252fd17d - std::sys_common::thread::start_thread::h5ae3fdd4dad03dd5
                               at src/libstd/sys_common/thread.rs:13
  35:     0x5631252fd17d - std::sys::unix::thread::Thread::new::thread_start::h76b2403b2434c4c0
                               at src/libstd/sys/unix/thread.rs:80
  36:     0x7fabec7c6dd5 - start_thread
                               at /usr/src/debug/glibc-2.17-c758a686/nptl/pthread_create.c:307
  37:     0x7fabec0d202d - __clone
  38:                0x0 - <unknown>


failures:
    bank::tests::test_bank_get_program_accounts

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 318 filtered out
```

#### Proposed Solution
TBD

**Comment by CriesofCarrots** [comment]
@svenski123 , do you have this commit? https://github.com/solana-labs/solana/commit/9d89fb5c353a7b68230f3f9eed5d67baf758694c

**Comment by svenski123** [comment]
No; pulled it; it looks better now; thanks!
