### ISSUE TITLE
panic observed in testnet-master-perf

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1076]
panicked at 'Expected an account balance of 1 (balance: 2', src/bin/bench-tps.rs:154:17

2018-08-27 09:44:35 | master-perf-testnet-solana-com-client-r3rt | bench-tps | main | panicked at 'Expected an account balance of 1 (balance: 2', src/bin/bench-tps.rs:154:17

SW version: 48762834d994a17c736590d4c1cd7ac00beea4dd

**Comment by rob-solana** [comment]
I'm going to close this because we haven't seen it for a while.
