### ISSUE TITLE
Solana 1.2.8 deadlocks after running bench-tps 

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#10889]
#### Problem

The Solana process seems to frequently run into some kind of deadlock after running bench-tps yesterday:

![image](https://user-images.githubusercontent.com/859697/86347348-7723bd00-bc5e-11ea-89da-2ef4b4ae5d5e.png)

Also shows in our monitoring data due to RPC timeouts:

![image](https://user-images.githubusercontent.com/859697/86347513-ae926980-bc5e-11ea-8d82-020ff0017249.png)

@Reisen is seeing the same thing on their node

#### Proposed Solution

Not deadlock

**Comment by Reisen** [comment]
Unsure if it's helpful, but they align with very large spikes of outgoing network traffic.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/158967/86348628-6e77ba80-bc4f-11ea-8bcd-0a97cc370fcc.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/158967/86348686-85b6a800-bc4f-11ea-902a-a08411a1b592.png">

**Comment by sakridge** [comment]
Any logs?

**Comment by leoluk** [comment]
Suspect stacktrace:

```
Thread 261 (Thread 0x7f8a0e5f2700 (LWP 1605)):
#0  0x000055cb8234630b in <std::collections::hash::map::DefaultHasher as core::hash::Hasher>::write ()
#1  0x000055cb82363a2e in hashbrown::map::make_hash ()
#2  0x000055cb823cb08c in hashbrown::raw::RawTable<T>::reserve_rehash ()
#3  0x000055cb823d3f65 in hashbrown::raw::RawTable<T>::insert ()
#4  0x000055cb8236047e in hashbrown::map::HashMap<K,V,S>::insert ()
#5  0x000055cb82334310 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#6  0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#7  0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#8  0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#9  0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#10 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#11 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#12 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#13 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#14 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#15 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#16 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#17 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#18 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#19 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#20 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#21 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#22 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#23 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#24 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#25 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#26 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#27 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#28 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#29 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#30 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#31 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#32 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#33 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#34 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#35 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#36 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#37 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#38 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#39 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#40 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#41 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#42 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#43 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#44 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#45 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#46 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#47 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#48 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#49 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#50 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#51 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#52 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#53 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#54 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#55 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#56 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#57 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#58 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#59 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#60 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#61 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#62 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#63 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#64 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#65 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#66 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#67 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#68 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#69 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#70 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#71 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#72 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#73 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#74 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#75 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#76 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#77 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#78 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#79 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#80 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#81 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#82 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#83 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#84 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#85 0x000055cb82334593 in solana_runtime::accounts_db::AccountsDB::inc_store_counts ()
#86 0x000055cb82335b9a in solana_runtime::accounts_db::AccountsDB::clean_accounts ()
#87 0x000055cb81fc0c2c in solana_ledger::bank_forks::BankForks::set_root ()
#88 0x000055cb81ccb96b in solana_core::replay_stage::ReplayStage::handle_votable_bank ()
```

**Comment by leoluk** [comment]
Full stacktraces: 
[gdb.txt](https://github.com/solana-labs/solana/files/4864619/gdb.txt)

**Comment by pkrasam** [comment]
idk if the deadlocks is causing my script on an average 20% to 100% transaction loss

**Script**:
```
#!/bin/bash

transact() {
  echo "solana ping -c 10 -i 0 -t 1"
  solana ping -c 10 -i 0 -t 1
}

while :
do
    echo "$(date) - sending transactions"
    transact
    echo "$(date) - sleeping for a bit"
    sleep 15s
done
```

Output:
```
Confirmation timeout:  seq=0               signature=3fGabhhqC7DeogdPaqzyn891T65Qyvs4AZ8AgZr3AXaHKstUAKpG8R2xmWVWqLeKzojwmiqsz4XFq8kvsreyuYfK
Confirmation timeout:  seq=1               signature=5suhaYncKgvMTuZwSbFaxoA3TyY3r3frCyjfuE8EyZYaav9GhQd1dwQDDg1AfAWVpD3mGQ1tS9ZaVbThnoEwU49K
Confirmation timeout:  seq=2               signature=63p1px9RqBNXFJcuW1F3Q9QXP8g5YfprEqSWjzYm7TombRLfUTL4zqznQHPR52nnqgrYEmnHZiT4cnQE74njoD8B
Confirmation timeout:  seq=3               signature=3bvT6QTLNado6Qrbw4KTJg9q5hq6v4go5atPs5AmEm4VxsCW85G3arxHYmFm5gW1rU7L1r8znDL14XJYTuMoqfpm
Confirmation timeout:  seq=4               signature=318Y8m8LyAWYpn8Xr5jf44EPSer9FcrYNG5VujiLGDJBk4nLMKFGxHj8NL2wWLaJPU91eUQMV2SUqrTCY9NG4xUY
Confirmation timeout:  seq=5               signature=NkYZmSkwzbUCGWx5gvC8391JUwwoeKV6jZL6o818UJEpV5Df935MTswpfjdoBJxSeQnahgHsz1vMRpnPFuzYAdr
Confirmation timeout:  seq=6               signature=2T1w1KLGwRjn2vRPgXAJB1FXWyAexuAGZEPzWhrXtrs7zePqRbLMp1jjYmmMU66prKRh1YPy9AsPhQ97gv749dYA
Confirmation timeout:  seq=7               signature=5hrTQLe6eqHLx7C5p1KpD1Q5BVM5y2VnwPbpW7qeZ9GfEsULDRqD2bmrqMe8mXEo1ydwTcrHS8qXVCfEDa49MVnY
Confirmation timeout:  seq=8               signature=4bfoPB8X86ut1SdsFu8oj9TFmvgM1Bz81dqMgaG4GXXw61CrsYmTLo5XAeKaJXnHNwoPSDY2z4cEfQqer9FA6KNk
Confirmation timeout:  seq=9               signature=4EiRqcm3azJuTW6ccHPAPBD5c4APngR7228Dy3ce4x7CgWsBsjeonDTwxD6LLEAcwmF24bY7ubqt44mULdvXDWt8

--- transaction statistics ---
10 transactions submitted, 0 transactions confirmed, 100.0% transaction loss

Fri Jul  3 02:32:56 CEST 2020 - sleeping for a bit
```
