### ISSUE TITLE
"Cannot allocate memory" when trying to sync a node for the first time

### ISSUE THREAD

**Issue by mappum** [solana-labs/solana#11002]
#### Problem

I am trying to run a node on a machine with 32GB memory, with low usage. It seems to unpack the state snapshot then suddenly fail to allocate memory even though it should have plenty.

```
[2020-07-11T00:06:30.633249562Z INFO  solana_ledger::snapshot_utils] snapshot untar took 59.3s
[2020-07-11T00:06:30.633264493Z INFO  solana_ledger::snapshot_utils] snapshot version: 1.2.0
[2020-07-11T00:06:30.633287157Z INFO  solana_ledger::snapshot_utils] Loading bank from "/home/mappum/validator-ledger/snapshot/.tmpdXkGH7/snapshots/11227805/11227805"
[2020-07-11T00:06:30.634890898Z INFO  solana_ledger::snapshot_utils] Rebuilding accounts...
thread 'main' panicked at 'failed to map the data file: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', runtime/src/append_vec.rs:177:19
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: __libc_start_main
  24: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-07-11T00:06:30.803041918Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'failed to map the data file: Os { code: 12, kind: Other, message: \"Cannot allocate memory\" }', runtime/src/append_vec.rs:177:19" location="runtime/src/append_vec.rs:177:19"

```

**Comment by sakridge** [comment]
can you increase `ulimit -n`/`vm.max_map_count` to 500,000.

**Comment by mappum** [comment]
This worked, thanks.
