### ISSUE TITLE
1.2.18 crashes upon RPC requests

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#11389]
#### Problem

```
thread 'http.worker130' panicked at 'called `Option::unwrap()` on a `None` value', core/src/rpc.rs:124:20
stack backtrace:

...

  14: core::panicking::panic
             at src/libcore/panicking.rs:52
  15: solana_core::rpc::JsonRpcRequestProcessor::bank
  16: solana_core::rpc::JsonRpcRequestProcessor::get_program_accounts
  17: <solana_core::rpc::RpcSolImpl as solana_core::rpc::rpc_impl_RpcSol::gen_server::RpcSol>::get_program_accounts

...
```
We're hitting the same unwrap for `get_minimum_balance_for_rent_exemption` and `get_account_info`

I believe we're accepting these requests before the validator has caught up to the cluster.  Will pull a log shortly

#### Proposed Solution

Triage and fix

cc/ @mvines @CriesofCarrots @jstarry

**Comment by t-nelson** [comment]
Said log: [RPaniC.log](https://github.com/solana-labs/solana/files/5030915/RPaniC.log)
