### ISSUE TITLE
BanksServer panics on solana-tokens rerun

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#12397]
#### Problem
Node panics if a solana-tokens command is rerun.

STR:
- Start a local node
- Start a `solana-tokens` distribution and then interrupt it by hitting cmd-C
- Immediately run the same command again (this works on non-BanksClient implementations -- v1.3 and earlier -- to continue tracking the confirmations of the in-progress transactions).

```
thread 'send-tx-svc' panicked at 'assertion failed: `(left == right)`
  left: `4835425952`,
 right: `0`', /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libstd/macros.rs:16:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
   6: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   7: std::panicking::rust_panic_with_hook
   8: rust_begin_unwind
   9: std::panicking::begin_panic_fmt
  10: std::sync::mpsc::shared::Packet<T>::decrement
  11: std::sync::mpsc::shared::Packet<T>::recv
  12: std::sync::mpsc::Receiver<T>::recv_deadline
  13: std::sync::mpsc::Receiver<T>::recv_timeout
  14: solana_banks_server::send_transaction_service::SendTransactionService::retry_thread::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

#### Proposed Solution
Identify bug and fix

**Comment by CriesofCarrots** [comment]
BanksClient has been removed from solana-tokens

**Comment by CriesofCarrots** [comment]
BanksClient is still implemented in v1.4, and also causes this panic in the RPC node:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', metrics/src/metrics.rs:107:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  15: <solana_metrics::metrics::InfluxDbMetricsWriter as solana_metrics::metrics::MetricsWriter>::write
  16: solana_metrics::metrics::MetricsAgent::write
  17: solana_metrics::metrics::MetricsAgent::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mvines** [comment]
We should just turn off the BanksClient tarpc port entirely in solana-validator v1.4 and above.  It's a dead end for cluster-level usage and doesn't even work on mainnet, clients will use JSON RPC.

**Comment by CriesofCarrots** [comment]
Works for me. I plan to remove BanksClient from solana-tokens v1.4 on Monday. I'll follow that up with solana-validator removal.
