### ISSUE TITLE
Crash from tower root assertion on validator startup

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#12591]
#### Problem

```
[2020-09-30T15:59:58.256677117Z INFO  solana_ledger::blockstore_processor] ledger processed in 50ms. 94 MB allocated. root=38185448, 1 fork at 38185448,
 with 1 frozen bank
[2020-09-30T15:59:58.498848424Z INFO  solana_core::consensus] adjusting lockouts (after replay up to 38185448): [38186913, 38186914, 38186915, 38186916,
 38186917, 38186918, 38186919, 38186920, 38186921, 38186922, 38186923, 38186924, 38186925, 38186926, 38186927, 38186928, 38186929, 38186930, 38186931, 3
8186932, 38186933, 38186934, 38186935, 38186936, 38186937, 38186938, 38186939, 38186940, 38186941, 38186942, 38186943]
thread 'main' panicked at 'tower root: 38186912 >= replayed root slot: 38185448', core/src/consensus.rs:778:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  12: std::panicking::begin_panic
  13: solana_core::consensus::Tower::adjust_lockouts_after_replay
  14: solana_core::validator::Validator::new
  15: solana_validator::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  19: std::panicking::try
             at src/libstd/panicking.rs:325
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-09-30T15:59:58.553233401Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at core/src/consensus.rs:778:9" location="core/src/consensus.rs:778:9"
```

#### Proposed Solution

Debug and fix

**Comment by sakridge** [comment]
cc @carllin

**Comment by sakridge** [comment]
It's on lemond: `/home/sakridge/solana/mainnet-beta/ledger.tar.zst`

**Comment by ryoqun** [comment]
reboot history:

```
[2020-09-29T23:25:29.523187347Z INFO  solana_validator] Starting validator with: ArgsOs {
[2020-09-29T23:26:39.266158012Z INFO  solana_core::validator] Starting validator with working bank slot 38029399
[2020-09-29T23:45:32.681275181Z INFO  solana_validator] Starting validator with: ArgsOs {
[2020-09-29T23:46:45.047700351Z INFO  solana_core::validator] Starting validator with working bank slot 38032619
[2020-09-29T23:58:35.638085318Z INFO  solana_validator] Starting validator with: ArgsOs {
[2020-09-29T23:59:41.744267177Z INFO  solana_core::validator] Starting validator with working bank slot 38034571
[2020-09-30T15:50:11.829316723Z INFO  solana_validator] Starting validator with: ArgsOs {
[2020-09-30T15:52:29.929418391Z INFO  solana_core::validator] Starting validator with working bank slot 38185755

```

**Comment by ryoqun** [comment]
Ok, I spotted the root cause: snapshot fetch is broken; it fetches older snapshot even if they have newer one locally.....

```
[2020-09-30T15:52:11.860064982Z INFO  solana_download_utils]   Downloaded http://90.188.226.112:8899/snapshot-38185755-4PL49huzCx8BDd3o2gBq1fo9vzEDgKkMejok5jmztSdJ.tar.zst (217388130 bytes) in 82.291568817s
[2020-09-30T15:52:30.237455307Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=38185755i root=38185755i
[2020-09-30T15:52:54.033035945Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=38185756i root=38185755i
[2020-09-30T15:52:54.070103746Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=38185757i root=38185755i
...
[2020-09-30T15:56:56.669368041Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=38186941i root=38186910i
[2020-09-30T15:56:56.851872527Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=38186942i root=38186911i
[2020-09-30T15:56:57.136221824Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=38186943i root=38186912i
[2020-09-30T15:59:27.412823376Z INFO  solana_download_utils] Removing old snapshot: "/home/sakridge/solana/mainnet-beta/validator-ledger/snapshot-38185755-4PL49huzCx8BDd3o2gBq1fo9vzEDgKkMejok5jmztSdJ.tar.zst"
... <validator restarts>
[2020-09-30T15:59:40.524432223Z INFO  solana_download_utils]   Downloaded http://18.212.219.11:9999/snapshot-38185448-FXnTYv9ACFursP56YyJcNueKzzqvsFXLYziUmn2UHHJN.tar.zst (215376790 bytes) in 13.106761712s

```

**Comment by ryoqun** [comment]
At first run, the validator has ledger slot 38185755 - 38186943.

At next run, it fetches the older snapshot (slot: 38185448) after removing the newer one (38185755) fetched at the first run.

**Comment by ryoqun** [comment]
The ultimate fix will be not to fetch older snapshot than local one, never.

Also, I'll add a bit of clear condition check for `reconcile` function and tower.
