### ISSUE TITLE
Solana validator v1.4.2 is not starting: thread 'main' panicked at 'slot_in_tower(43526861) < checked_slot(43526861)'

### ISSUE THREAD

**Issue by xni** [solana-labs/solana#13128]
#### Problem

When I'm trying to start the validator, this error can be observed in logs:

```
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]: [2020-10-24T07:26:28.053215234Z INFO  solana_core::consensus] adjusting lockouts (after replay up to 43615565): [43526861] tower root: 43526861 replayed root: 43615565
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]: thread 'main' panicked at 'slot_in_tower(43526861) < checked_slot(43526861)', core/src/consensus.rs:931:21
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]: stack backtrace:
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    0: backtrace::backtrace::libunwind::trace
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    1: backtrace::backtrace::trace_unsynchronized
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    2: std::sys_common::backtrace::_print_fmt
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/sys_common/backtrace.rs:78
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/sys_common/backtrace.rs:59
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    4: core::fmt::write
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libcore/fmt/mod.rs:1076
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    5: std::io::Write::write_fmt
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/io/mod.rs:1537
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    6: std::sys_common::backtrace::_print
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/sys_common/backtrace.rs:62
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    7: std::sys_common::backtrace::print
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/sys_common/backtrace.rs:49
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    8: std::panicking::default_hook::{{closure}}
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/panicking.rs:198
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:    9: std::panicking::default_hook
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/panicking.rs:217
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   11: std::panicking::rust_panic_with_hook
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/panicking.rs:530
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   12: rust_begin_unwind
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/panicking.rs:437
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   13: std::panicking::begin_panic_fmt
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/panicking.rs:391
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   14: solana_core::consensus::Tower::adjust_lockouts_after_replay
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   15: solana_core::validator::Validator::new
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   16: solana_validator::main
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   17: std::rt::lang_start::{{closure}}
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:   18: std::rt::lang_start_internal::{{closure}}
Oct 24 00:26:28 ubuntu-s-8vcpu-16gb-lon1-01 solana-validator[8787]:              at src/libstd/rt.rs:52
```

v1.4.2

**Comment by ryoqun** [comment]
@xni Sorry for any inconvenience. I'm currently working to fix it. As a work around, you can just remove the tower file in your ledger directory. The tower file is named like this: `tower-6tvK8JzXi5NDHEmpedQhBturfnRz2FK5CVj9UhSLNTCp.bin`

**Comment by ryoqun** [comment]
@xni  I also noticed that if removing the tower file didn't work, you could also try removing `--no-snapshot-fetch`.
