### ISSUE TITLE
web3: Inconsistent pubkey specification/usage in `compileMessage()`

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#13174]
#### Problem

In `Transaction.compileMessage()`,  if caller has constructed the instructions by specifying `PublicKey`s as `String`s, an ever so informative `TypeError: x.pubkey.equals is not a function` is thrown.  This can happen both where we promote the `feePayer` and where we check for unexpected signers

#### Proposed Solution

Runtime type-check or coerce and pray

cc/ @jstarry

**Comment by jstarry** [comment]
It is really unfortunate that the type errors are so uninformative here. Too bad we can't expect everyone to use TypeScript or Flow JS when using our library. I think this issue will end up being part of a broader change to adequately guard our API's against bad input

**Comment by jstarry** [comment]
@t-nelson I don't really understand the title of this issue. How about something like "web3: API does not guard against invalid pubkey inputs"?

**Comment by raghibislam** [comment]
`transaction.ts:285 Uncaught (in promise) TypeError: x.pubkey.equals is not a function
    at transaction.ts:285:1
    at Array.findIndex (<anonymous>)
    at Transaction.compileMessage (transaction.ts:284:1)
    at Transaction._compile (transaction.ts:376:1)
`
I am getting this error.

**Comment by David00154** [comment]
this issue has not yet been fixed

**Comment by David00154** [comment]
To actually fix this error if it still exist, just do this as so new Public('...'). 
Replace the ... with your public key

**Comment by t-nelson** [comment]
> To actually fix this error if it still exist, just do this as so new Public('...'). Replace the ... with your public key

are you volunteering to fix this issue?
