### ISSUE TITLE
Validators crash when node count is high (e.g. 150) 

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1397]
Some validators crash when network has high node count. The following crash was observed with 150 validators.
```
thread 'solana-listen' panicked at 'assertion failed: len <= BLOB_SIZE', src/packet.rs:235:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::begin_panic
   7: solana::packet::to_blob
   8: solana::crdt::Crdt::handle_protocol
   9: solana::crdt::Crdt::run_listen
```

This is because the gossip response are bigger than blob size.

**Comment by aeyakovenko** [comment]
fixed in #1493
