### ISSUE TITLE
solana-gossip-responder panic!ed

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#14074]
#### Problem

```
thread 'solana-responder-gossip' panicked at 'assertion failed: `(left == right)`
  left: `139986357043200`,
 right: `0`', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  14: std::sync::mpsc::shared::Packet<T>::recv
  15: std::sync::mpsc::Receiver<T>::recv_timeout
  16: solana_streamer::streamer::recv_send
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-12-11T12:20:30.622392404Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-responder-gossip" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `139986357043200`,
     right: `0`', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9" location="/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9"
```

**Comment by CriesofCarrots** [comment]
STR: `./run.sh` 
Presents about every other run

**Comment by behzadnouri** [comment]
This is likely because of a bug in std channels: https://github.com/rust-lang/rust/issues/39364#issuecomment-381446873
> We start off with a oneshot or stream channel (it's the same for both). Now we recv_timeout on it. While that receive is running, the channel is upgraded to a shared.

The workaround seems to be to clone the channel before spawning the thread which listens on the channel:
https://github.com/solana-labs/solana/blob/5a285e430/gossip/src/gossip_service.rs#L81-L85

So this should be "fixed" in: https://github.com/solana-labs/solana/pull/17647

**Comment by behzadnouri** [comment]
closing the issue as we have moved to crossbeam channels which does not have this bug.
