### ISSUE TITLE
CI Failing unpredictably on test: fullnode::tests::test_validator_to_leader_transition

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1424]
ci/docker-run.sh solanalabs/rust-nightly:2018-09-28 ci/test-nightly.sh

```
---- fullnode::tests::test_validator_to_leader_transition stdout ----
thread 'fullnode::tests::test_validator_to_leader_transition' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `20`', src/fullnode.rs:705:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:346
   7: solana::fullnode::tests::test_validator_to_leader_transition
             at src/fullnode.rs:705
   8: solana::fullnode::tests::test_validator_to_leader_transition::{{closure}}
             at src/fullnode.rs:628
   9: core::ops::function::FnOnce::call_once
             at libcore/ops/function.rs:238
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1468
             at libcore/ops/function.rs:238
             at liballoc/boxed.rs:661
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

**Comment by garious** [comment]
I've seen that too. @carllin, can you take a look?
