### ISSUE TITLE
validator panic on failed snapshot bank verification

### ISSUE THREAD

**Issue by phenomax** [solana-labs/solana#14363]
#### Problem

the validator paniced on failed snapshot bank verification

```
solana-validator --version
solana-validator 1.4.14 (src:eb0a448b; feat:569138916)
```

```

2020-12-30T22:27:13.674197531Z WARN  solana_runtime::accounts_db] Mismatched total lamports: 488589552453676692 calculated: 488589552453676676
[2020-12-30T22:27:13.674198656Z INFO  solana_metrics::metrics] datapoint: update_accounts_hash accounts_scan=31833729i hash_accumulate=727172i hash_total=5521468i
[2020-12-30T22:27:13.676993087Z WARN  solana_runtime::accounts] verify_bank_hash failed: MismatchedTotalLamports(488589552453676676, 488589552453676692)
thread 'main' panicked at 'Snapshot bank for slot 58257183 failed to verify', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:530
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  14: solana_runtime::snapshot_utils::bank_from_archive
  15: solana_ledger::bank_forks_utils::load
  16: solana_core::validator::Validator::new
  17: solana_validator::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  21: std::panicking::try
             at src/libstd/panicking.rs:325
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-12-30T22:27:13.785656136Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Snapshot bank for slot 58257183 failed to verify', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9" location="/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9"

```

start parameters

```
sol-validator solana-validator \
  --identity ~/solana/validator-keypair.json \
  --vote-account ~/solana/vote-account-keypair.json \
  --ledger ~/solana/validator-ledger \
  --trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
  --no-untrusted-rpc \
  --rpc-port 8899 \
  --private-rpc \
  --dynamic-port-range 8000-8010 \
  --entrypoint mainnet-beta.solana.com:8001 \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --wal-recovery-mode skip_any_corrupted_record \
  --limit-ledger-size \
  --log ~/solana/solana-validator.log
```

**Comment by ryoqun** [comment]
Thanks for detailed report!

> solana-validator 1.4.14 (src:eb0a448b; feat:569138916)

@phenomax Well, your version is too old? Upgrading to 1.4.19 should fix your issue. Could you try that?

CC: @sakridge

**Comment by phenomax** [comment]
Thank you for your fast reply. Yes, upgrading fixed the issue.
I was lazy and copied the install command from https://docs.solana.com/cli/install-solana-cli-tools, which is still on 1.4.14
