### ISSUE TITLE
AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by nnngggaaa** [solana-labs/solana#14678]
#### Problem
solana-cli 1.4.23 (src:375295a6; feat:1441058695)

after some delinquency (25000+ slots behind) i removed ledger and restarted node but it panics with the message from title:
```
[2021-01-19T23:55:01.061935483Z INFO  solana_download_utils]   Downloaded http://34.90.36.12:80/snapshot-61447362-DK21eYvEAZGesir9hDxjr11CJP1hwicaMspe5Maey1Eu.tar.zst (6003596503 bytes) in 65.326948944s
[2021-01-19T23:55:01.197932832Z WARN  solana_core::validator] identity: 9Mo3ap3jpuqQpLi75EsiXLWfTr1cbBhrJNumoq1wnVp6
[2021-01-19T23:55:01.197997179Z WARN  solana_core::validator] vote account: 9K67smfw8hDXmtnR7uvP62WrKUcB7oZ8cvpsB1hmrCzf
[2021-01-19T23:55:01.198014650Z WARN  solana_core::validator] authorized voter: 9Mo3ap3jpuqQpLi75EsiXLWfTr1cbBhrJNumoq1wnVp6
[2021-01-19T23:55:01.198029268Z WARN  solana_core::validator] CUDA is disabled
[2021-01-19T23:55:01.198038074Z INFO  solana_core::validator] AVX detected
[2021-01-19T23:55:01.198045356Z INFO  solana_core::validator] entrypoint: Some(ContactInfo { id: 11111111111111111111111111111111, gossip: V4(34.83.231.102:8001), tvu: V4(0.0.0.0:0), tvu_forwards: V4(0.0.0.0:0), repa
ir: V4(0.0.0.0:0), tpu: V4(0.0.0.0:0), tpu_forwards: V4(0.0.0.0:0), unused: V4(0.0.0.0:0), rpc: V4(0.0.0.0:0), rpc_pubsub: V4(0.0.0.0:0), serve_repair: V4(0.0.0.0:0), wallclock: 1611100412978, shred_version: 0 })
[2021-01-19T23:55:01.198097947Z INFO  solana_core::validator] Initializing sigverify...
[2021-01-19T23:55:01.198105714Z INFO  solana_core::validator] Done.
[2021-01-19T23:55:01.198165194Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 1048576
[2021-01-19T23:55:01.198174542Z INFO  solana_ledger::blockstore] Opening database at "/root/solana/validator-ledger/rocksdb"
[2021-01-19T23:55:01.305805980Z INFO  solana_ledger::blockstore] "/root/solana/validator-ledger/rocksdb" open took 107ms
[2021-01-19T23:55:01.305882693Z INFO  solana_core::validator] Searching for incorrect shreds..
[2021-01-19T23:55:01.307730886Z INFO  solana_core::validator] Cleaning accounts paths..
[2021-01-19T23:55:01.307994605Z WARN  solana_core::validator] encountered error removing accounts path: "/root/solana/validator-ledger/accounts"
[2021-01-19T23:55:01.308135107Z INFO  solana_core::validator] done. clean_accounts_paths took 369us
[2021-01-19T23:55:01.308152287Z INFO  solana_core::validator] loading ledger from "/root/solana/validator-ledger"...
[2021-01-19T23:55:01.312491951Z INFO  solana_core::validator] genesis hash: 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d
[2021-01-19T23:55:01.312551946Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 1048576
[2021-01-19T23:55:01.312562245Z INFO  solana_ledger::blockstore] Opening database at "/root/solana/validator-ledger/rocksdb"
[2021-01-19T23:55:01.392399849Z INFO  solana_ledger::blockstore] "/root/solana/validator-ledger/rocksdb" open took 79ms
[2021-01-19T23:55:01.393121080Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "/root/solana/validator-ledger/snapshot"
[2021-01-19T23:55:01.395506666Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "/root/solana/validator-ledger/snapshot-61447362-DK21eYvEAZGesir9hDxjr11CJP1hwicaMspe5Maey1Eu.tar.zst"
^[[2021-01-19T23:55:11.598300663Z INFO  solana_runtime::hardened_unpack] unpacked 103697 entries so far...
^[[5~^[[5~^[[5~^[[5~[2021-01-19T23:55:23.536037919Z INFO  solana_runtime::hardened_unpack] unpacked 192210 entries so far...
[2021-01-19T23:55:33.536212397Z INFO  solana_runtime::hardened_unpack] unpacked 295114 entries so far...
[2021-01-19T23:55:43.536349184Z INFO  solana_runtime::hardened_unpack] unpacked 396812 entries so far...
[2021-01-19T23:55:50.541918208Z INFO  solana_runtime::hardened_unpack] unpacked 447970 entries total
[2021-01-19T23:55:50.542045551Z INFO  solana_runtime::snapshot_utils] snapshot untar took 49.1s
[2021-01-19T23:55:50.542060276Z INFO  solana_runtime::snapshot_utils] snapshot version: 1.2.0
[2021-01-19T23:55:50.542093271Z INFO  solana_runtime::snapshot_utils] Loading bank from "/root/solana/validator-ledger/snapshot/tmp-snapshot-LwR5yS/snapshots/61447362/61447362"
[2021-01-19T23:56:01.489551431Z INFO  solana_runtime::serde_snapshot] 323685 slots remaining...
[2021-01-19T23:56:11.489583413Z INFO  solana_runtime::serde_snapshot] 203454 slots remaining...
[2021-01-19T23:56:21.489607714Z INFO  solana_runtime::serde_snapshot] 93004 slots remaining...
[2021-01-19T23:56:28.305105158Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305139725Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305151350Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305160386Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305169662Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305178575Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305187818Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305196378Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305204828Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305214096Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305223489Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305233299Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305241721Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305265912Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305275948Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:56:28.305286708Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-19T23:58:23.936907300Z ERROR solana_runtime::append_vec] AppendVec failed to remove "": Os { code: 2, kind: NotFound, message: "No such file or directory" }
Suppressed 11196 messages from solana.service
thread 'main' panicked at 'Load from snapshot failed: Serialize(Io(Custom { kind: Other, error: Error { kind: Other, message: "other os error" } }))', ledger/src/bank_forks_utils.rs:73:18
stack backtrace:
   0:     0x55b89f5780d5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55b89f5780d5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55b89f5780d5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55b89f5780d5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55b89f5a772c - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55b89f56f082 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x55b89f57ae30 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55b89f57ae30 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b89f57ae30 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x55b89f57ab7c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x55b89f1d4770 - solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}::h73915b33dfbd788b
  11:     0x55b89f57b498 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:530
  12:     0x55b89f57b06b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  13:     0x55b89f5a53b1 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  14:     0x55b89f5a5073 - core::option::expect_none_failed::h188f17af6c9f404b
                               at src/libcore/option.rs:1269
  15:     0x55b89e9cf06c - solana_ledger::bank_forks_utils::load::h9202c24547d91279
  16:     0x55b89e694d10 - solana_core::validator::Validator::new::h9a723211451e0433
  17:     0x55b89e434f72 - solana_validator::main::h6ec1c8886cb13385
  18:     0x55b89e456a23 - std::rt::lang_start::{{closure}}::h05e6f9a72d44c771
  19:     0x55b89f57b913 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  20:     0x55b89f57b913 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  21:     0x55b89f57b913 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  22:     0x55b89f57b913 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  23:     0x55b89f57b913 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  24:     0x55b89e438542 - main
  25:     0x7f50ac229b97 - __libc_start_main
  26:     0x55b89e41962a - _start
  27:                0x0 - <unknown>
[2021-01-19T23:58:29.042560705Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Load from snapshot failed: Serialize(Io(Custom { kind: Other, error: Error { kind: Other, message: \"other os error\" } }))', ledger/src/bank_forks_utils.rs:73:18" location="ledger/src/bank_forks_utils.rs:73:18"
[2021-01-19T23:58:29.042594499Z INFO  solana_metrics::metrics] submitting 2 points
solana.service: Main process exited, code=exited, status=1/FAILURE
solana.service: Failed with result 'exit-code'.
```

#### Proposed Solution

I do not know

**Comment by nnngggaaa** [comment]
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             32G     0   32G   0% /dev
tmpfs           6.3G  888K  6.3G   1% /run
/dev/md2        906G   73G  788G   9% /
tmpfs            32G     0   32G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/md1        487M  208M  254M  46% /boot
tmpfs           6.3G     0  6.3G   0% /run/user/0
tmpfs            32G   13G   20G  40% /root/solana/validator-ledger/accounts
```

**Comment by nnngggaaa** [comment]
```
# ls -l --full-time  /root/solana/validator-ledger/
total 10438024
drwxrwxrwt  2 root root    6696420 2021-01-19 22:44:14.161806539 -0800 accounts
drwxr-xr-x  2 root root    1269760 2021-01-19 22:44:14.077806770 -0800 accounts-shrink
-rw-r--r--  1 root root     132347 2020-03-15 21:59:57.000000000 -0700 genesis.bin
-rw-r--r--  1 root root      20144 2021-01-19 15:26:11.367206879 -0800 genesis.tar.bz2
drwxr-xr-x  2 root root      12288 2021-01-19 22:41:57.574178175 -0800 rocksdb
drwxr-xr-x 10 root root       4096 2021-01-19 22:44:09.201820103 -0800 snapshot
-rw-r--r--  1 root root 6305543713 2021-01-19 15:37:14.965715726 -0800 snapshot-61444603-J6ogz9fcPfKUQSxhk4JMorg5JMbtvLsJp7akpipJ8HZV.tar.zst
-rw-r--r--  1 root root 2114172219 2021-01-19 22:35:23.959231002 -0800 snapshot-61491020-FovMoe9PeMEfr6t4y1XF2ziX83EqhX7yNkdr7RQrsz7Z.tar.zst
-rw-r--r--  1 root root 2267344922 2021-01-19 22:41:07.386311849 -0800 snapshot-61491615-5QZKFYEDxRKvsvEueyTE4SKogqPLpmngTBWABCnXR1qY.tar.zst
drwxr-xr-x  2 root root       4096 2021-01-19 15:26:11.379206853 -0800 tmp-genesis
-rw-r--r--  1 root root       3808 2021-01-19 22:44:13.745807677 -0800 tower-9Mo3ap3jpuqQpLi75EsiXLWfTr1cbBhrJNumoq1wnVp6.bin
```

**Comment by nnngggaaa** [comment]
```
/root/.local/share/solana/install/active_release/bin/solana-validator \
  --entrypoint=mainnet-beta.solana.com:8001 \
  --identity=/root/solana/validator-keypair.json \
  --vote-account=/root/solana/vote-account-keypair.json \
  --ledger=/root/solana/validator-ledger \
  --trusted-validator=7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --trusted-validator=GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --trusted-validator=DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --trusted-validator=CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
  --dynamic-port-range=8001-8020 \
  --gossip-port=8001 \
  --rpc-port=8899 \
  --private-rpc \
  --no-untrusted-rpc \
  --rpc-bind-address 127.0.0.1 \
  --limit-ledger-size 50000000 \
  --accounts /root/solana/validator-ledger/accounts/ --account-shrink-path /root/solana/validator-ledger/accounts-shrink \
  --wal-recovery-mode skip_any_corrupted_record \
  --snapshot-interval-slots 500 \
  --log - \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --expected-shred-version 13490 \
  --wait-for-supermajority 53180900 \
  --expected-bank-hash Fi4p8z3AkfsuGXZzQ4TD28N8QDNSWC7ccqAqTs2GPdPu
```

**Comment by nnngggaaa** [comment]
Should note that after i several more restarts it just started working and now the issue is gone. I have not done anything - went asleep after filling the issue

**Comment by mvines** [comment]
Closing this for now, it seems obsolete
