### ISSUE TITLE
Flaky test_filter_current test

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#14744]
#### Problem

https://buildkite.com/solana-labs/solana/builds/38461#28898df8-f4d0-4809-aa29-93c35584ab64

```

---- crds_value::test::test_filter_current stdout ----
--
  | thread 'crds_value::test::test_filter_current' panicked at 'assertion failed: `(left == right)`
  | left: `CrdsValue { signature: UfQbpzAAHLGbbinfrRcGo5pK5b24H2bndeaQgPBDH44BVwX2NjqCmh893zNLZFZmGMD5PGPchFZwByiHrNSbV4r, data: SnapshotHashes(SnapshotHash { from: 2hUWfxRFwiJf9ioDWxkZ4nczGM86y6FCKkX9fQWkX1Vo, hashes: [(47826071, Atb1byD2enxDbLzLE9V54AkmEHbvhEsoHLNFNjeicXmG), (47825731, ARuE5q8YU3aoxRKi9j21YAUBDJSJfc1qV1bNbmvsEmmV), (47825897, C1mgsNXfsZbxHE15YgrqQ3fibsr16jUCG27CpHD27tX8), (47826059, 8DjLiKs7mDG2u1bjv8QcPJrUM1B4mgucRN8Twd8ppW1L), (47825863, FH7mDhshBfuH8kGPW1eTV59FpAMEse1CY3yzvwyUL1WU), (47825890, DtNLbXt9sKhPszkpNrXKb6xsAuhbCHxC2Dszy9HautuR), (47826122, HZDs4qHWgc3sbd6fHwoY7beCjYfXxTZPBiQAVtVXrwWk), (47825945, 7WWML1GZityMMY9w4nCnE5hEJnYJbdAKKa9Fs5nq8V2n)], wallclock: 1611249090723 }) }`,
  | right: `CrdsValue { signature: 5zNDcKYUiPVt1GBiQgdtuiF5sNujFJMrob2Trwm27uBcqRdTGYEunwyVCsZ63uV234sMRGvUm131hkyQKikV2Ddb, data: SnapshotHashes(SnapshotHash { from: 2hUWfxRFwiJf9ioDWxkZ4nczGM86y6FCKkX9fQWkX1Vo, hashes: [(47826010, 5yafFrA7mXgDbBhZqcyAFPdfHvVQGktZmDnEN6WhaDoc), (47825769, i6e3ezSstCe8nh8SiQxJfW7tWWRkRSCxTSfE2dE3nkM), (47826031, FFp5SYtCdckKSjAATqMjH9RVmr4kqwGvKwtadWkuUeg5), (47826137, JB3aPZtvUpQUAeGAGsmLje9fqd8bmQTLxooCj6k6GkUG), (47826098, 5SzVaytfvvn1Uk2UytgPaACyBD5rAYmqtRZb6o4VNpBt), (47825891, 5EJpZu6sSqkjYYJiyBpS5EoSzLeCPvwcb3mCWHQLhZBC), (47826105, 3dmYzJXwbFJEDGoBX6b7CUoVbzV883a1aicZfn1XNDc7)], wallclock: 1611249090723 }) }`', core/src/crds_value.rs:865:21
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/7efc097c4fe6e97f54a44cee91c56189e9ddb41c/library/std/src/panicking.rs:493:5
  | 1: core::panicking::panic_fmt
  | at /rustc/7efc097c4fe6e97f54a44cee91c56189e9ddb41c/library/core/src/panicking.rs:92:14
  | 2: solana_core::crds_value::test::test_filter_current
  | at ./src/crds_value.rs:865:21
  | 3: solana_core::crds_value::test::test_filter_current::{{closure}}
  | at ./src/crds_value.rs:844:5
  | 4: core::ops::function::FnOnce::call_once
  | at /rustc/7efc097c4fe6e97f54a44cee91c56189e9ddb41c/library/core/src/ops/function.rs:227:5
  | 5: core::ops::function::FnOnce::call_once
  | at /rustc/7efc097c4fe6e97f54a44cee91c56189e9ddb41c/library/core/src/ops/function.rs:227:5
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  |  
  |  
  | failures:
  | crds_value::test::test_filter_current

```

#### Proposed Solution

Debug and fix

**Comment by sakridge** [comment]
@behzadnouri any idea on this?

**Comment by behzadnouri** [comment]
> @behzadnouri any idea on this?

I will fix this. Thanks,

**Comment by sakridge** [comment]
I saw another failure:
https://buildkite.com/solana-labs/solana/builds/38702#26671966-2998-4a1c-ba46-4d6debb48280

Which is on ab02b5bb with the fix

**Comment by behzadnouri** [comment]
This is weird. I ran the test 1000 times locally and no failures.
Besides, with fixed seed, reruns should not matter anymore.

**Comment by behzadnouri** [comment]
I think this is because `new_rand_timestamp` is using current system time:
https://github.com/solana-labs/solana/blob/e1021d9f8/core/src/crds_value.rs#L134
which when generating several random crds-value may change from one to the other.
So fixing random seed is not enough.

I sent out https://github.com/solana-labs/solana/pull/14816
