### ISSUE TITLE
Unreliable CI Failure: test_boot_validator_from_file

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#1484]
---- test_boot_validator_from_file stdout ----
thread 'test_boot_validator_from_file' panicked at 'assertion failed: `(left == right)`
  left: `500`,
 right: `1000`', tests/multinode.rs:465:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: multinode::test_boot_validator_from_file
             at tests/multinode.rs:465
   8: multinode::__test::TESTS::{{closure}}
             at tests/multinode.rs:441
   9: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:642
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105

failures:
    test_boot_validator_from_file

**Comment by jackcmay** [comment]
Still seeing this issue in CI, can we disable until resolved?

**Comment by mvines** [comment]
yes please!

**Comment by jackcmay** [comment]
Ignored in #1576
