### ISSUE TITLE
bench-tps panic 1.4.26

### ISSUE THREAD

**Issue by HM999** [solana-labs/solana#15174]
#### Problem

Upon running a *second* test using same genesis block...
```
$ ./target/release/solana-validator -V
solana-validator 1.4.26 (src:devbuild; feat:3847334683)

Terminal 1: 

NDEBUG=1 ./multinode-demo/faucet.sh
...
[2021-02-06T11:51:28.919126739Z INFO  solana_faucet::faucet] Requesting airdrop of 1398135952500000 to AXggds3EzUsHEtP6LFM2TmCBH7Samec3DkCnj8dZybn8
[2021-02-06T11:51:28.919203849Z INFO  solana_metrics::metrics] datapoint: faucet-airdrop request_amount=1398135952500000i request_current=1398135952500000i
[2021-02-06T11:51:28.919213462Z INFO  solana_faucet::faucet] Airdrop transaction granted
...

Terminal 2: 

NDEBUG=1 ./multinode-demo/bench-tps.sh
....
thread 'main' panicked at 'Error requesting airdrop: to addr: 127.0.0.1:9900 amount: 1398135952500000 Err(Custom("ForUser(\"signature not found after 21 seconds\")"))', /home/u1/perf_test/solana/bench-tps/src/bench.rs:749:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: solana_bench_tps::bench::generate_and_fund_keypairs
   3: solana_bench_tps::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-02-06T11:53:14.396342456Z ERROR solana_metrics::metrics] datapoint: panic program="bench-tps" thread="main" one=1i message="panicked at 'Error requesting airdrop: to addr: 127.0.0.1:9900 amount: 1398135952500000 Err(Custom(\"ForUser(\\"signature not found after 21 seconds\\")\"))', /home/u1/perf_test/solana/bench-tps/src/bench.rs:749:25" location="/home/u1/perf_test/solana/bench-tps/src/bench.rs:749:25"

Terminal 1:

[2021-02-06T11:52:36.911465590Z INFO  solana_faucet::faucet] Error in request: Custom { kind: Other, error: "deserialize packet in faucet: Custom(\"invalid value: integer `1414745936`, expected variant index 0 <= i < 1\")" }
```

#### Proposed Solution

Can be saved by running setup.sh and starting again with a new genesis block... but this used to work.

**Comment by CriesofCarrots** [comment]
This seems resolved. Please reopen if issues persist.
