### ISSUE TITLE
Capitalization panic in testnet simulation

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#15180]
#### Problem

Capitalization panic in testnet simulation:
https://discordapp.com/channels/428295358100013066/439194979856809985/807491877015388160

```
2021-02-06 05:26:32 | Eqr2dzMoqHZ3t8QpYyDs8JtUQMYpWmTzZ2ujSNgN3FEv | validator | solana-accounts-background | 
panicked at 'assertion failed: `(left == right)` left: `1000189065363148006`, right: `1000189065482728910`', runtime/src/bank.rs:4334:9

2021-02-06 05:16:32 | 9hm9DnKHS5zKYQDCnRiA58fKttVXb7BSPDyKnuCDzTMT | validator | solana-accounts-background | 
panicked at 'assertion failed: `(left == right)` left: `1000189066716389049`, right: `1000189067148716410`', runtime/src/bank.rs:4334:9
```

#### Proposed Solution

Debug and fix it.

**Comment by sakridge** [comment]
cc @ryoqun

**Comment by sakridge** [comment]
Nodes that experienced the panic:
`34.74.225.200     |   831 | Eqr2dzMoqHZ3t8QpYyDs8JtUQMYpWmTzZ2ujSNgN3FEv |    -    | 8001 | none | none | none | none | none | none | 19458`
`34.74.94.243      |   507 | 9hm9DnKHS5zKYQDCnRiA58fKttVXb7BSPDyKnuCDzTMT |  1.5.6  | 8001 | 8003 | 8004 | 8000 | 8002 | 8006 | 8007 | 19458`

**Comment by sakridge** [comment]
From Eqr2dzMoqHZ3t8QpYyDs8JtUQMYpWmTzZ2ujSNgN3FEv
```
[2021-02-06T05:26:32.103469481Z INFO  solana_core::replay_stage] new fork:202368 parent:202367 root:202330
[2021-02-06T05:26:32.103551770Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=202368i block_height=190360i
[2021-02-06T05:26:32.103835935Z INFO  solana_metrics::metrics] datapoint: bank-timestamp get_timestamp_estimate_us=8i
[2021-02-06T05:26:32.103843608Z INFO  solana_metrics::metrics] datapoint: bank-timestamp-correction slot=202368i from_genesis=1612555439i corrected=1612588945i ancestor_timestamp=1612588945i
[2021-02-06T05:26:32.117608493Z INFO  solana_metrics::counter] COUNTER:{"name": "poh_recorder-tick_lock_contention", "counts": 3333777, "samples": 2740000,  "now": 1612589192117, "events": 1}
[2021-02-06T05:26:32.117639257Z INFO  solana_metrics::counter] COUNTER:{"name": "poh_recorder-tick_overhead", "counts": 8495448, "samples": 2740000,  "now": 1612589192117, "events": 0}
[2021-02-06T05:26:32.256776156Z INFO  solana_metrics::metrics] datapoint: optimistic_slot_elapsed average_elapsed_ms=547i
[2021-02-06T05:26:32.256800956Z INFO  solana_metrics::metrics] datapoint: optimistic_slot slot=202367i
[2021-02-06T05:26:32.283463215Z INFO  solana_metrics::metrics] datapoint: calculate_accounts_hash_without_index accounts_scan=43778648i eliminate_zeros=6094484i hash=3661589i sort=4698300i hash_total=79840635i
thread 'solana-accounts-background' panicked at 'assertion failed: `(left == right)`
  left: `1000189065363148006`,
 right: `1000189065482728910`', runtime/src/bank.rs:4334:9
stack backtrace:
[2021-02-06T05:26:32.317585611Z INFO  solana_metrics::metrics] datapoint: shred_fetch_tvu_forwards index_overrun=0i shred_count=297i slot_bad_deserialize=0i index_bad_deserialize=0i index_out_of_bounds=0i slot_out_of_range=0i duplicate_shred=0i
[2021-02-06T05:26:32.318344989Z INFO  solana_core::retransmit_stage] retransmit: packets_by_slot: {202364: 205, 202365: 144, 202366: 146, 202367: 144, 202368: 110}
[2021-02-06T05:26:32.318357774Z INFO  solana_metrics::metrics] datapoint: retransmit-num_nodes count=9i
[2021-02-06T05:26:32.318386521Z INFO  solana_metrics::metrics] datapoint: retransmit-stage total_time=29511i epoch_fetch=1411i epoch_cache_update=620i total_batches=626i total_packets=749i retransmit_total=4765i compute_turbine=6078i repair_total=4i di>
[2021-02-06T05:26:32.318367555Z INFO  solana_core::retransmit_stage] retransmit: top packets_by_source: {94: "34.73.188.55:8005", 95: "35.227.69.60:8005", 100: "35.231.121.54:8005", 105: "34.74.238.143:8005"} len: 8
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: solana_runtime::accounts_background_service::SnapshotRequestHandler::handle_snapshot_requests
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-02-06T05:26:32.324027988Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-accounts-background" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `1000189065363148006`,
     right: `1000189065482728910`', runtime/src/bank.rs:4334:9" location="runtime/src/bank.rs:4334:9"
     ```

**Comment by jeffwashington** [comment]
status: trying to snapshot. 1st attempt failed. pr submitted to revert to previous way of calculating hashes, using index. will restart simulation once snapshot data is captured. This time, we'll pass the flag that duplicates the hash validation process and compares the results.

**Comment by jeffwashington** [comment]
I think the slot is 200888.
And it looks like the hash calculation is different than what the bank has previously reported and the hash's calculation doesn't show up anywhere else in the log.

```
[2021-02-06T05:14:43.861329899Z INFO  solana_runtime::bank] bank frozen: 200888 hash: Hm2bv45q7MGiQnhBUJy3BuJkZE4fY7NrLLjYNnry3fJK accounts_delta: EemCqjfL6NoigmTtU9ULsBev81EWiHP4cgwxarC8xTcy signature_count: 653 last_blockhash: 5xaTtZLrKRBFuqZecWtnrhBVe59B91P1B3VRrpzpYJ9W capitalization: 1000189067148716410
[2021-02-06T05:14:43.861371498Z INFO  solana_runtime::bank] accounts hash slot: 200888 stats: BankHashStats { num_updated_accounts: 856, num_removed_accounts: 0, num_lamports_stored: 254422572374021, total_data_len: 320984, num_executable_accounts: 0 }
...
thread 'solana-accounts-background' panicked at 'assertion failed: `(left == right)`
// code:         assert_eq!(total_lamports, self.capitalization());
  left: `1000189066716389049`,
 right: `1000189067148716410`', runtime/src/bank.rs:4334:9
stack backtrace:
validator.sh: solana-validator --max-genesis-archive-unpacked-size 1073741824 --entrypoint 35.227.69.60:8001 --gossip-port 8001 --rpc-port 8899 --expected-shred-version 19458 --identity /home/solana/solana/net/../config/validator-identity.json --vote-account /home/solana/solana/net/../config/vote-account.json --expected-bank-hash BNUHx6KSntYg2SnX7Y1NZyQDkwZnrHWV56DHS3P4bH87 --init-complete-file init-complete-node.log --wait-for-supermajority 1 --accounts /mnt/solana-accounts --rpc-faucet-address 35.227.69.60:9900 --ledger /home/solana/solana/net/../config/validator --log - --enable-rpc-exit --enable-rpc-set-log-filter --require-tower --no-poh-speed-test
pid: 1211698
[2021-02-06T05:16:37.230389677Z INFO  solana_validator] solana-validator 1.5.6 (src:devbuild; feat:2760126207)
...
[2021-02-06T05:37:51.267927851Z INFO  solana_runtime::bank] bank frozen: 200888 hash: Hm2bv45q7MGiQnhBUJy3BuJkZE4fY7NrLLjYNnry3fJK accounts_delta: EemCqjfL6NoigmTtU9ULsBev81EWiHP4cgwxarC8xTcy signature_count: 653 last_blockhash: 5xaTtZLrKRBFuqZecWtnrhBVe59B91P1B3VRrpzpYJ9W capitalization: 1000189067148716410
[2021-02-06T05:37:51.267943487Z INFO  solana_runtime::bank] accounts hash slot: 200888 stats: BankHashStats { num_updated_accounts: 856, num_removed_accounts: 0, num_lamports_stored: 254422572374021, total_data_len: 320984, num_executable_accounts: 0 }
```

**Comment by jeffwashington** [comment]
validator 2:
slot 202200

```[2021-02-06T05:25:11.011282960Z INFO  solana_runtime::bank] bank frozen: 202200 hash: HshPoKPGe6sQ7XmsoqCQsV8JyF8zRNGJ6grfzDL1Fsv5 accounts_delta: 86tkc5jAWzBfB7hwp1bURTyqytJTHVQJFBN2TRRDM6Q9 signature_count: 1334 last_blockhash: F5DzPrjt2ozXEX3DbdniEziudZs4tAgtWpp5xC8uTA6L capitalization: 1000189065482728910
[2021-02-06T05:25:11.011311509Z INFO  solana_runtime::bank] accounts hash slot: 202200 stats: BankHashStats { num_updated_accounts: 1527, num_removed_accounts: 0, num_lamports_stored: 222095528255484, total_data_len: 395490, num_executable_accounts: 0 }
[2021-02-06T05:26:32.283463215Z INFO  solana_metrics::metrics] datapoint: calculate_accounts_hash_without_index accounts_scan=43778648i eliminate_zeros=6094484i hash=3661589i sort=4698300i hash_total=79840635i
thread 'solana-accounts-background' panicked at 'assertion failed: `(left == right)`
  left: `1000189065363148006`,
 right: `1000189065482728910`', runtime/src/bank.rs:4334:9
stack backtrace:
[2021-02-06T05:26:32.317585611Z INFO  solana_metrics::metrics] datapoint: shred_fetch_tvu_forwards index_overrun=0i shred_count=297i slot_bad_deserialize=0i index_bad_deserialize=0i index_out_of_bounds=0i slot_out_of_range=0i duplicate_shred=0i
[2021-02-06T05:26:32.318344989Z INFO  solana_core::retransmit_stage] retransmit: packets_by_slot: {202364: 205, 202365: 144, 202366: 146, 202367: 144, 202368: 110}
[2021-02-06T05:26:32.318357774Z INFO  solana_metrics::metrics] datapoint: retransmit-num_nodes count=9i
[2021-02-06T05:26:32.318386521Z INFO  solana_metrics::metrics] datapoint: retransmit-stage total_time=29511i epoch_fetch=1411i epoch_cache_update=620i total_batches=626i total_packets=749i retransmit_total=4765i compute_turbine=6078i repair_total=4i discard_total=0i
[2021-02-06T05:26:32.318367555Z INFO  solana_core::retransmit_stage] retransmit: top packets_by_source: {94: "34.73.188.55:8005", 95: "35.227.69.60:8005", 100: "35.231.121.54:8005", 105: "34.74.238.143:8005"} len: 8
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: solana_runtime::accounts_background_service::SnapshotRequestHandler::handle_snapshot_requests
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-02-06T05:26:32.324027988Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-accounts-background" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `1000189065363148006`,
     right: `1000189065482728910`', runtime/src/bank.rs:4334:9" location="runtime/src/bank.rs:4334:9"
..
[2021-02-06T05:52:03.238434294Z INFO  solana_runtime::bank] bank frozen: 202200 hash: HshPoKPGe6sQ7XmsoqCQsV8JyF8zRNGJ6grfzDL1Fsv5 accounts_delta: 86tkc5jAWzBfB7hwp1bURTyqytJTHVQJFBN2TRRDM6Q9 signature_count: 1334 last_blockhash: F5DzPrjt2ozXEX3DbdniEziudZs4tAgtWpp5xC8uTA6L capitalization: 1000189065482728910
[2021-02-06T05:52:03.238465344Z INFO  solana_runtime::bank] accounts hash slot: 202200 stats: BankHashStats { num_updated_accounts: 1527, num_removed_accounts: 0, num_lamports_stored: 222095528255484, total_data_len: 395490, num_executable_accounts: 0 }
```

**Comment by jeffwashington** [comment]
status: tyera is restarting simulation. Added verification of hash and lamports calculation, improved assert message, added a few checks.
Separately, have ledger on colo machine. Generating snapshot at slot 200k almost complete.
@CriesofCarrots is changing the # of snapshots retained to much more than 2. I measured the slot 180k snapshot at 5g.

**Comment by CriesofCarrots** [comment]
This is the branch running on the new simulation cluster: https://github.com/CriesofCarrots/solana/tree/v1.5-kinsim-20210210

**Comment by jeffwashington** [comment]
I gathered snapshots up to slot 200k. I ran the ledger tool to verify. Both the above slots match the bank's capitalization.
```200888 hash: Hm2bv45q7MGiQnhBUJy3BuJkZE4fY7NrLLjYNnry3fJK accounts_delta: EemCqjfL6NoigmTtU9ULsBev81EWiHP4cgwxarC8xTcy signature_count: 653 last_blockhash: 5xaTtZLrKRBFuqZecWtnrhBVe59B91P1B3VRrpzpYJ9W capitalization: 1000189067148716410
matches bank.cap
202200 hash: HshPoKPGe6sQ7XmsoqCQsV8JyF8zRNGJ6grfzDL1Fsv5 accounts_delta: 86tkc5jAWzBfB7hwp1bURTyqytJTHVQJFBN2TRRDM6Q9 signature_count: 1334 last_blockhash: F5DzPrjt2ozXEX3DbdniEziudZs4tAgtWpp5xC8uTA6L capitalization: 1000189065482728910
matches bank.cap
https://github.com/solana-labs/solana/issues/15180```

**Comment by jeffwashington** [comment]
@sakridge suggests re-adding the hashing of append-vecs to check for store corruption that @carllin is guessing may be the problem.

**Comment by jeffwashington** [comment]
This was fixed. I think it was an account index or cache race condition? @carllin @ryoqun. I think this was the pr that took a few weeks between carl and ryo.
