### ISSUE TITLE
thread 'bigtable-upload' panicked at 'there is no timer running, must be called from the context of Tokio runtime'

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#15924]
`tw`, running 1.6.0 is periodically panicking with:
```
[2021-03-16T16:06:50.572174628Z INFO  solana_ledger::bigtable_upload] Found 3 slots in the range (68148129, 68148131)
[2021-03-16T16:06:50.572201166Z INFO  solana_ledger::bigtable_upload] Loading list of bigtable blocks between slots 68148129 and 68148131...
[2021-03-16T16:06:50.577473068Z ERROR solana_ledger::bigtable_upload] get_confirmed_blocks for 68148130 failed: BigTableError(RpcError(Status { code: Unknown, message: "transport error: operation was canceled: connection closed" }))
thread 'bigtable-upload' panicked at 'there is no timer running, must be called from the context of Tokio runtime', /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.5/src/time/driver/handle.rs:50:18
stack backtrace:
[2021-03-16T16:06:50.593571643Z INFO  solana_metrics::metrics] datapoint: shred_insert_is_full total_time_ms=720i slot=68148290i last_index=541i
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   3: tokio::time::driver::sleep::Sleep::new_timeout
   4: tokio::time::driver::sleep::sleep
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: tokio::runtime::enter::Enter::block_on
   8: tokio::runtime::thread_pool::ThreadPool::block_on
   9: tokio::runtime::Runtime::block_on
  10: solana_core::bigtable_upload_service::BigTableUploadService::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-03-16T16:06:50.625219971Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="bigtable-upload" one=1i message="panicked at 'there is no timer running, must be called from the context of Tokio runtime', /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.5/src/time/driver/handle.rs:50:18" location="/var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.5/src/time/driver/handle.rs:50:18"
[2021-03-16T16:06:50.625388097Z INFO  solana_metrics::metrics] submitting 304 points
```
This has not been observed on v1.5

**Comment by CriesofCarrots** [comment]
Hmm, `tokio-0.3.5`... Bumping ledger's tokio dependency to v1.1 would be a good first step

**Comment by mvines** [comment]
I think we blow up here: https://github.com/solana-labs/solana/blob/170cb792ebfa5e4ba1c3ec8c69f08ab684cad7ea/ledger/src/bigtable_upload.rs#L84

**Comment by mvines** [comment]
tokio mismatch most likely.  Do you want this @CriesofCarrots?

**Comment by CriesofCarrots** [comment]
> tokio mismatch most likely. Do you want this @CriesofCarrots?

Yep, I'll take. Confirming locally now.
