### ISSUE TITLE
Out-of-bounds error in retransmit

### ISSUE THREAD

**Issue by vkomenda** [solana-labs/solana#16302]
#### Problem

Out-of-bounds error in solana-retransmitter in 1.6.2.

```
thread 'solana-retransmitter' panicked at 'insertion index (is 4) should be <= len (is 0)', library/alloc/src/vec.rs:1217:13
thread 'solana-retransmitter' panicked at 'insertion index (is 4) should be <= len (is 0)', library/alloc/src/vec.rs:1217:13
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::insert::assert_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:1217:13
   3: solana_streamer::sendmmsg::mmsghdr_for_packet
   4: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   5: solana_streamer::sendmmsg::multicast
   6: solana_core::cluster_info::ClusterInfo::retransmit_to
   7: solana_core::retransmit_stage::retransmit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
[2021-04-01T13:37:24.624989942Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-retransmitter" one=1i message="panicked at 'insertion index (is 4) should be <= len (is 0)', library/alloc/src/vec.rs:1217:13" location="library/alloc/src/vec.rs:1217:13"
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1[2021-04-01T13:37:24.625053617Z INFO  solana_metrics::metrics] submitting 391 points
: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::insert::assert_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:1217:13
   3: solana_streamer::sendmmsg::mmsghdr_for_packet
   4: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   5: solana_streamer::sendmmsg::multicast
   6: solana_core::cluster_info::ClusterInfo::retransmit_to
   7: solana_core::retransmit_stage::retransmit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::insert::assert_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:1217:13
   3: solana_streamer::sendmmsg::mmsghdr_for_packet
   4: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   5: solana_streamer::sendmmsg::multicast
   6: solana_core::cluster_info::ClusterInfo::retransmit_to
   7: solana_core::retransmit_stage::retransmit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'solana-retransmitter' panicked at 'insertion index (is 3) should be <= len (is 0)', library/alloc/src/vec.rs:1217:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::insert::assert_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:1217:13
   3: solana_streamer::sendmmsg::mmsghdr_for_packet
   4: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   5: solana_streamer::sendmmsg::multicast
   6: solana_core::cluster_info::ClusterInfo::retransmit_to
   7: solana_core::retransmit_stage::retransmit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'solana-retransmitter' panicked at 'insertion index (is 3) should be <= len (is 0)', library/alloc/src/vec.rs:1217:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::insert::assert_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:1217:13
   3: solana_streamer::sendmmsg::mmsghdr_for_packet
   4: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   5: solana_streamer::sendmmsg::multicast
   6: solana_core::cluster_info::ClusterInfo::retransmit_to
   7: solana_core::retransmit_stage::retransmit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'solana-retransmitter' panicked at 'insertion index (is 3) should be <= len (is 0)', library/alloc/src/vec.rs:1217:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::insert::assert_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:1217:13
   3: solana_streamer::sendmmsg::mmsghdr_for_packet
   4: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   5: solana_streamer::sendmmsg::multicast
   6: solana_core::cluster_info::ClusterInfo::retransmit_to
   7: solana_core::retransmit_stage::retransmit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-04-01T13:37:24.682262472Z INFO  solana_core::replay_stage] new fork:70372564 parent:70372547 root:70369346
[2021-04-01T13:37:24.714228143Z INFO  solana_runtime::accounts_db] req_flush_root: Some(70369346) old_slot_flushes: []
thread 'solana-retransmitter' panicked at 'insertion index (is 4) should be <= len (is 0)', library/alloc/src/vec.rs:1217:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::insert::assert_failed
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/vec.rs:1217:13
   3: solana_streamer::sendmmsg::mmsghdr_for_packet
   4: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
   5: solana_streamer::sendmmsg::multicast
   6: solana_core::cluster_info::ClusterInfo::retransmit_to
   7: solana_core::retransmit_stage::retransmit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

#### Proposed Solution

TODO

**Comment by sakridge** [comment]
@behzadnouri can you take a look?
