### ISSUE TITLE
core::test_rpc_subscriptions and core::test_rpc_slot_updates are flaky

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#16970]
#### Problem

The following two commands eventually fail. My estimate is that the tests fail less than 1 in 10 iterations.

```
(export RUST_LOG=INFO; set -e; while true; do cargo test --package solana-core --release --test rpc test_rpc_subscriptions; done)
(export RUST_LOG=INFO; set -e; while true; do cargo test --package solana-core --release --test rpc test_rpc_slot_updates; done)
```

It produces the following errors

```
---- test_rpc_subscriptions stdout ----
thread 'test_rpc_subscriptions' panicked at 'recv_timeout, 569/1000 signatures remaining', core/tests/rpc.rs:354:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
(also observed with different values than 569)

```
---- test_rpc_slot_updates stdout ----
thread 'test_rpc_slot_updates' panicked at 'assertion failed: `(left == right)`
  left: `"Frozen"`,
 right: `"Completed"`', core/tests/rpc.rs:206:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', core/tests/rpc.rs:171:55
```

#### Proposed Solution

I don’t know enough about what these tests do to propose a solution here.

**Comment by xiangzhu70** [comment]
Starting to work on it.  The debug note doc is https://docs.google.com/document/d/17kJ122_wZbEA8SWqke6tUAyKTksAnYYGSubV-ytn2rw/edit?usp=sharing

**Comment by xiangzhu70** [comment]
Increased the timeout with https://github.com/solana-labs/solana/pull/27008

**Comment by yihau** [comment]
core::test_rpc_slot_updates #26593
core::test_rpc_subscriptions #27394
