### ISSUE TITLE
Snapshot incomplete frame

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#17134]
#### Problem
While running a validator on lemond on master, encountered the panic:

```
thread 'main' panicked at 'Load from snapshot failed: UnpackError(Io(Custom { kind: UnexpectedEof, error: "incomplete frame" }))', ledger/src/bank_forks_utils.rs:74:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/option.rs:1329:5
   3: solana_ledger::bank_forks_utils::load
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-05-09T21:59:28.845653902Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Load from snapshot failed: UnpackError(Io(Custom { kind: UnexpectedEof, error: \"incomplete frame\" }))', ledger/src/bank_forks_utils.rs:74:18" location="ledger/src/bank_forks_utils.rs:74:18"
```
Logs/ledger/snapshot are all under /home/carl/solana/DebugConsensus/mb/snapshot_fail_verify on lemond

**Comment by ryoqun** [comment]
@carllin hmm, this looks like broken snapshot archive? For comparison, can you successfully unpack the snapshot? 3e0fed48e7751f342ebd72b6a05e22ea1829ab81 #17057

**Comment by carllin** [comment]
Heh yeah I think its the same issue:

```
[2021-05-09T21:59:19.075769101Z WARN  solana_validator] Snapshot couldn't be downloaded
```
