### ISSUE TITLE
thread 'solana-replay-stage' panicked at 'candidate_latest_frozen_vote is a frozen bank, so must exist in ancestors map'

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#17377]
The `bvb` node running:
```
solana-validator 1.7.0 (src:e320af99; feat:3533521759)
```
just panicked with:
```
thread 'solana-replay-stage' panicked at 'candidate_latest_frozen_vote is a frozen bank, so must exist in ancestors map', core/src/consensus.rs:781:26
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at ./rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1321:5
   3: solana_core::consensus::Tower::check_switch_threshold
   4: solana_core::replay_stage::ReplayStage::select_vote_and_reset_forks
   5: solana_core::replay_stage::ReplayStage::new::{{closure}}
```

This may be a new regression on master.  I just updated it to a new master build a couple hours prior.  Previously it was running b5302e76198b951e7d4f96fbf5f17e273f209dcd for I didn't observe this panic

**Comment by mvines** [comment]
Full log is at `~/issue-17377.log` on `bvb`, crash starts on line 18049221
