### ISSUE TITLE
Load from snapshot failed # Cannot allocate memory

### ISSUE THREAD

**Issue by wuzhenlin135** [solana-labs/solana#17608]
#### Problem

[2021-05-31T03:47:02.523772635Z INFO  solana_core::validator] loading ledger from "/sol/ledger"...
[2021-05-31T03:47:02.525035046Z INFO  solana_core::validator] genesis hash: 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d[2021-05-31T03:47:02.525061606Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 700000
[2021-05-31T03:47:02.525065011Z INFO  solana_ledger::blockstore] Opening database at "/sol/ledger/rocksdb"
[2021-05-31T03:47:02.628961532Z INFO  solana_ledger::blockstore] "/sol/ledger/rocksdb" open took 103ms
[2021-05-31T03:47:02.629702856Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "/sol/ledger/snapshot"
[2021-05-31T03:47:02.630387639Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "/sol/ledger/snapshot-80737400-2BZ1MzwapYW4nZCs3Txvg2taepTUR7yFsP5usiteScna.tar.zst"
[2021-05-31T03:47:12.630504717Z INFO  solana_runtime::hardened_unpack] unpacked 98356 entries so far...
[2021-05-31T03:47:22.630512360Z INFO  solana_runtime::hardened_unpack] unpacked 203280 entries so far...
[2021-05-31T03:47:32.756155228Z INFO  solana_runtime::hardened_unpack] unpacked 290869 entries so far...
[2021-05-31T03:47:42.756231499Z INFO  solana_runtime::hardened_unpack] unpacked 382262 entries so far...
[2021-05-31T03:47:48.476271993Z INFO  solana_runtime::hardened_unpack] unpacked 431885 entries total
[2021-05-31T03:47:48.476454464Z INFO  solana_runtime::snapshot_utils] snapshot untar took 45.8s
[2021-05-31T03:47:48.476489681Z INFO  solana_runtime::snapshot_utils] snapshot version: 1.2.0
[2021-05-31T03:47:48.476531021Z INFO  solana_runtime::snapshot_utils] Loading bank from /sol/ledger/snapshot/tmp-snapshot-UzzUMU/snapshots/80737400/80737400
thread 'main' panicked at 'Load from snapshot failed: Serialize(Io(Os { code: 12, kind: Other, message: "Cannot allocate memory" }))', ledger/src/bank_forks_utils.rs:75:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: solana_ledger::bank_forks_utils::load
   4: solana_core::validator::new_banks_from_ledger
   5: solana_core::validator::Validator::new
   6: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-05-31T03:47:57.630933738Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Load from snapshot failed: Serialize(Io(Os { code: 12, kind: Other, message: \"Cannot allocate memory\" }))', ledger/src/bank_forks_utils.rs:75:18" location="ledger/src/bank_forks_utils.rs:75:18"
[2021-05-31T03:47:57.630964647Z INFO  solana_metrics::metrics] submitting 2 points
[2021-05-31T03:47:59.660733932Z INFO  solana_validator] solana-validator 1.6.10 (src:5d4654d2; feat:3533521759)

**Comment by wuzhenlin135** [comment]
#11002 same problem

**Comment by houlei1017** [comment]
I got the same problem

**Comment by t-nelson** [comment]
The PR @wuzhenlin135 references has the solution.  A more permanent instantiation is available [in the docs](https://docs.solana.com/running-validator/validator-start#increased-memory-mapped-files-limit)
