### ISSUE TITLE
Capitalization panic in mainnet validator

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#17740]
#### Problem

Pete | LunaNova reported an assert:
https://discord.com/channels/428295358100013066/689412830075551748/850254944241582080

```
we've just had a backup validator fall over and restart with the following in the logs:
Jun 04 06:58:16 solana-validator[95555]: thread 'solana-accounts-background' panicked at 'assertion failed: `(left == right)`
Jun 04 06:58:16 solana-validator[95555]:   left: `496829790352427966`,
Jun 04 06:58:16 solana-validator[95555]:  right: `496829790352427958`', runtime/src/bank.rs:4407:9
Jun 04 06:58:16 solana-validator[95555]: stack backtrace:
Jun 04 06:58:16 solana-validator[95555]:    0: rust_begin_unwind
Jun 04 06:58:16 solana-validator[95555]:              at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
Jun 04 06:58:16 solana-validator[95555]:    1: core::panicking::panic_fmt
Jun 04 06:58:16 solana-validator[95555]:              at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
Jun 04 06:58:16 solana-validator[95555]:    2: solana_runtime::accounts_background_service::SnapshotRequestHandler::handle_snapshot_requests
Jun 04 06:58:16 solana-validator[95555]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jun 04 06:58:16 solana-validator[95555]: [2021-06-04T05:58:16.275393260Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-accounts-background" one=1i message="panicked at 'assertion failed: `(left == righ
Jun 04 06:58:16 solana-validator[95555]:       left: `496829790352427966`,
Jun 04 06:58:16 solana-validator[95555]:      right: `496829790352427958`', runtime/src/bank.rs:4407:9" location="runtime/src/bank.rs:4407:9"
```

#### Proposed Solution

Debug and fix.

**Comment by sakridge** [comment]
cc @jeffwashington

**Comment by sakridge** [comment]
[9CqDvvGvSNVZDo5RskCAv4fTubpFCs9RLTrjUxEYrvNA-24hoursPreCrash-20210604.log.tar.gz](https://github.com/solana-labs/solana/files/6598551/9CqDvvGvSNVZDo5RskCAv4fTubpFCs9RLTrjUxEYrvNA-24hoursPreCrash-20210604.log.tar.gz)

**Comment by jeffwashington** [comment]
assert_eq!(total_lamports, self.capitalization());
```
total_lamports:        496829790352427966
self.capitalization(): 496829790352427958
```
difference of 8

**Comment by t-nelson** [comment]
:sun_with_face: :gun:

**Comment by jeffwashington** [comment]
> hehe, it's one of our older threadripper based systems without ECC RAM so could well be

**Comment by jeffwashington** [comment]
I think the plan is to wait to see if others encounter this. I will add a data point.

**Comment by behzadnouri** [comment]
more instances on v1.9.18 on Mainnet:
https://discord.com/channels/428295358100013066/689412830075551748/971504476554932235

> Has anyone seen panics due to capitalization_mismatch on 1.9.18 on Mainnet? Here's what I saw in my logs: 
> 
> thread 'solana-bg-accounts' panicked at 'capitalization_mismatch. slot: 132430005, calculated_lamports: 520765542482772675, capitalization: 520765542480733395', runtime/src/bank.rs:5956:13
