### ISSUE TITLE
solana-validator 1.7.6 crash

### ISSUE THREAD

**Issue by depool-live** [solana-labs/solana#18844]
#### Problem
solana-validator 1.7.6 crash crash after start
[2021-07-22T18:52:28.679377866Z WARN  solana_ledger::blockstore_processor] TooFewTicks, slot: 0, entry len: 0, tick_height: 0, last entry: 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY, last_blockhash: 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY, shred_index: 3, slot_full: true
thread 'main' panicked at 'processing for bank 0 must succeed: InvalidBlock(TooFewTicks)', ledger/src/blockstore_processor.rs:866:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
   3: solana_ledger::blockstore_processor::process_blockstore
   4: solana_ledger::bank_forks_utils::load
   5: solana_core::validator::Validator::new
   6: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-07-22T18:52:28.688509034Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'processing for bank 0 must succeed: InvalidBlock(TooFewTicks)', ledger/src/blockstore_processor.rs:866:6" location="ledger/src/blockstore_processor.rs:866:6"

solana-validator 1.7.6 (src:devbuild; feat:1047961907)
Linux ubuntu 5.13.4-051304-generic #202107220826-Ubuntu SMP Thu Jul 22 08:33:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by depool-live** [comment]
#### Proposed Solution

remove flag
--no-snapshot-fetch
