### ISSUE TITLE
solana-validator 1.7.6 crash

### ISSUE THREAD

**Issue by depool-live** [solana-labs/solana#18884]
#### Problem
Crash on startup, after fill the RAM (~47Gb now)

[2021-07-25T12:56:02.817074204Z INFO  solana_metrics::metrics] datapoint: gossip errors=5i
[2021-07-25T12:56:02.817075807Z INFO  solana_streamer::streamer] gossip last-error: Some(Io(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })) count: 5
[2021-07-25T12:56:02.819107814Z INFO  solana_metrics::counter] COUNTER:{"name": "cluster_info-purge-no_working_bank", "counts": 83001, "samples": 83000,  "now": 1627217762819, "events": 1}
[2021-07-25T12:56:03.819778022Z INFO  solana_metrics::metrics] datapoint: gossip errors=6i
[2021-07-25T12:56:03.819774516Z INFO  solana_streamer::streamer] gossip last-error: Some(Io(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })) count: 6
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1584368940`,
 right: `1580834132`', runtime/src/bank.rs:1405:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
   4: solana_runtime::bank::Bank::new_from_fields
   5: solana_runtime::serde_snapshot::bank_from_stream
   6: solana_runtime::snapshot_utils::rebuild_bank_from_snapshots
   7: solana_runtime::snapshot_utils::bank_from_archive
   8: solana_ledger::bank_forks_utils::load
   9: solana_core::validator::new_banks_from_ledger
  10: solana_core::validator::Validator::new
  11: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-07-25T12:56:04.164207492Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `1584368940`,
     right: `1580834132`', runtime/src/bank.rs:1405:9" location="runtime/src/bank.rs:1405:9"
[2021-07-25T12:56:04.164451855Z INFO  solana_metrics::metrics] submitting 79 points
[2021-07-25T12:56:04.880605946Z INFO  solana_metrics::metrics] datapoint: cluster_info_stats entrypoint=0i entrypoint2=0i push_vote_read=0i get_votes=0i get_accounts_hash=0i all_tvu_peers=0i tvu_peers=0i new_push_requests_num=894i table_size=787756i purged_values_size=207514i failed_inserts_size=19112i num_nodes=2405i num_nodes_staked=0i
[2021-07-25T12:56:04.880622407Z INFO  solana_metrics::metrics] datapoint: cluster_info_stats2 gossip_packets_dropped_count=0i repair_peers=0i new_push_requests=8687i new_push_requests2=20i purge=13336i process_gossip_packets_time=188221i verify_gossip_packets_time=152573i handle_batch_ping_messages_time=3070i handle_batch_pong_messages_time=72i handle_batch_prune_messages_time=1673i handle_batch_pull_requests_time=0i handle_batch_pull_responses_time=94128i handle_batch_push_messages_time=80244i process_pull_resp=27701i filter_pull_resp=10614i process_pull_resp_count=24i pull_response_fail_insert=1412i pull_response_fail_timeout=0i pull_response_success=3076i process_pull_resp_timeout=0i push_response_count=0i
[2021-07-25T12:56:04.880628909Z INFO  solana_metrics::metrics] datapoint: cluster_info_stats3 process_pull_resp_len=4488i process_pull_requests=0i pull_request_ping_pong_check_failed_count=0i new_pull_requests_pings_count=10i generate_pull_responses=0i process_prune=541i process_push_message=4743i prune_received_cache=50i epoch_slots_lookup=0i new_pull_requests=395391i mark_pull_request=0i
[2021-07-25T12:56:04.880633077Z INFO  solana_metrics::metrics] datapoint: cluster_info_stats4 skip_push_message_shred_version=0i skip_pull_response_shred_version=394i skip_pull_shred_version=0i push_message_count=391i push_message_value_count=682i new_pull_requests_count=7168i pull_from_entrypoint_count=0i prune_message_count=643i prune_message_len=6769i
[2021-07-25T12:56:04.880636624Z INFO  solana_metrics::metrics] datapoint: cluster_info_stats5 pull_requests_count=0i packets_received_count=7334i packets_received_prune_messages_count=643i packets_received_pull_requests_count=0i packets_received_pull_responses_count=4488i packets_received_push_messages_count=391i packets_received_verified_count=7334i packets_sent_gossip_requests_count=8072i packets_sent_prune_messages_count=0i packets_sent_pull_requests_count=7168i packets_sent_pull_responses_count=0i packets_sent_push_messages_count=894i require_stake_for_gossip_unknown_feature_set=376i require_stake_for_gossip_unknown_stakes=0i trim_crds_table=0i trim_crds_table_failed=0i trim_crds_table_purged_values_count=0i

Linux ubuntu 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
solana-validator 1.7.6 (src:3542348c; feat:1047961907)

**Comment by depool-live** [comment]
Proposed Solution

use right snapshot
