### ISSUE TITLE
Can't start node

### ISSUE THREAD

**Issue by simplewhale** [solana-labs/solana#19575]
#### Problem
![image](https://user-images.githubusercontent.com/36060515/131817934-d8eb0473-81ed-4c4c-9fb1-d75e15a17a4f.png)

**Comment by zhangyanhuivv** [comment]
same issue

**Comment by zhangyanhuivv** [comment]
solana-validator version: Mainnet - v1.6.22

solana-validator \
--ledger /data1/sol/validator-ledger \
--entrypoint entrypoint.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
--trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
--trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
--trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
--trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
--expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
--rpc-port 8899 \
--no-voting \
--enable-rpc-transaction-history \
--limit-ledger-size \
--no-untrusted-rpc \
--identity /data1/sol/wallet/id.json \
--log /data1/sol/log/solana-validator.log \
--private-rpc \
--dynamic-port-range 8000-8010

[2021-09-02T10:55:02.180935554Z INFO  solana_download_utils]   Downloaded http://145.40.67.83:80/snapshot-94536840-CMfTitawnJBTB7bZtp4Aey9UNNKuyn82HkhdGonGperu.tar.zst (9049055650 bytes) in 435.639795332s
[2021-09-02T10:55:02.209700378Z WARN  solana_core::validator] identity: CEwAv9fdKgMBsfJnktGe5X8RL4YtGBgH5mkMGMSa9u7x
[2021-09-02T10:55:02.209730770Z WARN  solana_core::validator] vote account: 3vGybYb2qH8SHsYmPpVtEVF69yXEs8J2VNw7T5t1UCu8
[2021-09-02T10:55:02.209738222Z WARN  solana_core::validator] voting disabled
[2021-09-02T10:55:02.209742774Z WARN  solana_core::validator] CUDA is disabled
[2021-09-02T10:55:02.209746886Z INFO  solana_core::validator] AVX detected
[2021-09-02T10:55:02.209749954Z INFO  solana_core::validator] entrypoint: ContactInfo { id: 11111111111111111111111111111111, gossip: 145.40.93.177:8001, tvu: 0.0.0.0:0, tvu_forwards: 0.0.0.0:0, repair: 0.0.0.0:0, tpu: 0.0.0.0:0, tpu_forwards: 0.0.0.0:0, unused: 0.0.0.0:0, rpc: 0.0.0.0:0, rpc_pubsub: 0.0.0.0:0, serve_repair: 0.0.0.0:0, wallclock: 1630579633726, shred_version: 0 }
[2021-09-02T10:55:02.209767521Z INFO  solana_core::validator] entrypoint: ContactInfo { id: 11111111111111111111111111111111, gossip: 147.75.38.117:8001, tvu: 0.0.0.0:0, tvu_forwards: 0.0.0.0:0, repair: 0.0.0.0:0, tpu: 0.0.0.0:0, tpu_forwards: 0.0.0.0:0, unused: 0.0.0.0:0, rpc: 0.0.0.0:0, rpc_pubsub: 0.0.0.0:0, serve_repair: 0.0.0.0:0, wallclock: 1630579633726, shred_version: 0 }
[2021-09-02T10:55:02.209779061Z INFO  solana_core::validator] entrypoint: ContactInfo { id: 11111111111111111111111111111111, gossip: 34.83.231.102:8001, tvu: 0.0.0.0:0, tvu_forwards: 0.0.0.0:0, repair: 0.0.0.0:0, tpu: 0.0.0.0:0, tpu_forwards: 0.0.0.0:0, unused: 0.0.0.0:0, rpc: 0.0.0.0:0, rpc_pubsub: 0.0.0.0:0, serve_repair: 0.0.0.0:0, wallclock: 1630579633726, shred_version: 0 }
[2021-09-02T10:55:02.209790329Z INFO  solana_core::validator] entrypoint: ContactInfo { id: 11111111111111111111111111111111, gossip: 145.40.67.83:8001, tvu: 0.0.0.0:0, tvu_forwards: 0.0.0.0:0, repair: 0.0.0.0:0, tpu: 0.0.0.0:0, tpu_forwards: 0.0.0.0:0, unused: 0.0.0.0:0, rpc: 0.0.0.0:0, rpc_pubsub: 0.0.0.0:0, serve_repair: 0.0.0.0:0, wallclock: 1630579633726, shred_version: 0 }
[2021-09-02T10:55:02.209801165Z INFO  solana_core::validator] entrypoint: ContactInfo { id: 11111111111111111111111111111111, gossip: 86.109.15.59:8001, tvu: 0.0.0.0:0, tvu_forwards: 0.0.0.0:0, repair: 0.0.0.0:0, tpu: 0.0.0.0:0, tpu_forwards: 0.0.0.0:0, unused: 0.0.0.0:0, rpc: 0.0.0.0:0, rpc_pubsub: 0.0.0.0:0, serve_repair: 0.0.0.0:0, wallclock: 1630579633726, shred_version: 0 }
[2021-09-02T10:55:02.209812503Z INFO  solana_core::validator] Initializing sigverify...
[2021-09-02T10:55:02.209816374Z INFO  solana_core::validator] Done.
[2021-09-02T10:55:02.209827312Z INFO  solana_core::validator] Cleaning accounts paths..
[2021-09-02T10:55:02.209900359Z INFO  solana_core::validator] done. clean_accounts_paths took 68us
[2021-09-02T10:55:02.209912267Z INFO  solana_core::validator] loading ledger from "/data1/sol/validator-ledger"...
[2021-09-02T10:55:02.211273798Z INFO  solana_core::validator] genesis hash: 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d
[2021-09-02T10:55:02.211299063Z INFO  solana_ledger::poh] Running 800000 hashes...
[2021-09-02T10:55:02.586003200Z INFO  solana_core::validator] PoH speed check: Will sleep 25303148ns per slot.
[2021-09-02T10:55:02.586047607Z ERROR solana_ledger::blockstore] Unable to increase the maximum open file descriptor limit to 500000
thread 'main' panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: solana_core::validator::new_banks_from_ledger
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-09-02T10:55:02.601334859Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6" location="core/src/validator.rs:1080:6"

**Comment by onurplusplus** [comment]
- Did you set `LimitNOFILE` manually?
- Did you run `solana-sys-tuner` before starting the validator?

**Comment by simplewhale** [comment]
I use the./run.sh script to start the node. Where do I need to set these parameters?

**Comment by onurplusplus** [comment]
First, let's be sure about the installation steps those you followed. Can you share them step by step?
Also, you can add your logs as text for clear history and the community, especially who searches the same issue here.

I didn't use the `run` script and don't know its history, I follow the instructions in [Install the Solana Tool Suite](https://docs.solana.com/cli/install-solana-cli-tools), [Add Solana to Your Exchange](https://docs.solana.com/integrations/exchange#node-setup) and [Starting a Validator](https://docs.solana.com/running-validator/validator-start#automatic). You can give a shot if there is no other answer.

The issue that you faced looks about lower value for `LimitNOFILE` property, `ulimit` generally.
If you completed the pre-steps successfully, you can try to append this assignment in `./run.sh` script after the following line `export RUST_BACKTRACE=1`. I'm not sure about the implementation in sh file with or without `export`.
```
...
export RUST_BACKTRACE=1
export LimitNOFILE=1000000
...
```

**Comment by simplewhale** [comment]
I'm using the compiled source code here, following step 4 to launch the./run.sh script.

https://github.com/solana-labs/solana. The./run.sh script is as follows:

![image](https://user-images.githubusercontent.com/36060515/131972789-ac22cca2-d72c-48e1-b57a-f96b13566309.png)

The same mistakes were made again

**Comment by onurplusplus** [comment]
I'm not sure about the implementation in shell script as I said. Could you try those steps in [here](https://docs.solana.com/running-validator/validator-start#system-tuning)? If you prefer to do it manually, could you try [this one](https://docs.solana.com/running-validator/validator-start#manual)?

**Comment by simplewhale** [comment]
Okay, I'll go through all the steps you sent me, and then use

"Solana - the validator \

--ledger /root/sol/solana/config/ledger \

--identity /root/sol/solana/config/run/validator-identity.json \

--entrypoint entrypoint.mainnet-beta.solana.com:8001 \

--entrypoint entrypoint2.mainnet-beta.solana.com:8001 \

--entrypoint entrypoint3.mainnet-beta.solana.com:8001 \

--entrypoint entrypoint4.mainnet-beta.solana.com:8001 \

--entrypoint entrypoint5.mainnet-beta.solana.com:8001 \

--expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \

--rpc-port 8899 \

--no-voting \

--enable-rpc-transaction-history \

--limit-ledger-size \--known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \

--known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \

--known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \

--known-validator --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \

---only-known-rpc"


To start. A new problem has arisen.


[2021-09-03:21:55.848726485z ERROR solana_net_utils] Received no response at TCP /8899, check your port configuration: timed out waiting on channel

[2021-09-03T09:22:00.849107110z ERROR solana_net_utils] Received no response at TCP /8900, check your port configuration: timed out waiting on channel

[2021-09-03T09:22:05.849494572z ERROR solana_net_utils] Received no response at TCP /8000, check your port configuration: timed out waiting on channel

[2021-09-030T09:22:05.849796973z INFO solana_net_utils] Checking that TCP ports [(8899, TcpListener {addr: 0.0.0.0:8899, fd: 85}), (8900, TcpListener {addr: 0.0.0.0:8900, fd: 86}), (8000, TcpListener {addr: 0.0.0.0:8000, fd: 87})] are reachable from 145.40.93.177:8001

[2021-09-03:22:16.368019603z ERROR solana_net_utils] Received no response at TCP /8899, check your port configuration: timed out waiting on channel

[2021-09-03T09:22:21.368413796z ERROR solana_net_utils] Received no response at TCP /8900, check your port configuration: timed out waiting on channel

[2021-09-03:22:26.368803174z ERROR solana_net_utils] Received no response at TCP /8000, check your port configuration: timed out waiting on channel


The other synchronization nodes are not connected correctly. Has the seed node been updated?

**Comment by onurplusplus** [comment]
You need to pass `--dynamic-port-range 8000-8100`  too.

**Comment by nyetwurk** [comment]
> export LimitNOFILE=1000000

That isn't even remotely how you set open file limits. It's done in systemd unit file or via rlimit.

**Comment by nyetwurk** [comment]
1) This ticket doesn't belong here, as there are explicit instructions for setting both sysctl and rlimits in the solana documentation
2) Description "Can't start node" is far too vague

**Comment by onurplusplus** [comment]
> > export LimitNOFILE=1000000
> 
> 
> 
> That isn't even remotely how you set open file limits. It's done in systemd unit file or via rlimit.

It was not a certain statement. That's why I specified "not being sure" and "setting hard & soft limits", also shared the official docs links with an ask for adding outputs as text/snippet.

**Comment by t-nelson** [comment]
> I use the./run.sh script to start the node. Where do I need to set these parameters?

I'd advise against using `run.sh` at all. [`solana-test-validator`](https://docs.solana.com/developing/test-validator) is superior in every way

**Comment by steviez** [comment]
> I'd advise against using `run.sh` at all. [`solana-test-validator`](https://docs.solana.com/developing/test-validator) is superior in every way

@t-nelson - Should we update the README to reflect this?
https://github.com/solana-labs/solana#4-run-a-minimal-local-cluster

**Comment by WilliamWhispell** [comment]
I ran into the same issue, first time trying to launch a validator. Using WSL (Ubuntu 20) on Windows. Tried running the sys tuner and see in the logs:

cat sys-tuner.log
[2021-09-06T01:20:59.586387100Z ERROR solana_sys_tuner] Failed to find sysctl net.core.rmem_max
[2021-09-06T01:20:59.586524800Z ERROR solana_sys_tuner] Failed to find sysctl net.core.rmem_default
[2021-09-06T01:20:59.586572700Z ERROR solana_sys_tuner] Failed to find sysctl net.core.wmem_max
[2021-09-06T01:20:59.586612600Z ERROR solana_sys_tuner] Failed to find sysctl net.core.wmem_default
[2021-09-06T01:20:59.586650400Z ERROR solana_sys_tuner] Failed to find sysctl vm.max_map_count

ulimit -Hn
65536

validator logs:
[2021-09-06T02:03:25.396883100Z INFO  solana_core::validator] genesis hash: 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d
[2021-09-06T02:03:25.396923400Z INFO  solana_ledger::poh] Running 800000 hashes...
[2021-09-06T02:03:25.736756000Z INFO  solana_core::validator] PoH speed check: Will sleep 60201200ns per slot.
[2021-09-06T02:03:25.736894400Z ERROR solana_ledger::blockstore] Unable to increase the maximum open file descriptor limit to 500000
thread 'main' panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: solana_core::validator::new_banks_from_ledger
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by GooSatoru** [comment]
Version:

solana-validator 1.6.22 (src:7956f04f; feat:3316993441)

Run:

export LimitNOFILE=1000000
export RUST_BACKTRACE=1

```
solana-validator \
  --ledger /data/solana \
  --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --rpc-port 8899 \
  --no-voting \
  --enable-rpc-transaction-history \
  --limit-ledger-size 100000000 \
  --trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --identity /home/ubuntu/validator-keypair.json \
  --snapshot-compression none \
  --no-port-check \
  --no-untrusted-rpc \
  --wal-recovery-mode skip_any_corrupted_record
```

Got:

```
[2021-09-06T02:23:57.230115768Z ERROR solana_ledger::blockstore] Unable to increase the maximum open file descriptor limit to 500000
thread 'main' panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: solana_core::validator::new_banks_from_ledger
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-09-06T02:23:57.345013846Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6" location="core/src/validator.rs:1080:6"

```

**Comment by WilliamWhispell** [comment]
I was able to get this working on WSL using steps in https://stackoverflow.com/questions/63960859/how-can-i-raise-the-limit-for-open-files-in-ubuntu-20-04-on-wsl2

I modified the soft and hard limits in /etc/security/limits.conf, /etc/systemd/system.conf and /etc/sysctl.conf to be above the 500,000 value solana-validator requires. Then I su into my username and can finally see the limit changes taking effect. This works with WSL 1 too.

**Comment by onurplusplus** [comment]
> export LimitNOFILE=1000000

@GooSatoru it works in systemd. I didn't say that confidently for that reason.
You should follow the suggestions of contributors, or should use `solana-sys-tuner` for that purpose. [It does tuning](https://docs.solana.com/running-validator/validator-start#system-tuning) for you.

**Comment by GooSatoru** [comment]
> > export LimitNOFILE=1000000
> 
> @GooSatoru it works in `systemd`. This parameter cannot be set like that. I didn't type that confidently for this reason.
> You should follow the suggestions of the contributors, or should use `solana-sys-tuner` for this purpose. [It tunes system](https://docs.solana.com/running-validator/validator-start#system-tuning) for you. You can also find the details of manual configuration in [the same part of docs](https://docs.solana.com/running-validator/validator-start#manual).
> 
> > solana-validator 
> > --ledger /data/solana 
> > --entrypoint entrypoint.mainnet-beta.solana.com:8001 
> > --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d 
> > --rpc-port 8899 
> > --no-voting 
> > --enable-rpc-transaction-history 
> > --limit-ledger-size 100000000 
> > --trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 
> > --identity /home/ubuntu/validator-keypair.json 
> > --snapshot-compression none 
> > --no-port-check 
> > --no-untrusted-rpc 
> > --wal-recovery-mode skip_any_corrupted_record
> 
> You should probably need to pass dynamic port range too, something like as follows:
> 
> ```
> solana-validator \
>     ...
>     --dynamic-port-range 8000-8100 \
>     ...
> ```

Go new error

```
[2021-09-07T15:20:12.056718314Z ERROR solana_ledger::blockstore] Unable to increase the maximum open file descriptor limit to 500000
thread 'main' panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: solana_core::validator::new_banks_from_ledger
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-09-07T15:20:12.186388941Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6" location="core/src/validator.rs:1080:6"
```

**Comment by t-nelson** [comment]
please don't necro post...

all support happens on https://solana.com/discord
