### ISSUE TITLE
thread 'main' panicked at 'gossip_addr bind_to port

### ISSUE THREAD

**Issue by ihmc3jn09hk** [solana-labs/solana#19811]
#### Problem
Solana-validator cannot start even in `Devnet`. The node is behind a firewall/NAT with ip `yyy.yyy.yyy.yyy`.  The `gossip-host` and `bind-host` are set to a reverse proxy with IP `xxx.xxx.xxx.xxx`. The `dynamic-port-range` for  TCP & UDP 8000-8010 are configured and opened. 
The connection between `xxx.xxx.xxx.xxx` and `yyy.yyy.yyy.yyy` is checked without any problem. I get following error. 

Seems #2199 does not work

```console
[2021-09-12T10:29:32.706456285Z INFO  solana_validator] solana-validator 1.7.11 (src:bdb77b0c; feat:1140394761)
[2021-09-12T10:29:32.706524217Z INFO  solana_validator] Starting validator with: ArgsOs {
        inner: [
            "solana-validator",
            "--identity",
            "/home/solana-auto/validator-key.json",
            "--vote-account",
            "/home/solana-auto/vote-account-key.json",
            "--known-validator",
            "dv1ZAGvdsz5hHLwWXsVnM94hWf1pjbKVau1QVkaMJ92",
            "--known-validator",
            "dv2eQHeP4RFrJZ6UeiZWoc3XTtmtZCUKxxCApCDcRNV",
            "--known-validator",
            "dv4ACNkpYPcE3aKmYDqZm9G5EB3J4MRoeE7WNDRBVJB",
            "--known-validator",
            "dv3qDFk1DTF36Z62bNvrCXe9sKATA6xvVy6A798xxAS",
            "--only-known-rpc",
            "--ledger",
            "ledger",
            "--rpc-port",
            "8899",
            "--dynamic-port-range",
            "8000-8010",
            "--entrypoint",
            "entrypoint.devnet.solana.com:8001",
            "--entrypoint",
            "entrypoint2.devnet.solana.com:8001",
            "--entrypoint",
            "entrypoint3.devnet.solana.com:8001",
            "--entrypoint",
            "entrypoint4.devnet.solana.com:8001",
            "--entrypoint",
            "entrypoint5.devnet.solana.com:8001",
            "--expected-genesis-hash",
            "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG",
            "--wal-recovery-mode",
            "skip_any_corrupted_record",
            "--limit-ledger-size",
            "--log",
            "/home/solana-auto/validator.log",
            "--bind-address",
            "xxx.xxx.xxx.xxx",           #Proxy IP
            "--gossip-host",
            "xxx.xxx.xxx.xxx",          #Proxy IP
            "--gossip-port",
            "8001",
        ],
    }
[2021-09-12T10:29:32.706758683Z WARN  solana_core::validator] CUDA is disabled
[2021-09-12T10:29:32.706779434Z INFO  solana_core::validator] AVX detected
[2021-09-12T10:29:32.706788681Z INFO  solana_core::validator] AVX2 detected
[2021-09-12T10:29:43.144270755Z INFO  solana_validator] obtained shred-version 23305 from 136.144.49.15:8001
thread 'main' panicked at 'gossip_addr bind_to port 8001: Cannot assign requested address (os error 99)', gossip/src/cluster_info.rs:2786:21
stack backtrace:
   0:     0x56100a612a40 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x56100a612a40 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56100a612a40 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56100a612a40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56100a638caf - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x56100a60a262 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x56100a6153d5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56100a6153d5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56100a6153d5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x56100a614e83 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x56100a6159dd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x56100a615577 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:     0x56100a612efc - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x56100a6154d9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x5610091d076b - std::panicking::begin_panic_fmt::h400b8e9dca200408
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:     0x5610098473ac - solana_gossip::cluster_info::Node::get_gossip_port::{{closure}}::hc59a033d052d6fa9
  16:     0x5610098472c7 - solana_gossip::cluster_info::Node::get_gossip_port::h8272a034da5f375d
  17:     0x561009847425 - solana_gossip::cluster_info::Node::new_with_external_ip::h37060c05e491c92f
  18:     0x56100921156a - solana_validator::main::hd92838c006440cd6
  19:     0x561009225113 - std::sys_common::backtrace::__rust_begin_short_backtrace::h28daf5b03540d6ba
  20:     0x561009225129 - std::rt::lang_start::{{closure}}::h9ca33b24b2bad4f8
  21:     0x56100a615eda - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  22:     0x56100a615eda - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  23:     0x56100a615eda - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  24:     0x56100a615eda - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  25:     0x56100a615eda - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  26:     0x561009216c42 - main
  27:     0x7fbe63d220b3 - __libc_start_main
  28:     0x5610091ed2ea - _start
  29:                0x0 - <unknown>
```

#### Proposed Solution
Donno what's happening.

**Comment by t-nelson** [comment]
Can you elaborate your proxy configuration?

Are the redacted IPs public/routable?

**Comment by ihmc3jn09hk** [comment]
> Can you elaborate your proxy configuration?
> 
> Are the redacted IPs public/routable?

Hello @t-nelson ,
The validator machine sits behind a firewall which opened a dedicated port for validator machine only. 
The sol-validator requires 11 dynamic ports, 8899 and 8900, I use a VPS instance with public IP `xxx.xxx.xxx.xxx` with the ports 8899,8900 and 8000-10000 (both TCP and UDP) opened. 
A proxy is configed on the instance with a tunnel connection to the validator-machine. It forwards/routes all the connections from these ports to the validator machine and remap the identical ports to the `localhost`or `127.0.0.1` == `yyy.yyy.yyy.yyy`.
My guess the problem is here. Since `solana-validator` uses either the `bind-address` or `gossip-host` which I have to set to the public IP `xxx.xxx.xxx.xxx` while it should listen to `yyy.yyy.yyy.yyy`, the address binding failed. If I set the proxy maps to `xxx.xxx.xxx.xxx` , it is a dead loop for itself.
Does this guess right ? If so,
Is there a way to adjust the listening address to `yyy.yyy.yyy.yyy` ?
