### ISSUE TITLE
Error while starting Solana

### ISSUE THREAD

**Issue by Along-WG** [solana-labs/solana#19867]
#### Problem
[2021-09-14T12:38:35.463100007Z INFO  solana_runtime::hardened_unpack] unpacked 382064 entries so far...
thread 'main' panicked at 'Load from snapshot failed: UnpackError(Io(Custom { kind: UnexpectedEof, error: TarError { desc: "failed to unpack `/data/validator-ledger/accounts/accounts/96388153.1147562190`", io: Custom { kind: UnexpectedEof, error: TarError { desc: "failed to unpack `accounts/96388153.1147562190` into `/data/validator-ledger/accounts/accounts/96388153.1147562190`", io: Custom { kind: UnexpectedEof, error: "incomplete frame" } } } } }))', ledger/src/bank_forks_utils.rs:74:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: solana_ledger::bank_forks_utils::load
   4: solana_core::validator::new_banks_from_ledger
   5: solana_core::validator::Validator::new
   6: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-09-14T12:38:37.887838790Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Load from snapshot failed: UnpackError(Io(Custom { kind: UnexpectedEof, error: TarError { desc: \"failed to unpack `/data/validator-ledger/accounts/accounts/96388153.1147562190`\", io: Custom { kind: UnexpectedEof, error: TarError { desc: \"failed to unpack `accounts/96388153.1147562190` into `/data/validator-ledger/accounts/accounts/96388153.1147562190`\", io: Custom { kind: UnexpectedEof, error: \"incomplete frame\" } } } } }))', ledger/src/bank_forks_utils.rs:74:18" location="ledger/src/bank_forks_utils.rs:74:18"
[2021-09-14T12:38:37.887872719Z INFO  solana_metrics::metrics] submitting 2 points

**Comment by ffakira** [comment]
Currently the mainnet-beta cluster is down, you should try to follow up in [Issue 19869](https://github.com/solana-labs/solana/issues/19869)
