### ISSUE TITLE
Capitalization mismatch assert

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#19985]
#### Problem

mnb validator on v1.6.25 hits this assert

capitalization mismatch:
```
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.559793184Z INFO  solana_core::replay_stage] new root 96988796
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.559889514Z INFO  solana_core::replay_stage] vote bank: Some((96988827, SameFork)) reset bank: 96988827
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.559907209Z INFO  solana_metrics::metrics] datapoint: blocks_produced num_blocks_on_fork=17309i num_dropped_blocks_on_fork=664i
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.563958346Z INFO  solana_metrics::metrics] datapoint: banking_stage-loop-stats id=2i process_packets_count=0i new_tx_count=0i dropped_batches_count=0i newly_buffered_packets_count=0i current_buffered_packets_count=0i rebuffered_pa>
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.565443300Z INFO  solana_core::poh_recorder] reset poh from: 37WdanYWh4GLCDzdG4ZdcTHmuw27PuTbJwG87AFHAn9A,6207285018,96988826 to: 37WdanYWh4GLCDzdG4ZdcTHmuw27PuTbJwG87AFHAn9A,96988827
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.565478864Z INFO  solana_core::replay_stage] DXsfUZQe25CgChBBq7NdFqGfZsu5VC5YWW6Rz4sA49Gi reset PoH to tick 6207284992 (within slot 96988827). My next leader slot is 97024352
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.576886304Z INFO  solana_metrics::metrics] datapoint: block-commitment-cache aggregate-commitment-ms=17i highest-confirmed-root=96988792i highest-confirmed-slot=96988823i
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.601681319Z INFO  solana_metrics::metrics] datapoint: capitalization_mismatch slot=96988767i calculated_lamports=519782132386052358i capitalization=504301008666966278i
Sep 17 18:07:16 solana-validator[88262]: thread 'solana-accounts-background' panicked at 'capitalization_mismatch. slot: 96988767, calculated_lamports: 519782132386052358, capitalization: 504301008666966278', runtime/src/bank.rs:4480:13
Sep 17 18:07:16 solana-validator[88262]: stack backtrace:
Sep 17 18:07:16 solana-validator[88262]:    0:     0x559743929f70 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
Sep 17 18:07:16 solana-validator[88262]:    1:     0x559743929f70 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
Sep 17 18:07:16 solana-validator[88262]:    2:     0x559743929f70 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
Sep 17 18:07:16 solana-validator[88262]:    3:     0x559743929f70 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
Sep 17 18:07:16 solana-validator[88262]:    4:     0x5597439513dc - core::fmt::write::h89e4288724daa3fa
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
Sep 17 18:07:16 solana-validator[88262]:    5:     0x559743920942 - std::io::Write::write_fmt::h6d40f996e84584d9
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
Sep 17 18:07:16 solana-validator[88262]:    6:     0x55974392c795 - std::sys_common::backtrace::_print::h0c0b93221682afc8
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
Sep 17 18:07:16 solana-validator[88262]:    7:     0x55974392c795 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
Sep 17 18:07:16 solana-validator[88262]:    8:     0x55974392c795 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
Sep 17 18:07:16 solana-validator[88262]:    9:     0x55974392c2f3 - std::panicking::default_hook::h7b00dcc1d0944747
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
Sep 17 18:07:16 solana-validator[88262]:   10:     0x5597434fa12e - solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}::hba6a619f6b4cd493
Sep 17 18:07:16 solana-validator[88262]:   11:     0x55974392cf56 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
Sep 17 18:07:16 solana-validator[88262]:   12:     0x55974392ca77 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
Sep 17 18:07:16 solana-validator[88262]:   13:     0x55974392a40c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
Sep 17 18:07:16 solana-validator[88262]:   14:     0x55974392c9d9 - rust_begin_unwind
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
Sep 17 18:07:16 solana-validator[88262]:   15:     0x55974392c98b - std::panicking::begin_panic_fmt::h818c3c917eaeb432
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
Sep 17 18:07:16 solana-validator[88262]:   16:     0x559743307d08 - solana_runtime::bank::Bank::update_accounts_hash_with_index_option::h36ebcb8fc9bfe24f
Sep 17 18:07:16 solana-validator[88262]:   17:     0x55974325f88d - solana_runtime::accounts_background_service::SnapshotRequestHandler::handle_snapshot_requests::h3ab4f1a6c65a6605
Sep 17 18:07:16 solana-validator[88262]:   18:     0x55974329d541 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ae5755036fed908
Sep 17 18:07:16 solana-validator[88262]:   19:     0x55974323266d - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4c72a9156571a6a7
Sep 17 18:07:16 solana-validator[88262]:   20:     0x55974393628a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h61144a2be4ee36d8
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
Sep 17 18:07:16 solana-validator[88262]:   21:     0x55974393628a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcf5d395fdd120c17
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
Sep 17 18:07:16 solana-validator[88262]:   22:     0x55974393628a - std::sys::unix::thread::Thread::new::thread_start::hb5e40d3d934ebb7a
Sep 17 18:07:16 solana-validator[88262]:                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
Sep 17 18:07:16 solana-validator[88262]:   23:     0x7ff638338609 - start_thread
Sep 17 18:07:16 solana-validator[88262]:   24:     0x7ff637ec7293 - clone
Sep 17 18:07:16 solana-validator[88262]:   25:                0x0 - <unknown>
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.611751509Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-accounts-background" one=1i message="panicked at 'capitalization_mismatch. slot: 96988767, calculated_lamports: 519782132386052358, cap>
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.611846534Z INFO  solana_metrics::metrics] submitting 769 points
Sep 17 18:07:16 solana-validator[88262]: [2021-09-17T18:07:16.666762408Z INFO  solana_core::replay_stage] new fork:96988828 parent:96988827 root:96988796
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706181066Z INFO  solana_metrics::metrics] datapoint: retransmit-first-shred slot=96988828i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706219231Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=96988828i block_height=86748061i parent_slot_height=96988827i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706226378Z INFO  solana_metrics::metrics] datapoint: shred_fetch index_overrun=0i shred_count=25i slot_bad_deserialize=0i index_bad_deserialize=0i index_out_of_bounds=0i slot_out_of_range=0i duplicate_shred=0i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706240053Z INFO  solana_metrics::metrics] datapoint: banking_stage-loop-stats id=3i process_packets_count=0i new_tx_count=0i dropped_batches_count=0i newly_buffered_packets_count=0i current_buffered_packets_count=0i rebuffered_pa>
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706280894Z INFO  solana_metrics::metrics] datapoint: shred_fetch_tvu_forwards index_overrun=0i shred_count=3907i slot_bad_deserialize=0i index_bad_deserialize=0i index_out_of_bounds=0i slot_out_of_range=0i duplicate_shred=1509i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706346357Z INFO  solana_metrics::metrics] datapoint: shred_fetch_repair index_overrun=0i shred_count=9i slot_bad_deserialize=0i index_bad_deserialize=0i index_out_of_bounds=0i slot_out_of_range=0i duplicate_shred=0i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706377520Z INFO  solana_metrics::metrics] datapoint: poh-service ticks=184i hashes=2308096i elapsed_us=348588i total_sleep_us=143630i total_tick_time_us=358i total_lock_time_us=657i total_hash_time_us=846643i total_record_time_us>
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706406224Z INFO  solana_metrics::metrics] datapoint: banking_stage-loop-stats id=0i process_packets_count=0i new_tx_count=0i dropped_batches_count=0i newly_buffered_packets_count=0i current_buffered_packets_count=0i rebuffered_pa>
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706436744Z INFO  solana_metrics::metrics] datapoint: recycler_total_allocated_count name="shred_fetch_stage_recycler_shrink" count=2000i recycled_len=0i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706447629Z INFO  solana_metrics::metrics] datapoint: banking_stage-loop-stats id=2i process_packets_count=0i new_tx_count=0i dropped_batches_count=0i newly_buffered_packets_count=0i current_buffered_packets_count=0i rebuffered_pa>
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706472846Z INFO  solana_metrics::metrics] datapoint: banking_stage-loop-stats id=1i process_packets_count=0i new_tx_count=0i dropped_batches_count=0i newly_buffered_packets_count=0i current_buffered_packets_count=0i rebuffered_pa>
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706700158Z INFO  solana_metrics::metrics] datapoint: retransmit-num_nodes count=1658i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706715296Z INFO  solana_metrics::metrics] datapoint: retransmit-stage total_time=2232421i epoch_fetch=5144i epoch_cache_update=15808i total_batches=1071i total_packets=6774i retransmit_total=27134i retransmit_tree_mismatch=0i com>
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706720208Z INFO  solana_metrics::metrics] datapoint: retransmit-slot-num-packets slot=96988824i num_shreds=883i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706722798Z INFO  solana_metrics::metrics] datapoint: retransmit-slot-num-packets slot=96988825i num_shreds=1643i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706725283Z INFO  solana_metrics::metrics] datapoint: retransmit-slot-num-packets slot=96988826i num_shreds=1946i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706727323Z INFO  solana_metrics::metrics] datapoint: retransmit-slot-num-packets slot=96988827i num_shreds=1613i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706734321Z INFO  solana_metrics::metrics] datapoint: retransmit-slot-num-packets slot=96988828i num_shreds=1i
Sep 17 18:07:17 solana-validator[88262]: [2021-09-17T18:07:17.706736081Z INFO  solana_core::retransmit_stage] retransmit: top packets_by_source: {35: "5.62.127.18:8005", 37: "173.231.58.226:8006", 39: "54.77.132.209:12660", 43: "65.21.124.221:8005", 51: "5.83.175.225:8005"} len: 908
Sep 17 18:07:17 solana-validator[88262]: thread 'solana-receiver' panicked at 'cudaHostRegister error: 4 ptr: 0x7fc540799c00 bytes: 167936', perf/src/cuda_runtime.rs:33:17
Sep 17 18:07:17 solana-validator[88262]: stack backtrace:
Sep 17 18:07:17 solana-validator[88262]: total_gpus: 1
Sep 17 18:07:17 solana-validator[88262]: i: 0 size: 1312
Sep 17 18:07:17 solana-validator[88262]:    0:     0x559743929f70 - std::backtrace_rs::backtrace::libunwindthread '::tracesolana-receiver::' panicked at 'h5e9d00f0cdf4f57ecudaHostRegister error: 4 ptr: 0x7fc33af79d00 bytes: 167936
Sep 17 18:07:17 solana-validator[88262]: ',  perf/src/cuda_runtime.rs : 33 : 17
Sep 17 18:07:17 solana-validator[88262]:                         at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
Sep 17 18:07:17 solana-validator[88262]:    1:     0x559743929f70 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9thread 'solana-receiver' panicked at 'cudaHostRegister error: 4 ptr: 0x7fe5103fa200 bytes: 167936', perf/src/cuda_runtime.rs:33:17
Sep 17 18:07:22 systemd[1]: solana.service: Main process exited, code=exited, status=1/FAILURE
Sep 17 18:07:22 systemd[1]: solana.service: Failed with result 'exit-code'.
Sep 17 18:07:23 systemd[1]: solana.service: Scheduled restart job, restart counter is at 1.
Sep 17 18:07:23 systemd[1]: Stopped Solana Validator.
```

#### Proposed Solution

Debug and fix.

**Comment by MBGBuzzer** [comment]
yep this on my node(((

**Comment by jeffwashington** [comment]
attempt 1. Adding this flag to the validator to get an additional check on what could be causing the mismatch:
```
--accounts-db-test-hash-calculation
```

Explanation:
The validator should run no differently, but prior to getting the panics, hopefully get a different panic logging that the hash calculations were different than expected, providing a third piece of data: expected, calculated using accounts index (this should be the one the debug option adds), and calculated without using accounts index.

**Comment by jeffwashington** [comment]
@sakridge reports cap in binary:
```
11100110110101000110001100001110001011101110011100100000110
11011111111101000110001100001110001011101110011100100000110
```

**Comment by sakridge** [comment]
> @sakridge reports cap in binary:
> 
> ```
> 11100110110101000110001100001110001011101110011100100000110
> 11011111111101000110001100001110001011101110011100100000110
> ```

The other instance was this:

```
11011111111101000110011010111110001010110100001110100110100
11011111111101000110001100001110001011101110011100100000110
```

from `panicked at 'capitalization_mismatch. slot: 96988767, calculated_lamports: 519782132386052358, capitalization: 504301008666966278', runtime/src/bank.rs:4480:13
`

**Comment by jeffwashington** [comment]
I only detected 2 examples of this panic in [metrics](https://metrics.solana.com:3000/d/monitor-edge/cluster-telemetry-edge?orgId=2&viewPanel=28&from=now-2d&to=now&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=mainnet-beta&var-hostid=DXsfUZQe25CgChBBq7NdFqGfZsu5VC5YWW6Rz4sA49Gi), both on this validator.

**Comment by sakridge** [comment]
@jeffwashington is the calculated value correct? or the value from the bank capitalization?

**Comment by MBGBuzzer** [comment]
> attempt 1. Adding this flag to the validator to get an additional check on what could be causing the mismatch:
> 
> ```
> --accounts-db-test-hash-calculation
> ```
> 
> Explanation:
> The validator should run no differently*, but prior to getting the panics, hopefully get a different panic logging that the hash calculations were different than expected, providing a third piece of data: expected, calculated using accounts index (this should be the one the debug option adds), and calculated without using accounts index.
> 
> * validator's bg processing loop will run more slowly. This can cause an accumulation of uncleaned account data. There could also be more contention with the accounts index, causing some performance degradation of the validator.

im wait snapshot and restart validator - just wait moment

**Comment by steviez** [comment]
For the sake of pulling everything into one place, previous instances of this on 1.6 as well: https://github.com/solana-labs/solana/issues/17740

**Comment by Vovans** [comment]
I've got the same

`[2022-11-14T14:31:23.923761809Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-bg-accounts" one=1i message="panicked at 'capitalization_mismatch. slot: 160996216, calculated_lamports: 533492921110225899, capitalization: 533492921110225915', runtime/src/bank.rs:6217:13" location="runtime/src/bank.rs:6217:13" version="\"1.13.3 (src:3271b83d; feat:4011803773)\""`

Here is a log before the validator crashed [sollog.txt](https://github.com/solana-labs/solana/files/10007130/sollog.txt)

**Comment by steviez** [comment]
> calculated_lamports: 533492921110225899, capitalization: 533492921110225915

The difference in these two numbers is 16 (base 10), so it follows that they only differ by one bit in binary
```
0111 0110 0111 0101 1000 1111 1100 0011 0100 1111 0101 1110 0011 1110 1011
0111 0110 0111 0101 1000 1111 1100 0011 0100 1111 0101 1110 0011 1111 1011
                                                                    ^
```
