### ISSUE TITLE
Sporadic failure with test test_check_account_subscribe in build

### ISSUE THREAD

**Issue by lijunwangs** [solana-labs/solana#21393]
#### Problem

Seeing the following:

thread 'rpc_subscriptions::tests::test_check_account_subscribe' panicked at 'TestBroadcastReceiver: no data, timeout reached', rpc/src/rpc_pubsub_service.rs:209:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:521:12
   1: solana_rpc::rpc_pubsub_service::TestBroadcastReceiver::recv
             at ./src/rpc_pubsub_service.rs:209:21
   2: solana_rpc::rpc_subscriptions::tests::test_check_account_subscribe::{{closure}}
             at ./src/rpc_subscriptions.rs:1139:28
   3: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
   4: serial_test::serial_core
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/serial_test-0.5.1/src/lib.rs:64:5
   5: solana_rpc::rpc_subscriptions::tests::test_check_account_subscribe
             at ./src/rpc_subscriptions.rs:1045:5
   6: solana_rpc::rpc_subscriptions::tests::test_check_account_subscribe::{{closure}}
             at ./src/rpc_subscriptions.rs:1046:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 
failures:
    rpc_subscriptions::tests::test_check_account_subscribe

https://buildkite.com/solana-labs/solana/builds/59851#5786531d-4ec5-4ef3-a931-e24a6603a676

**Comment by lijunwangs** [comment]
No longer seeing this
