### ISSUE TITLE
@solana/web3.js crash on Timeout (socket close failure)

### ISSUE THREAD

**Issue by PaulBernier** [solana-labs/solana#21446]
#### Problem

Using library `@solana/web3.js` version `1.31.0` on Node.js 16.10.
Our application regularly crashes with this error that seems to happen after a timeout from this lib:

```
/app/node_modules/rpc-websockets/dist/lib/client.js:392
      this.socket.close(code || 1000, data);
                  ^
TypeError: Cannot read properties of undefined (reading 'close')
    at Client.close (/app/node_modules/rpc-websockets/dist/lib/client.js:392:19)
    at Timeout._onTimeout (/app/node_modules/@solana/web3.js/lib/index.cjs.js:6720:30)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

#### Proposed Solution

-

**Comment by rbjamaca** [comment]
I'm also experiencing the same issue in react-native ios
