### ISSUE TITLE
12.04.2021 Dapps reported large percentage of failed TXs

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#21621]
#### Problem

12.04.2021 Dapps reported large percentage of failed TXs

#### Proposed Solution

fix it

**Comment by dafyddd** [comment]
This is what a typical tx timeout would look like for us. Our client sends the same tx repeatedly every 2 seconds until 30s has passed and then it reports a "timeout". The tx may or may not get confirmed later, but usually doesn't get confirmed.

```
Started awaiting confirmation for QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6 size: 550                                                                
Fri, 03 Dec 2021 21:34:46 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:34:48 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:34:50 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:34:52 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:34:54 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:34:56 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:34:58 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:00 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:02 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:04 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:06 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:08 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:10 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:12 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Fri, 03 Dec 2021 21:35:14 GMT  sending tx  QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6                                                                 
Timed out for txid QAZyCZmLJoAtXdAdG1VQ77YDRDBbSBEkywAm89GYRtgMirGFGngaGY4NeComXdYp9tih62zbRKKZpQzq61Xkxx6
Error: Timed out awaiting confirmation on transaction
    at MangoClient.<anonymous> (/home/dd/blockworks-foundation/mango-client-v3/src/client.ts:261:15)
    at Generator.throw (<anonymous>)
    at rejected (/home/dd/blockworks-foundation/mango-client-v3/src/client.ts:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by aeyakovenko** [comment]
how many of these did you have pending?

**Comment by dafyddd** [comment]
One client will only have one of these txids on loop retrying every 2s. But all our services and all the UI use the same client so this may have been happening dozens or hundreds of times simultaneously. Also, I didn't know about this at the time, but Triton nodes were *also* doing this 2s retry on the node side. So depending on how that's implemented, it could be 100s ^ 2 number of retries.

**Comment by dafyddd** [comment]
@jstarry mentioned on twitter he doesn't think this is the likely cause: https://twitter.com/jstrry/status/1467199471058661379?s=20

**Comment by brianlong** [comment]
This has been a common problem across the defi ecosystem (not unique to Mango) during high-activity events. The transactions seem to die in the queue on the validators.

There is a common pattern that we see around these episodes. Please note, that I am suggesting correlation, not causation, with these charts.

On metrics.solana.com, we see the pending queue chart spike up like this:

<img width="2183" alt="Screen Shot 2021-12-03 at 3 24 51 PM" src="https://user-images.githubusercontent.com/79186/144767351-562a8fa9-a263-4013-bfb8-d85fbcc2aaaa.png">

and on explorer.solana.com, we see throughput drop like this:

<img width="1139" alt="Screen Shot 2021-12-03 at 3 30 47 PM" src="https://user-images.githubusercontent.com/79186/144767386-096fd50c-b9b3-4dcd-9442-3a4696d47b5b.png">

We also see banking stage forwards spike up like this:

![image](https://user-images.githubusercontent.com/79186/144767426-e26ebcb3-af95-48c3-a127-e3596e69f7f1.png)

**Comment by brianlong** [comment]
Anecdotally, I have seen two scenarios that might cause these problems:

1) Heavy compute transactions like minting NFTs. A large NFT drop can fill the maximum compute units for many blocks in a row. Throughput drops during these periods.
2) Heavy bot activity directed at high-volume defi pairs. Read/write locking on the accounts seems to have a negative impact beyond the targeted trading pair.

**Comment by CherryWorm** [comment]
![image](https://user-images.githubusercontent.com/2720007/144852666-5493fce6-14fb-4e7b-9ba5-503728c8b34b.png)

I guess this graph is not too valuable without context, but I'll try to provide as much as I can:

each unit corresponds to one or multiple transactions, red indicates either multiple of those transactions failed or didn't land in less than 15s. Spikes in failed transactions correlates very well with low-tps on the network overall. This is how it looked just last month, before the network upgraded to 1.8.5:

![image](https://user-images.githubusercontent.com/2720007/144853064-3423aeba-01be-41fe-8b48-ec0e01de07bc.png)

I think that's where the regression occured.

In my eyes this is a bug somewhere where higher-than-usual transaction loads lead to blocks not being able to be finished in time, increasing skipped slot% (would be interesting to see some statistics on that), overall forking in the network and tps to go down.

**Comment by brianlong** [comment]
Here's 30 days of aggregate skip rate data from validators.app. The skip rate moved up noticeably over the 30-day period.

 If this is helpful, I might be able to pull some extra detail per validator.

[validator_block_history_stats.csv](https://github.com/solana-labs/solana/files/7663829/validator_block_history_stats.csv)

**Comment by t-nelson** [comment]
> This is what a typical tx timeout would look like for us. Our client sends the same tx repeatedly every 2 seconds until 30s has passed and then it reports a "timeout". The tx may or may not get confirmed later, but usually doesn't get confirmed.

Is 30s significant?  It'd be more robust and predictable to rebroadcast (but not resign!) the transaction until the `lastValidBlockHeight` (from the `getFees` reply) expires.  At this point the blockhash has expired and the transaction will never land.  Also requesting that the RPC server not rebroadcast for you

> Also, I didn't know about this at the time, but Triton nodes were _also_ doing this 2s retry on the node side.

This can be disabled by passing `maxRetries` option to `sendTransaction`. Unfortunately it looks like this [isn't exposed](https://github.com/solana-labs/solana/pull/21181) in web3.js today

> @jstarry mentioned on twitter he doesn't think this is the likely cause: https://twitter.com/jstrry/status/1467199471058661379?s=20

I'd agree with Justin's assessment.  The amplification should be no worse than the number of RPC backends in your pool
