### ISSUE TITLE
Panic on master

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#21941]
#### Problem
Commit: 82672b40fd158c098136 is broken. this is master as of writing.

Build: `./cargo build --release`

My hacky way of setting up a local cluster.

terminal 1. generate genesis + setup faucet
```
solana_keygen=./target/release/solana-keygen
SOLANA_CONFIG_DIR=./config

mkdir $SOLANA_CONFIG_DIR
NDEBUG=1 ./multinode-demo/setup.sh
./target/release/solana-ledger-tool -l config/bootstrap-validator/ create-snapshot 0
NDEBUG=1 ./multinode-demo/faucet.sh
```

terminal 2: run node
```
bank_hash=$(./target/release/solana-ledger-tool -l config/bootstrap-validator bank-hash)
RUST_LOG=info,solana_runtime::bank=DEBUG,solana_core::banking_stage=DEBUG  \
	NDEBUG=1 ./multinode-demo/bootstrap-validator.sh  \
  --wait-for-supermajority 0 \
  --expected-bank-hash $bank_hash
```

wait a few minutes...
```
[2021-12-16T06:24:07.635551336Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-db-accounts-0" one=1i message="panicked at 'assertion failed: !self.is_cached()', runtime/src/account_info.rs:132:9" location="runtime/src/account_info.rs:132:9"
   0: rust_begin_unwind
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/efd0483949496b067cd5f7569d1b28cd3d5d3c72/library/core/src/panicking.rs:50:5
   3: solana_runtime::accounts_db::AccountsDb::load_accounts_index_for_shrink
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   7: rayon_core::registry::WorkerThread::wait_until_cold
   8: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-12-16T06:24:07.635907752Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-db-accounts-2" one=1i message="panicked at 'assertion failed: !self.is_cached()', runtime/src/account_info.rs:132:9" location="runtime/src/account_info.rs:132:9"
```

**Comment by buffalu** [comment]
@brooksprumo

**Comment by brooksprumo** [comment]
@jeffwashington Can you take a look at this?

**Comment by buffalu** [comment]
damn y’all fast!
