### ISSUE TITLE
Not all NFTs checked out (mainnet-beta)

### ISSUE THREAD

**Issue by annabnn812** [solana-labs/solana#22407]
#### Problem
I am used Candy Machine-v2 . Uploaded (545) out of (555). How to fix it without deleting the folder " .cache" ?

P.S. Answer from https://docs.metaplex.com/candy-machine-v2/verify-upload    
"  Error: not all NFTs checked out. check out logs above for details"

In this case, you will need to re-run the upload command. Only after the verify command succeeds should you make your Candy Machine live."  ---- THIS DOES NOT WORK. 

Writing indices 460-469
Writing indices 470-479
Writing indices 480-489
Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5tSDdJDyHrCp8JjX5ibz6v4cxYFfY4Lnif53ZnGyJtDEQ3qaxNSuX51Fjdc7T1GyPZ7jEbqcrdFtv6BDceN2K4Na using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (/home/annabnn/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (/home/annabnn/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/home/annabnn/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/home/annabnn/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async /home/annabnn/metaplex/js/packages/cli/src/commands/upload.ts:367:19
    at async Promise.all (index 0)
    at async uploadV2 (/home/annabnn/metaplex/js/packages/cli/src/commands/upload.ts:347:7)
    at async Command.<anonymous> (/home/annabnn/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:183:7)
saving config line 480-489 failed Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5tSDdJDyHrCp8JjX5ibz6v4cxYFfY4Lnif53ZnGyJtDEQ3qaxNSuX51Fjdc7T1GyPZ7jEbqcrdFtv6BDceN2K4Na using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (/home/annabnn/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (/home/annabnn/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/home/annabnn/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/home/annabnn/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async /home/annabnn/metaplex/js/packages/cli/src/commands/upload.ts:367:19
    at async Promise.all (index 0)
    at async uploadV2 (/home/annabnn/metaplex/js/packages/cli/src/commands/upload.ts:347:7)
    at async Command.<anonymous> (/home/annabnn/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:183:7)
Writing indices 490-499
Writing indices 500-509
Writing indices 510-519

annabnn@DESKTOP-I9U0J1I:~/nft_build$ ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e mainnet-beta \
    -k ~/.config/solana/mainnet-wallet.json  \
    -cp config.json \
    -c example \
    ./assets

wallet public key: 6aR1QdHg1P8PbGfsNqxPf7hbPvNRUSF2NzzHVNArZRKV
Key size 0
uploaded (545) out of (555)
/home/annabnn/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:418
      throw new Error(
            ^
Error: predefined number of NFTs (555) is smaller than the uploaded one (545)
    at Command.<anonymous> (/home/annabnn/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:418:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jacobcreech** [comment]
Hey, we don't support candy machine here. Recommended to join the [metaplex discord](https://discord.gg/v4ZQSMVy) and ask there or file an issue on the [metaplex repo](https://github.com/metaplex-foundation/js)
