### ISSUE TITLE
ProgramTestContext panics when warping to n+1 slot

### ISSUE THREAD

**Issue by kklas** [solana-labs/solana#22948]
#### Problem

When using ProgramTest and warping to the next slot (e.g. if current slot is 5 and warping to slot 6), the warp fails with a panic.

It's easy to reproduce:
```
use {
    solana_program_test::ProgramTest,
};

#[tokio::test]
async fn test_foo() {
    let mut ctx = ProgramTest::default().start_with_context().await.unwrap();
    ctx.warp_to_slot(2).unwrap();
}
```

fails with:
```
---- test_foo stdout ----
thread 'test_foo' panicked at 'assertion failed: `(left != right)`
  left: `1`,
 right: `1`', runtime/src/bank.rs:1480:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:138:5
   4: solana_runtime::bank::Bank::_new_from_parent
             at /home/work/work/solana/runtime/src/bank.rs:1480:9
   5: solana_runtime::bank::Bank::new_from_parent
             at /home/work/work/solana/runtime/src/bank.rs:1436:9
   6: solana_runtime::bank::Bank::warp_from_parent
             at /home/work/work/solana/runtime/src/bank.rs:1673:23
   7: solana_program_test::ProgramTestContext::warp_to_slot
             at ./src/lib.rs:1078:43
   8: foo::test_foo::{{closure}}
             at ./tests/foo.rs:8:5
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
  11: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:62
  12: tokio::coop::with_budget::{{closure}}
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
  13: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  14: std::thread::local::LocalKey<T>::with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  15: tokio::coop::with_budget
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  16: tokio::coop::budget
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  17: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:240:39
  18: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:29
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  20: tokio::runtime::basic_scheduler::enter
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:349:5
  21: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:230:9
  22: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:501:9
  23: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/basic_scheduler.rs:186:24
  24: tokio::runtime::Runtime::block_on
             at /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:461:46
  25: foo::test_foo
             at ./tests/foo.rs:8:5
  26: foo::test_foo::{{closure}}
             at ./tests/foo.rs:6:7
  27: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  28: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_foo

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.21s
```

**Comment by steviez** [comment]
Looks like the implementation of `ProgramTestContext::warp_to_slot()`
https://github.com/solana-labs/solana/blob/37afdd1a6544db4f74d7a15c7601f7532f6b6414/program-test/src/lib.rs#L1078-L1090
would make it expected to hit this assertion if warping ahead one slot:
https://github.com/solana-labs/solana/blob/37afdd1a6544db4f74d7a15c7601f7532f6b6414/runtime/src/bank.rs#L1523
My (possibly naive) understanding leads me to think simply skipping the warp in the `warp_slot = working_slot + 1` case should resolve this

**Comment by kklas** [comment]
Thanks for working on this!
