### ISSUE TITLE
Simulation-detection counter measures can cause validator to panic

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#23260]
#### Problem

https://github.com/solana-labs/solana/pull/22880 seems to be causing a panic in the accounts index on an rpc node with a relatively heavy amount of transactions sent to it:

```
thread 'sol-rpc-el' panicked at 'assertion failed: previous_was_cached', runtime/src/in_mem_accounts_index.rs:481:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: solana_runtime::in_mem_accounts_index::InMemAccountsIndex<T>::lock_and_update_slot_list
   4: solana_runtime::in_mem_accounts_index::InMemAccountsIndex<T>::upsert
   5: solana_runtime::accounts_index::AccountsIndex<T>::upsert
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   7: rayon::iter::plumbing::Folder::consume_iter
   8: rayon::iter::plumbing::Producer::fold_with
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: <rayon::slice::Chunks<T> as rayon::iter::IndexedParallelIterator>::with_producer
  11: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
  12: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  13: solana_runtime::accounts_db::AccountsDb::update_index
  14: solana_runtime::accounts_db::AccountsDb::store
  15: solana_runtime::bank::Bank::store_account_and_update_capitalization
  16: solana_runtime::bank::Bank::update_slot_hashes
  17: solana_runtime::bank::Bank::_new_from_parent
  18: solana_runtime::bank::Bank::simulate_transaction
  19: <solana_rpc::rpc::rpc_full::FullImpl as solana_rpc::rpc::rpc_full::rpc_impl_Full::gen_server::Full>::send_transaction
  20: <jsonrpc_core::delegates::DelegateMethodWithMeta<T,F> as jsonrpc_core::calls::RpcMethod<M>>::call
  21: jsonrpc_core::middleware::Middleware::on_call
  22: jsonrpc_core::middleware::Middleware::on_request
  23: jsonrpc_core::io::MetaIoHandler<T,S>::handle_request
  24: jsonrpc_http_server::handler::RpcHandler<M,S>::process_body
  25: <jsonrpc_http_server::handler::RpcHandler<M,S> as core::future::future::Future>::poll
  26: <jsonrpc_http_server::handler::RpcHandler<M,S> as core::future::future::Future>::poll
  27: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  28: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  29: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  30: tokio::runtime::task::harness::Harness<T,S>::poll
  31: std::thread::local::LocalKey<T>::with
  32: tokio::runtime::thread_pool::worker::Context::run_task
  33: tokio::runtime::thread_pool::worker::Context::run
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
  35: tokio::runtime::thread_pool::worker::run
  36: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  38: tokio::runtime::task::harness::Harness<T,S>::poll
  39: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

#### Proposed Solution
Triage and fix.
~~Also consider reverting v1.9 backport: https://github.com/solana-labs/solana/pull/23143~~
Reverted: https://github.com/solana-labs/solana/pull/23261 & https://github.com/solana-labs/solana/pull/23262

Also, the huge changeset in `programs/bpf/Cargo.lock` caught my attention. Not sure a dependency on solana-validator is the best idea.

**Comment by jstarry** [comment]
Is it possible that when the simulation bank for "slot + 1" was created, there was already a live bank at that slot for a different fork? If that's the case, creating the simulation bank would try to overwrite sysvar accounts for "slot + 1" and corrupt the state for the live bank.
