### ISSUE TITLE
Error: While trying to resolve module `crypto` with `react-native`

### ISSUE THREAD

**Issue by FrozenPyrozen** [solana-labs/solana#23772]
#### Problem
I'm trying to install https://github.com/solana-labs/solana-web3.js/  "@solana/web3.js": "1.35.0", into "react-native": "~0.63.4" project and run build on ios, and got an error:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/38257513/159045856-fabc59a0-e224-4c39-90b7-39054db546d8.png">

```
error: Error: While trying to resolve module `crypto` from file `/Users/admin/Projects/Work/mobile-wallet/node_modules/hdkey/lib/hdkey.js`, the package `/Users/admin/Projects/Work/mobile-wallet/node_modules/crypto/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/admin/Projects/Work/mobile-wallet/node_modules/crypto/index.js`. Indeed, none of these files exist:

  * /Users/admin/Projects/Work/mobile-wallet/node_modules/crypto/index.js(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.browser.cjs|.native.browser.cjs|.browser.cjs|.ios.cjs.js|.native.cjs.js|.cjs.js|.ios.json|.native.json|.json)
  * /Users/admin/Projects/Work/mobile-wallet/node_modules/crypto/index.js/index(.native|.ios.jsx|.native.jsx|.jsx|.ios.js|.native.js|.js|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs|.ios.browser.cjs|.native.browser.cjs|.browser.cjs|.ios.cjs.js|.native.cjs.js|.cjs.js|.ios.json|.native.json|.json)
    at DependencyGraph.resolveDependency (/Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/node-haste/DependencyGraph.js:376:17)
    at Object.resolve (/Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/admin/Projects/Work/mobile-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
```

I've tried to install crypto from https://www.npmjs.com/package/react-native-crypto and `rn-nodeify ` with steps:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/38257513/159044738-75eef9ec-18b1-4357-a627-c8eb1dced042.png">
But this doesn't work:(

#### Proposed Solution
Add react-native support in https://github.com/solana-labs/solana-web3.js

**Comment by steveluscher** [comment]
We've now advanced the requirements for `@solana/web3.js` to require RN >=0.7.0. https://github.com/solana-labs/solana/tree/master/web3.js#compatibility
