### ISSUE TITLE
Innocuous stdout panic

### ISSUE THREAD

**Issue by bartenbach** [solana-labs/solana#23814]
#### Problem
I get a harmless panic when piping output to head. This may be an actual Rust API issue and not a Solana issue.

![image](https://user-images.githubusercontent.com/572337/159340392-55f6a9f0-c5f7-45c6-ae37-221bdeb3fba2.png)

Full trace:
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1197:9
stack backtrace:
   0:     0x56184d80613c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x56184d80613c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56184d80613c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56184d80613c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56184d829c0c - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x56184d7fe6c5 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x56184d807d10 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56184d807d10 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56184d807d10 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x56184d8078c5 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x56184d8083c4 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:     0x56184d807ea0 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
  12:     0x56184d8065e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x56184d807e09 - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:     0x56184cd70c8b - std::panicking::begin_panic_fmt::hbfade3aea4ee91c4
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:460:5
  15:     0x56184d7fd915 - std::io::stdio::print_to::h42fabb8e003ac51c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/stdio.rs:1197:9
  16:     0x56184d7fd915 - std::io::stdio::_print::hd9c9dbd31aa97d70
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/stdio.rs:1209:5
  17:     0x56184cd7918f - solana::main::hd9ac2ed4975f885d
  18:     0x56184cd7e8b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf22de823ecb9cfb8
  19:     0x56184cd73e7d - std::rt::lang_start::{{closure}}::h947f5088a26585e2
  20:     0x56184d805e1b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc56adab7a77ec6e3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259:13
  21:     0x56184d805e1b - std::panicking::try::do_call::h29f013120c5abc65
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  22:     0x56184d805e1b - std::panicking::try::h86d5b2b66caec4cf
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  23:     0x56184d805e1b - std::panic::catch_unwind::h7dd136d787f51397
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  24:     0x56184d805e1b - std::rt::lang_start_internal::{{closure}}::h4a199351e630a8a5
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:48
  25:     0x56184d805e1b - std::panicking::try::do_call::h20ceb9e5dff838c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  26:     0x56184d805e1b - std::panicking::try::hc2abb46a5e41bd43
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  27:     0x56184d805e1b - std::panic::catch_unwind::h52c3eb4408ad6dfb
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  28:     0x56184d805e1b - std::rt::lang_start_internal::hd15a47be08101c28
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:20
  29:     0x56184cd7abd2 - main
  30:     0x7f4c4bad32fa - <unknown>
  31:     0x7f4c4bad33a8 - __libc_start_main
  32:     0x56184cd7209a - _start
  33:                0x0 - <unknown>
zsh: exit 101   solana validators --sort commission -n |
zsh: done       head -10
```

#### Proposed Solution
Am not expert. Can someone confirm this is not a Solana issue?

**Comment by steviez** [comment]
Not a Solana issue: https://github.com/rust-lang/rust/issues/35108
