### ISSUE TITLE
Panic on `tw` due to bad drop callpath detected

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#23976]
#### Problem

From Joe:

> Our testnet warehouse node `tw` just got this on a restart, corrupted ledger? Never seen this one before, fetching a new snapshot doesn't help either:
> 
> ```
> [2022-03-28T00:45:51.748352023Z INFO solana_metrics::metrics] datapoint: retransmit-first-shred slot=125391050i
>   0: rust_begin_unwind
>       at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
>  1: core::panicking::panic_fmt
>       at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
>  2: solana_runtime::accounts_db::AccountsDb::purge_slot
>  3: <solana_runtime::Bank as core::ops::drop::Drop>::drop
>  4: alloc::sync::Arc<T>::drop_slow
>  5: solana_rpc::transaction_status_service::TransactionStatusService::write_transaction_status_batch note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [2022-03-28T00:45:51.755152185Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-transaction-status-writer" one=1i message="panicked at 'bad drop callpath detected; Bank::drop() must run serially with other logic in ABS like clean_accounts()', runtime/src/accounts_db.rs:4007:13" location="runtime/src/accounts_db.rs:4007:13" version="\"1.10.2 (src:11be3fb7; feat:382658362)\""
> ```
> 
> I don't want to wipe it until someone can take a look

#### Proposed Solution

Debug and fix

#### Solutions

#23999: short-term: Move where the bank drop callback is set to earlier, so that all banks will it set
#23852: long-term: Rework blockstore processing to not have special handling just for startup

**Comment by brooksprumo** [comment]
#23970 was found during this debugging, but is not the root cause. There are Banks that are held *outside* of BankForks when `Tvu::new()` is called, so not all the Banks have their drop-callback set. But, since AccountsDb just has a single global flag for `is_bank_drop_callback_enabled`, this results in the panic when these other banks eventually get dropped.

**Comment by brooksprumo** [comment]
Found it.

Down in blockstore processor, in `execute_batch()`, we call:
https://github.com/solana-labs/solana/blob/2a5764ef79cff391da080cc19617f171109c4158/ledger/src/blockstore_processor.rs#L242-L243

So the transaction status sender clones the `Arc<Bank>` and sends it over to the TransactionStatusService (TSS). When the TSS receives the message and pulls out the bank, it has the last strong count.
https://github.com/solana-labs/solana/blob/2a5764ef79cff391da080cc19617f171109c4158/rpc/src/transaction_status_service.rs#L73

This Bank is not in BankForks. So, when `Tvu::new()` sets the bank-drop-callback on all the Banks in BankForks:
https://github.com/solana-labs/solana/blob/2a5764ef79cff391da080cc19617f171109c4158/core/src/tvu.rs#L251-L264

there are other Banks that do not get updated. Specifically, all the Banks that are in the TSS channel.

So it seems we need some way to have the TVU wait to set the bank-drop-callback until the TSS has processed all of its Banks. That, or somehow retroactively setting the bank-drop-callback on the banks still-to-be-processed by the TSS.

**Comment by brooksprumo** [comment]
Fixed by #23999 (master) and #24129 (v1.10). If this reproduces in v1.9, we can backport there as well.
