### ISSUE TITLE
Can't start node

### ISSUE THREAD

**Issue by jasoncsli** [solana-labs/solana#24474]
Hello, I try to start the Solana node for devnet. But I receive this error message. Do you have any ideas how could I solve it?

#### Problem
````shell
> solana-validator   --identity ./validator-keypair.json   --vote-account ./vote-account-keypair.json   --rpc-port 8899   --entrypoint entrypoint.devnet.solana.com:8001   --limit-ledger-size   --dynamic-port-range 8000-8100   --log -   --private-rpc   --no-port-check   --no-voting   --no-snapshot-fetch
[2022-04-19T07:09:55.660170258Z INFO  solana_validator] solana-validator 1.10.8 (src:623ac656; feat:1122441720)
[2022-04-19T07:09:55.660190678Z INFO  solana_validator] Starting validator with: ArgsOs {
        inner: [
            "solana-validator",
            "--identity",
            "./validator-keypair.json",
            "--vote-account",
            "./vote-account-keypair.json",
            "--rpc-port",
            "8899",
            "--entrypoint",
            "entrypoint.devnet.solana.com:8001",
            "--limit-ledger-size",
            "--dynamic-port-range",
            "8000-8100",
            "--log",
            "-",
            "--private-rpc",
            "--no-port-check",
            "--no-voting",
            "--no-snapshot-fetch",
        ],
    }
````

````shell
[2022-04-19T07:09:59.452014540Z INFO  solana_ledger::blockstore_processor] processing ledger for slot 0...
thread 'main' panicked at 'processing for bank 0 must succeed: InvalidBlock(Incomplete)', ledger/src/blockstore_processor.rs:1055:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: solana_ledger::blockstore_processor::process_blockstore_for_bank_0
   4: solana_ledger::bank_forks_utils::load_bank_forks
   5: solana_core::validator::Validator::new
   6: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-04-19T07:09:59.465572514Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'processing for bank 0 must succeed: InvalidBlock(Incomplete)', ledger/src/blockstore_processor.rs:1055:6" location="ledger/src/blockstore_processor.rs:1055:6" version="\"1.10.8 (src:623ac656; feat:1122441720)\""
````

**Comment by CriesofCarrots** [comment]
Quick reply: you will need to remove the `--no-snapshot-fetch` parameter for your first boot.
However, we don't do technical support on github. Please join us on discord for that: https://solana.com/discord
Also, devnet is currently down... I recommend you follow along at discord #devnet-announcements to know when it's back up again.
