### ISSUE TITLE
`getEstimatedFee` test times out very often

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#24730]
#### Problem

Ever since we moved from Travis CI to GitHub CI, this test from #23579 is timing out on almost all web3.js PRs.

https://github.com/solana-labs/solana/blob/7ba419e5d54582404866eda39a9fff7bb3eaa186/web3.js/test/transaction.test.ts#L117-L137

This is almost certainly because it's trying to hit testnet.

#### Proposed Solution

Is it possible to make this test hit a local validator instead, when `TEST_LIVE` is `true`?

**Comment by steveluscher** [comment]
cc/ @marcnjaramillo

**Comment by jstarry** [comment]
Yeah I'm not happy with that test. We shouldn't have any CI tests hit a live cluster. It should be using the test validator or be mocked out

**Comment by marcnjaramillo** [comment]
I'm happy to work on this. This was one of my first PRs, so I wasn't aware of the implications. I'll take a look at other tests that use test validator or mocks to get started.

**Comment by jstarry** [comment]
> I'm happy to work on this. This was one of my first PRs, so I wasn't aware of the implications. I'll take a look at other tests that use test validator or mocks to get started.

That'd be great, thanks!

**Comment by marcnjaramillo** [comment]
Working on this now. I'm curious if just setting `Connection` using the already defined `url` would suffice, or if I should create a mock server for this test? This is the only test for `Transaction` that actually needs a `connection`, so is there a preference for which approach to use?

I'm also seeing something odd when trying to run tests:

```
TSError: ⨯ Unable to compile TypeScript:
src/loader.ts:142:7 - error TS2558: Expected 0 type arguments, but got 1.

142       Readonly<{
          ~~~~~~~~~~
143         bytes: number[];
    ~~~~~~~~~~~~~~~~~~~~~~~~
... 
147         offset: number;
    ~~~~~~~~~~~~~~~~~~~~~~~
148       }>
    ~~~~~~~~
src/loader.ts:203:46 - error TS2558: Expected 0 type arguments, but got 1.

203       const dataLayout = BufferLayout.struct<IInstructionInputData>([
                                                 ~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:1243:30)
    at Object.m._compile (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Ph (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:286187)
    at u (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:288319)
    at o (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:287137)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:284879
    at Object.apply (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:199341)
    at Object.require.extensions.<computed> [as .ts] (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:1374:12)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231006
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231041
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231254
    at Su (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:228927)
    at ku (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:230341)
    at Ou (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:233586)
    at Mu (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:234409)
    at Object.import (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:238641)
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/src/bpf-loader.ts:1:329)
    at Generator.next (<anonymous>)
    at bl (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:245144)
    at kl (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:247659)
    at u (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:287740)
    at o (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:287137)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:284879
    at Object.apply (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:199341)
    at Object.require.extensions.<computed> [as .ts] (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:1374:12)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231006
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231041
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231254
    at Su (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:228587)
    at ku (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:230341)
    at Ou (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:233586)
    at Mu (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:234409)
    at Object.import (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:238641)
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/src/index.ts:1:27)
    at Generator.next (<anonymous>)
    at bl (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:245144)
    at kl (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:247659)
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:288137)
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:228903)
    at Object.m._compile (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Ph (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:286187)
    at u (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:288319)
    at o (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:287137)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:284879
    at Object.apply (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:199341)
    at Object.require.extensions.<computed> [as .ts] (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:1374:12)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231006
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231041
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:231254
    at Su (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:228587)
    at ku (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:230341)
    at Proxy.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:253887)
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:252173)
    at Tu (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:233858)
    at Bp.l [as _finalize] (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:234076)
    at Bp.resumeChildren (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:273686)
    at Object.resumeChildren (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:238735)
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/test/bpf-loader.test.ts:1:1110)
    at Generator.next (<anonymous>)
    at bl (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:245412)
    at kl (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:248178)
    at u (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:287740)
    at o (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:287137)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:284879
    at Object.apply (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:199341)
    at Object.require.extensions.<computed> [as .ts] (/Users/marcjaramillo/solana/solana/web3.js/node_modules/ts-node/src/index.ts:1374:12)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:251778
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:251820)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:254242
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:254318
    at Su (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:228587)
    at Proxy.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:254092)
    at Object.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:252173)
    at Object.t (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:279775)
    at n (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:279589)
    at Object.exports.requireOrImport (/Users/marcjaramillo/solana/solana/web3.js/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/Users/marcjaramillo/solana/solana/web3.js/node_modules/mocha/lib/esm-utils.js:55:34)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61:5)
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:34535
    at /Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:34176
    at process.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:34506)
    at Function.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:296856)
    at Function.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:296555)
    at Function.<anonymous> (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:284879)
    at Object.apply (/Users/marcjaramillo/solana/solana/web3.js/node_modules/esm/esm.js:1:199341)
    at node:internal/main/run_main_module:17:47
    at async singleRun (/Users/marcjaramillo/solana/solana/web3.js/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/marcjaramillo/solana/solana/web3.js/node_modules/mocha/lib/cli/run.js:362:5)
```

It's the top part that is particularly puzzling because I am also seeing that same error in `Message` about `Readonly` having the wrong number of arguments. Has anyone else seen this?

cc/ @steveluscher @jstarry @jordansexton @mvines @jacobcreech

**Comment by steveluscher** [comment]
Is that test failure with changes in your repo, or just on a fresh copy of `master`?

If the latter, try blowing stuff away and starting again.

```
cd web3.js/
git clean -dfx .
yarn
yarn test
```

**Comment by marcnjaramillo** [comment]
> Is that test failure with changes in your repo, or just on a fresh copy of `master`?
> 
> If the latter, try blowing stuff away and starting again.
> 

It's in the branch I created to work on this, but I created the branch after fetching the upstream `master` branch. I'll run the commands you mentioned now. Thanks!

**Comment by steveluscher** [comment]
Is this closed by https://github.com/solana-labs/solana/pull/25210, @marcnjaramillo?

**Comment by marcnjaramillo** [comment]
Yes, it is.
