### ISSUE TITLE
append vec duplicate write version

### ISSUE THREAD

**Issue by jeffwashington** [solana-labs/solana#25193]
#### Problem

v.1.9.20
when loading from snapshot:
fn generate_index()
fn process_storage_slot<'a>(
assert_ne!(occupied_version, this_version);

This is during validator startup account index generation. We're scanning appendvecs for account info to populate the index. Apparently an appendvec had the same pubkey listed twice with the same write_version. As a result, the version of the account data to use is ambiguous. It is possible the account data is the same and it doesn't matter. But, the write versions being the same should not happen afaik.
When this condition exists in a snapshot, a validator will not be able to start with this snapshot and a new one will have to be retrieved.

```
May 13 07:09:03 ams26 solana-rpc.sh[58864]: thread '<unnamed>' panicked at 'assertion failed: `(left != right)`                                                                  
May 13 07:09:03 ams26 solana-rpc.sh[58864]:   left: `291781225207`,
May 13 07:09:03 ams26 solana-rpc.sh[58864]:  right: `291781225207`', runtime/src/accounts_db.rs:6697:29                                                                          
May 13 07:09:03 ams26 solana-rpc.sh[58864]: stack backtrace:
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    0: rust_begin_unwind
May 13 07:09:03 ams26 solana-rpc.sh[58864]:              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5                                   
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    1: core::panicking::panic_fmt
May 13 07:09:03 ams26 solana-rpc.sh[58864]:              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14                                 
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    2: core::panicking::assert_failed_inner
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    3: core::panicking::assert_failed
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut                                              
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold                                          
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    6: rayon::iter::plumbing::bridge_producer_consumer::helper                                                                        
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    7: rayon_core::registry::in_worker
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    8: rayon::iter::plumbing::bridge_producer_consumer::helper                                                                        
May 13 07:09:03 ams26 solana-rpc.sh[58864]:    9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once                                  
May 13 07:09:03 ams26 solana-rpc.sh[58864]:   10: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute                                                            
May 13 07:09:03 ams26 solana-rpc.sh[58864]:   11: rayon_core::registry::WorkerThread::wait_until_cold                                                                            
May 13 07:09:03 ams26 solana-rpc.sh[58864]:   12: rayon_core::registry::ThreadBuilder::run                                                                                       
May 13 07:09:03 ams26 solana-rpc.sh[58864]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                              
May 13 07:09:03 ams26 solana-rpc.sh[58864]: [2022-05-13T07:09:03.935175837Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="?" one=1i message="panicked at 'assertion failed: `(left != right)`
May 13 07:09:03 ams26 solana-rpc.sh[58864]:       left: `291781225207`,
May 13 07:09:03 ams26 solana-rpc.sh[58864]:      right: `291781225207`', runtime/src/accounts_db.rs:6697:29" location="runtime/src/accounts_db.rs:6697:29" version="\"1.9.20 (src:devbuild; feat:2945818700)\""
```

**Comment by jeffwashington** [comment]
we saw this recently in kin sim.

**Comment by Lusitaniae** [comment]
```
Oct 11 08:38:21 dc2 solana-rpc.sh[14355]: [2022-10-11T08:38:21.424109486Z WARN  solana_core::validator] voting disabled
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]: thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:   left: `454791752923`,
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:  right: `454791752923`', runtime/src/accounts_db.rs:6771:29
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]: stack backtrace:
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    0: rust_begin_unwind
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:              at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    1: core::panicking::panic_fmt
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:              at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    2: core::panicking::assert_failed_inner
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    3: core::panicking::assert_failed
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    6: rayon::iter::plumbing::bridge_producer_consumer::helper
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    7: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    8: rayon_core::registry::WorkerThread::wait_until_cold
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:    9: rayon_core::registry::ThreadBuilder::run
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]: [2022-10-11T08:43:53.183497733Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="?" one=1i message="panicked at 'assertion failed: `(left != right)`
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:       left: `454791752923`,
Oct 11 08:43:53 dc2 solana-rpc.sh[14355]:      right: `454791752923`', runtime/src/accounts_db.rs:6771:29" location="runtime/src/accounts_db.rs:6771:29" version="\"1.10.40 (src:6d8e935c; feat:872682205)\""

```
