### ISSUE TITLE
Reducing the number of transactions when running client.sh demo causes a panic

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#2530]
#### Problem
Running multinode-demo/client.sh with a reduced `tx_count` results in a bench-tps panic at the end of the run.

The command I'm running is -
`./multinode-demo/client.sh  --num-nodes=2 --duration=60 --tx_count=500`
Stack trace -
```
Waiting for validator threads...
192.168.2.6:9102     : Exiting validator thread
192.168.2.6:8186     : Exiting validator thread
Waiting for transmit threads...
Token balance: 0
 Node address        |       Max TPS | Total Transactions
---------------------+---------------+--------------------
192.168.2.6:9102     |        502.00 | 12674 
192.168.2.6:8186     |        502.21 | 12674 

Average max TPS: 502.11, 0 nodes had 0 TPS
thread 'main' panicked at 'attempt to subtract with overflow', bench-tps/src/bench.rs:502:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
             at metrics/src/metrics.rs:231
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   7: rust_begin_unwind
             at libstd/panicking.rs:325
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   9: core::panicking::panic
             at libcore/panicking.rs:52
  10: solana_bench_tps::bench::compute_and_report_stats
             at bench-tps/src/bench.rs:502
  11: solana_bench_tps::main
             at bench-tps/src/main.rs:285
  12: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start

```
note - does not panic every single time. Recent successful result with no other changes to the codebase 
```
Highest TPS: 552.10 sampling period 1s max transactions: 21362 clients: 2 drop rate: 0.01
	Average TPS: 344.78473
```

**Comment by mvines** [comment]
Obsolete
