### ISSUE TITLE
solana math try_div has error

### ISSUE THREAD

**Issue by cola8888** [solana-labs/solana#25513]
[2022-05-24T08:21:05Z INFO  port_anchor_adaptor] amount is 41831684857, price is 4968999999, loan_to_valu is 80, radio is 0.996304937790866736, decimal is 10000000000000000000.000000000000000000
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom(14)', src\main.rs:222:79
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\core\src\panicking.rs:107
   2: core::result::unwrap_failed
             at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\core\src\result.rs:1661
   3: enum$<core::result::Result<port_variable_rate_lending_instructions::math::decimal::Decimal,enum$<solana_program::program_error::ProgramError> > >::unwrap<port_variable_rate_lending_instructions::math::decimal::Decimal,enum$<solana_program::program_error::
             at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\core\src\result.rs:1342
   4: port_anchor_adaptor::main
             at .\src\main.rs:219
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

![image](https://user-images.githubusercontent.com/63403598/169986644-f7fd1945-3b0a-4874-9686-d17f78fb66fe.png)

**Comment by cola8888** [comment]
What is the specific message of this error

**Comment by KirillLykov** [comment]
I think this issue misses some details which could help to understand the problem. In particular, it would be nice to have a minimalistic example to reproduce the problem.

**Comment by cola8888** [comment]
![image](https://user-images.githubusercontent.com/63403598/170032378-53412979-5e95-4d7e-9d6b-ab6f34d5d87f.png)
![image](https://user-images.githubusercontent.com/63403598/170032478-0be7f32f-c65d-44c6-a0bc-116c8fe013cc.png)
![image](https://user-images.githubusercontent.com/63403598/170032547-a150b84e-7915-45fb-a900-46d2e73b5137.png)

**Comment by cola8888** [comment]
![image](https://user-images.githubusercontent.com/63403598/170032884-d868af96-b373-4d4b-b545-522d47cccea9.png)
![image](https://user-images.githubusercontent.com/63403598/170032966-73611529-2f70-4d59-987c-adc102e7db55.png)
![image](https://user-images.githubusercontent.com/63403598/170032990-21af58e1-fada-4040-b227-3259e84c4ce0.png)


> I think this issue misses some details which could help to understand the problem. In particular, it would be nice to have a minimalistic example to reproduce the problem.
