### ISSUE TITLE
Too many open files in system

### ISSUE THREAD

**Issue by KorayBarkin** [solana-labs/solana#25548]
When I start the node after a while it gives me this error:

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: solana_ledger::bank_forks_utils::load_bank_forks
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-05-25T12:48:57.833951610Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Load from snapshot failed: Serialize(Io(Os { code: 23, kind: Uncategorized, message: \"Too many open files in system\" }))', ledger/src/bank_forks_utils.rs:233:10" location="ledger/src/bank_forks_utils.rs:233:10" version="\"1.10.19 (src:5e56677d; feat:2368599632)\""
```

I did add 
`LimitNOFILE=1000000 `to /etc/systemd/system/sol.service 
`DefaultLimitNOFILE=1000000` to /etc/systemd/system.conf

Also I did changed /etc/security/limits.conf as:
```
soft    nofile  65535
hard    nofile  65535
```

However, the problem remains the same any help appreciated.

**Comment by joncinque** [comment]
Hi there! We don't use GitHub for technical support.  Feel free to ask a question on StackOverflow with the "solana" tag or join us on Discord in the #validator-support channel https://discord.gg/solana
