### ISSUE TITLE
ReplayStage Panic on Restart

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#25716]
#### Problem
Trying to restart today and run into: [restart_crash.txt](https://github.com/solana-labs/solana/files/8818545/restart_crash.txt)

```
thread 'solana-replay-stage' panicked at 'assertion failed: !new_storage_location.is_cached()', runtime/src/accounts_db.rs:3632:17
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: solana_runtime::accounts_db::AccountsDb::retry_to_get_account_accessor
   4: solana_runtime::accounts_db::AccountsDb::load
   5: solana_runtime::accounts::Accounts::load_slow
   6: solana_program_runtime::sysvar_cache::SysvarCache::fill_missing_entries
   7: solana_runtime::bank::sysvar_cache::<impl solana_runtime::bank::Bank>::fill_missing_sysvar_cache_entries
   8: solana_runtime::bank::Bank::_new_from_parent
   9: solana_runtime::bank::Bank::new_from_parent_with_options
  10: solana_core::replay_stage::ReplayStage::generate_new_bank_forks
  11: solana_core::replay_stage::ReplayStage::new::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-06-01T20:24:18.687904257Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-replay-stage" one=1i message="panicked at 'assertion failed: !new_storage_location.is_cached()', runtime/src/accounts_db.rs:3632:17" location="runtime/src/accounts_db.rs:3632:17" version="\"1.10.23 (src:777c66ce; feat:1054763811)\""
```

**Comment by jstarry** [comment]
Which cluster and which validator version were you using?
