### ISSUE TITLE
Stable version crashes using testnet

### ISSUE THREAD

**Issue by tazhate** [solana-labs/solana#25754]
#### Problem
```Jun 03 09:50:44 test01 solana-rpc.sh[26327]: [2022-06-03T09:50:44.897918819Z WARN  solana_metrics::metrics] datapoint: bank-stake_delegation_accounts-invalid-account slot=135308256i vote-address="6qc8pDUvuxXTSrBPJfqWsX1qSpx4A3gZXRPkx8mBrJjB" reason=0i
Jun 03 09:50:44 test01 solana-rpc.sh[26327]: thread 'main' panicked at 'assertion failed: `(left == right)`
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:   left: `1052467075038369`,
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:  right: `1032484470924328`', runtime/src/bank.rs:2584:9
Jun 03 09:50:44 test01 solana-rpc.sh[26327]: stack backtrace:
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    0: rust_begin_unwind
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:              at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    1: core::panicking::panic_fmt
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:              at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    2: core::panicking::assert_failed_inner
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    3: core::panicking::assert_failed
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    4: solana_runtime::bank::Bank::update_rewards_with_thread_pool
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    5: solana_measure::measure::Measure::this
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    6: solana_runtime::bank::Bank::_new_from_parent
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    7: solana_runtime::bank::Bank::new_from_parent
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    8: solana_ledger::blockstore_processor::process_next_slots
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:    9: solana_ledger::blockstore_processor::process_blockstore_from_root
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:   10: solana_core::validator::Validator::new
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:   11: solana_validator::main
Jun 03 09:50:44 test01 solana-rpc.sh[26327]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jun 03 09:50:44 test01 solana-rpc.sh[26327]: [2022-06-03T09:50:44.949220690Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'assertion failed: `(left == right)`
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:       left: `1052467075038369`,
Jun 03 09:50:44 test01 solana-rpc.sh[26327]:      right: `1032484470924328`', runtime/src/bank.rs:2584:9" location="runtime/src/bank.rs:2584:9" version="\"1.10.23 (src:777c66ce; feat:1054763811)\""
```

```/home/solana/.local/share/solana/install/active_release/bin/solana-validator --version
solana-validator 1.10.23 (src:777c66ce; feat:1054763811)
```

```
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Remove empty snapshots
find "/data/solana/ledger" -name 'snapshot-*' -size 0 -print -exec rm {} \; || true

# Start solana rpc node, intended to be used with journalctl/systemctl. Logs will go to journalctl.
exec /home/solana/.local/share/solana/install/active_release/bin/solana-validator \
  --identity /home/solana/identity.json \
    --entrypoint entrypoint.testnet.solana.com:8001 \
    --entrypoint entrypoint2.testnet.solana.com:8001 \
    --entrypoint entrypoint3.testnet.solana.com:8001 \
    --ledger /data/solana/ledger \
  --accounts /solana/tmpfs/accounts \
  --log - \
  --gossip-port 8001 \
  --rpc-port 8899 \
  --rpc-bind-address 0.0.0.0 \
  --dynamic-port-range 8002-8020 \
  --wal-recovery-mode skip_any_corrupted_record \
  --limit-ledger-size 600000000 \
  --no-snapshot-fetch \
  --no-genesis-fetch \
  --no-port-check \
  --no-voting \
  --full-rpc-api \
  --enable-cpi-and-log-storage \
  --enable-rpc-transaction-history \
  --rpc-pubsub-enable-block-subscription \
  --account-index program-id spl-token-owner spl-token-mint \
  --expected-genesis-hash 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY \
  --known-validator 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on \
  --known-validator dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs \
  --known-validator Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN \
  --known-validator eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ \
  --known-validator 9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv

```

If you need any additional info please comment.

**Comment by jstarry** [comment]
@tazhate can you please share what epoch/block this happened at and also share logs from a few minutes before the crash?
