### ISSUE TITLE
thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by slashramin** [solana-labs/solana#26076]
#### Problem
Its a few hours I am falling behind 
tried restarting with latest update and new snapshot but got this error
why this is happening to me?

after updated to version 1.10.25
when I try to start run node I got this error  

```
[2022-06-20T10:08:12.932406970Z INFO  solana_metrics::metrics] datapoint: net-stats-validator in_datagrams_delta=0i no_ports_delta=0i in_errors_delta=2i out_datagrams_delta=0i rcvbuf_errors_delta=2i sndbuf_errors_delta=0i in_csum_errors_delta=0i ignored_multi_delta=0i in_errors=64612i rcvbuf_errors=64612i sndbuf_errors=0i
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `220881658854336`,
 right: `196883816393467`', runtime/src/bank.rs:2570:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: solana_runtime::bank::Bank::update_rewards_with_thread_pool
   5: solana_measure::measure::Measure::this
   6: solana_runtime::bank::Bank::_new_from_parent
   7: solana_runtime::bank::Bank::new_from_parent
   8: solana_ledger::blockstore_processor::process_next_slots
   9: solana_ledger::blockstore_processor::process_blockstore_from_root
  10: solana_core::validator::Validator::new
  11: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-06-20T10:08:13.123080255Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `220881658854336`,
     right: `196883816393467`', runtime/src/bank.rs:2570:9" location="runtime/src/bank.rs:2570:9" version="\"1.10.25 (src:d64f6808; feat:965221688)\""
```

**Comment by steviez** [comment]
I'm closing this issue as it describes the same issue we encountered in https://github.com/solana-labs/solana/issues/26028; see the comments of that issue for more details.
