### ISSUE TITLE
document using ldb to drop rocksdb column families for downgrade scenarios

### ISSUE THREAD

**Issue by jbiseda** [solana-labs/solana#26284]
#### Problem

If a validator does not know about all column families in rocksdb it will panic on startup. This breaks validator downgrade to a version prior to the version where the column family was introduced.

[2022-06-24T07:15:05.438851924Z INFO  solana_ledger::blockstore] Opening database at "/home/jeff_biseda_solana_com/github.solana-labs/solana/target/release/ledger/rocksdb"
thread 'main' panicked at 'Failed to open ledger database: RocksDb(Error { message: "Invalid argument: Column families not opened: optimistic_slots" })', core/src/validator.rs:1350:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: solana_core::validator::Validator::new
   4: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-06-24T07:15:05.481118007Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Failed to open ledger database: RocksDb(Error { message: \"Invalid argument: Column families not opened: optimistic_slots\" })', core/src/validator.rs:1350:6" location="core/src/validator.rs:1350:6" version="\"1.10.27 (src:devbuild; feat:1425680972)\""

#### Proposed Solution

document downgrade procedure:

# install
$ sudo apt install rocksdb-tools

# view existing column families
$ ldb --db=github.solana-labs/solana/target/release/ledger/rocksdb/ list_column_families

# remove column family
$ ldb --db=ledger/rocksdb drop_column_family optimistic_slots
OK

**Comment by jbiseda** [comment]
duplicate of #26424
