### ISSUE TITLE
Manually close `Connection` in web3.js?

### ISSUE THREAD

**Issue by ndrewtl** [solana-labs/solana#26648]
#### Problem
While running a Jest test harness, the code seems to throw an exception do to it exiting while a `Connection` is still open:
```js
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPWRAP

      33 | ): Promise<PublicKey[]> {
      34 |
    > 35 |   const { value } = await connection.getParsedTokenAccountsByOwner(
         |                                      ^
      36 |     publicKey, { programId: TOKEN_PROGRAM_ID }
      37 |   );
      38 |

      at node_modules/node-fetch/lib/index.js:1468:15
      at Function.fetch [as default] (node_modules/node-fetch/lib/index.js:1437:9)
      at fetch (node_modules/@solana/web3.js/src/fetch-impl.ts:12:16)
      at ClientBrowser.callServer (node_modules/@solana/web3.js/src/connection.ts:1009:23)
      at ClientBrowser.request (node_modules/jayson/lib/client/browser/index.js:102:8)
      at node_modules/@solana/web3.js/src/connection.ts:1048:14
      at Connection._rpcRequest (node_modules/@solana/web3.js/src/connection.ts:1047:12)
      at Connection.getParsedTokenAccountsByOwner (node_modules/@solana/web3.js/src/connection.ts:2563:34)
```

#### Proposed Solution

Provide a way to manually close a `Connection`. Perhaps a method like `Connection.close(): Promise<void>`.

**Comment by steveluscher** [comment]
I think the problem might actually be because of the connection agent manager we have going on. Follow along in #25069!
