### ISSUE TITLE
React-native build fails when generating the dsym file

### ISSUE THREAD

**Issue by adilmezghouti** [solana-labs/solana#27251]
#### Problem
The react-native build fails during the minification step. Note that the build used to work fine with version 1.47.3. Here is the error I am getting:
error node_modules/@solana/web3.js/lib/index.native.js: Unexpected token name «n», expected punc «,» in file node_modules/@solana/web3.js/lib/index.native.js at 4138:32.
Error: Unexpected token name «n», expected punc «,» in file node_modules/@solana/web3.js/lib/index.native.js at 4138:32
    at minifyCode (/Users/username/development/projectName/node_modules/metro-transform-worker/src/index.js:101:13)
    at transformJS (/Users/username/development/projectName/node_modules/metro-transform-worker/src/index.js:319:28)
    at transformJSWithBabel (/Users/username/development/projectName/Mobile/node_modules/metro-transform-worker/src/index.js:410:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/username/development/projectName/Mobile/node_modules/metro-transform-worker/src/index.js:571:12)

#### Environment information:
- node: v16.14.0
- react-native: 0.68.2
- solana-web3.js: 1.53.0

**Comment by lichmac** [comment]
Any update? I got the error

**Comment by mr-574rk** [comment]
im having same issue , any solution yet?

**Comment by adilmezghouti** [comment]
Updating metro.config.js to configure the metro transformer to use the terser minifier worked for me. You can do so by adding this to the transformer section: `minifierPath: 'metro-minify-terser',`
To make this work, you need to yarn or npm install metro-minify-terser as well.

**Comment by adamkoot** [comment]
> Updating metro.config.js to configure the metro transformer to use the terser minifier worked for me. You can do so by adding this to the transformer section: `minifierPath: 'metro-minify-terser',` To make this work, you need to yarn or npm install metro-minify-terser as well.

It's works for me, thanks!
