### ISSUE TITLE
move_and_async_delete_path failing on /mnt/accounts

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#27350]
#### Problem

Seeing panics on master running on tesnet w/ /mnt/accounts. I think https://github.com/solana-labs/solana/pull/27306 introduced it?
```
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]: [2022-08-23T20:29:06.652713190Z INFO  solana_core::validator] Cleaning accounts paths..
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]: [2022-08-23T20:29:06.652738929Z WARN  solana_core::validator] Path renaming failed: Permission denied (os error 13).  Falling back to rm_dir in sync mode
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', core/src/validator.rs:2095:40
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]: stack backtrace:
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:    0: rust_begin_unwind
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:    1: core::panicking::panic_fmt
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:    2: core::result::unwrap_failed
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:              at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:    3: solana_core::validator::move_and_async_delete_path
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:    4: solana_core::validator::Validator::new
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]:    5: solana_validator::main
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 23 20:29:06 tx-testnet-2 start-validator.sh[4165672]: [2022-08-23T20:29:06.665333442Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }', core/src/validator.rs:2095:40" location="core/src/validator.rs:2095:40" version="\"1.12.0 (src:devbuild; feat:599178905)\""
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]: [2022-08-23T20:29:08.127639078Z INFO  solana_validator] solana-validator 1.12.0 (src:devbuild; feat:599178905)
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]: [2022-08-23T20:29:08.127652263Z INFO  solana_validator] Starting validator with: ArgsOs {
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:         inner: [
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "/home/jito/jito-solana/target/release/solana-validator",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--identity",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "/home/jito/validator-keys/validator-keypair-3.json",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--vote-account",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "/home/jito/validator-keys/vote-account-keypair-3.json",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--rpc-port",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "8899",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--entrypoint",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "entrypoint.testnet.solana.com:8001",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--entrypoint",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "entrypoint2.testnet.solana.com:8001",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--entrypoint",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "entrypoint3.testnet.solana.com:8001",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--limit-ledger-size",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--log",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "-",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--enable-rpc-transaction-history",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--rpc-pubsub-enable-block-subscription",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--full-rpc-api",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--accounts",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "/mnt/accounts",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--ledger",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "/mnt/ledger",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--block-engine-address",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "http://block-engine.testnet.dallas.jito.wtf:1003",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--block-engine-auth-service-address",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "http://block-engine.testnet.dallas.jito.wtf:1005",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--shred-receiver-address",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "145.40.99.197:1002",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--tip-payment-program-pubkey",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "3jarB2NVZc9KouEppPHoAf3v9y77H5R88nyfMLDUzuwm",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--tip-distribution-program-pubkey",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "7QnFbRZajkym8mUh9rXuM5nKrPAPRfEU6W31izSWJDVh",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--tip-distribution-account-payer",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "/home/jito/validator-keys/validator-keypair-3.json",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--merkle-root-upload-authority",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "7QnFbRZajkym8mUh9rXuM5nKrPAPRfEU6W31izSWJDVh",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--commission-bps",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "800",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:             "--private-rpc",
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:         ],
Aug 23 20:29:08 tx-testnet-2 start-validator.sh[4165833]:     }
```

```
jito@tx-testnet-2:~$ ls -lh /mnt/
total 4.0K
drwxrwxrwt 2 jito jito   40 Aug 23 20:26 accounts
drwxr-xr-x 8 jito root 4.0K Aug 23 20:36 ledger
jito@tx-testnet-2:~$ cat /etc/fstab
UUID=fa2e1ad5-0a41-4203-b27e-8a9929768287	/	ext4	errors=remount-ro	0	1
UUID=9ad71f9d-c32c-48fb-81f0-27013987c0dc	none	swap	none	0	0
/dev/nvme0n1p1 /mnt/ledger ext4 defaults 0 1
none /mnt/accounts tmpfs defaults,size=128G 0 0
```

#### Proposed Solution
Fail early or handle properly?

**Comment by buffalu** [comment]
https://github.com/solana-labs/solana/pull/27386
