### ISSUE TITLE
thread 'solana-cleanup-accounts-3' panic

### ISSUE THREAD

**Issue by austin1231789** [solana-labs/solana#27439]
Issue occurred and it did not panic or freeze up, it just restarted the service.
```
thread 'solana-cleanup-accounts-3' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 12, kind: OutOfMemory, message: "Cannot allocate memory" }', runtime/src/cache_hash_data.rs:87:45
thread 'solana-cleanup-accounts-6' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 12, kind: OutOfMemory, message: "Cannot allocate memory" }', runtime/src/cache_hash_data.rs:87:45
[2022-08-27T21:28:50.858709549Z INFO  solana_metrics::metrics] datapoint: block-commitment-cache aggregate-commitment-ms=15i highest-confirmed-root=147930926i highest-confirmed-slot=147930957i
   0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: solana_runtime::cache_hash_data::CacheHashDataFile::load_map
   4: solana_runtime::cache_hash_data::CacheHashData::load
[2022-08-27T21:28:50.933592620Z INFO  solana_metrics::metrics] datapoint: shred_fetch_tvu_forwards index_overrun=0i shred_count=3610i ping_count=0i ping_err_verify_count=0i slot_bad_deserialize=0i index_bad_deserialize=0i index_out_of_bounds=0i slot_out_of_range=0i duplicate_shred=1484i
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   6: rayon::iter::plumbing::Folder::consume_iter
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon_core::job::StackJob<L,F,R>::run_inline
   9: rayon_core::registry::in_worker
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: rayon_core::job::StackJob<L,F,R>::run_inline
  12: rayon_core::registry::in_worker
  13: rayon::iter::plumbing::bridge_producer_consumer::helper
  14: std::panicking::try
  15: rayon_core::registry::in_worker
  16: rayon::iter::plumbing::bridge_producer_consumer::helper
  17: std::panicking::try
  18: rayon_core::registry::in_worker
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: std::panicking::try
  21: rayon_core::registry::in_worker
  22: rayon::iter::plumbing::bridge_producer_consumer::helper
  23: std::panicking::try
  24: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  25: rayon_core::registry::WorkerThread::wait_until_cold
  26: rayon_core::registry::in_worker
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: std::panicking::try
  29: rayon_core::registry::in_worker
  30: rayon::iter::plumbing::bridge_producer_consumer::helper
  31: std::panicking::try
  32: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  33: rayon_core::registry::WorkerThread::wait_until_cold
  34: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: solana_runtime::cache_hash_data::CacheHashDataFile::load_map
   4: solana_runtime::cache_hash_data::CacheHashData::load
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   6: rayon::iter::plumbing::Folder::consume_iter
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon_core::job::StackJob<L,F,R>::run_inline
   9: rayon_core::registry::in_worker
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: std::panicking::try
  12: rayon_core::registry::in_worker
  13: rayon::iter::plumbing::bridge_producer_consumer::helper
  14: std::panicking::try
  15: rayon_core::registry::in_worker
  16: rayon::iter::plumbing::bridge_producer_consumer::helper
  17: std::panicking::try
  18: rayon_core::registry::in_worker
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: rayon_core::job::StackJob<L,F,R>::run_inline
  21: rayon_core::registry::in_worker
  22: rayon::iter::plumbing::bridge_producer_consumer::helper
  23: std::panicking::try
  24: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  25: rayon_core::registry::WorkerThread::wait_until_cold
  26: rayon_core::registry::in_worker
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: std::panicking::try
  29: rayon_core::registry::in_worker
  30: rayon::iter::plumbing::bridge_producer_consumer::helper
  31: std::panicking::try
  32: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  33: rayon_core::registry::WorkerThread::wait_until_cold
  34: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: solana_runtime::cache_hash_data::CacheHashDataFile::load_map
   4: solana_runtime::cache_hash_data::CacheHashData::load
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   6: rayon::iter::plumbing::Folder::consume_iter
   7: rayon::iter::plumbing::bridge_producer_consumer::helper
   8: rayon_core::job::StackJob<L,F,R>::run_inline
   9: rayon_core::registry::in_worker
  10: rayon::iter::plumbing::bridge_producer_consumer::helper
  11: std::panicking::try[2022-08-27T21:28:50.948318305Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-cleanup-accounts-8" one=1i message="panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 12, kind: OutOfMemory, message: \"Cannot allocate memory\" }', runtime/src/cache_hash_data.rs:87:45" location="runtime/src/cache_hash_data.rs:87:45" version="\"1.10.34 (src:4edcb5f3; feat:483097211)\""

  12: rayon_core::registry::in_worker
  13: rayon::iter::plumbing::bridge_producer_consumer::helper
  14: std::panicking::try
  15: rayon_core::registry::in_worker
  16: rayon::iter::plumbing::bridge_producer_consumer::helper
  17: std::panicking::try
  18: rayon_core::registry::in_worker
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: std::panicking::try
  21: rayon_core::registry::in_worker
  22: rayon::iter::plumbing::bridge_producer_consumer::helper
  23: std::panicking::try
  24: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  25: rayon_core::registry::WorkerThread::wait_until_cold
  26: rayon_core::registry::in_worker
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: std::panicking::try
  29: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  30: rayon_core::registry::WorkerThread::wait_until_cold
  31: rayon_core::registry::in_worker
  32: rayon::iter::plumbing::bridge_producer_consumer::helper
  33: std::panicking::try
  34: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  35: rayon_core::registry::WorkerThread::wait_until_cold
  36: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-08-27T21:28:50.952189268Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-cleanup-accounts-3" one=1i message="panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 12, kind: OutOfMemory, message: \"Cannot allocate memory\" }', runtime/src/cache_hash_data.rs:87:45" location="runtime/src/cache_hash_data.rs:87:45" version="\"1.10.34 (src:4edcb5f3; feat:483097211)\""
[2022-08-27T21:28:50.952241826Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-cleanup-accounts-6" one=1i message="panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 12, kind: OutOfMemory, message: \"Cannot allocate memory\" }', runtime/src/cache_hash_data.rs:87:45" location="runtime/src/cache_hash_data.rs:87:45" version="\"1.10.34 (src:4edcb5f3; feat:483097211)\""
[2022-08-27T21:28:50.956168272Z INFO  solana_metrics::metrics] datapoint: replay-loop-voting-stats vote_push_us=0i vote_send_us=0i generate_vote_us=98i update_commitment_cache_us=5i
[2022-08-27T21:28:50.956177179Z INFO  solana_metrics::metrics] datapoint: replay-loop-timing-stats total_elapsed_us=1067000i collect_frozen_banks_elapsed=152i compute_bank_stats_elapsed=22158i select_vote_and_reset_forks_elapsed=16i start_leader_elapsed=107i reset_bank_elapsed=116i voting_elapsed=1098i select_forks_elapsed=7i compute_slot_stats_elapsed=24i generate_new_bank_forks_elapsed=9770i replay_active_banks_elapsed=231997i process_gossip_duplicate_confirmed_slots_elapsed=0i process_unfrozen_gossip_verified_vote_hashes_elapsed=322i wait_receive_elapsed=800490i heaviest_fork_failures_elapsed=0i bank_count=2i process_duplicate_slots_elapsed=5i repair_correct_slots_elapsed=2i retransmit_not_propagated_elapsed=0i generate_new_bank_forks_read_lock_us=0i generate_new_bank_forks_get_slots_since_us=5396i generate_new_bank_forks_loop_us=4104i generate_new_bank_forks_write_lock_us=40i replay_blockstore_us=199026i
```

**Comment by apfitzge** [comment]
From the logs you posted it looks to have panicked, I'm guessing your service has auto-restart on.

Do you still have the logs from around the time of the crash?

This is potentially related to another issue: #26375, which we've seen lead to OOM crashes like this #27297

**Comment by apfitzge** [comment]
I see there's a large number of storages open right before the time of that panic. I can also see the number of stores is steadily increasing over time
```
[2022-08-27T21:28:10.604829258Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=994287i recycle_count=1000i total_bytes=110851665920i total_alive_bytes=105110683648i total_alive_ratio=0.9482102300912357
```

That points to it being the issue I linked above. Thanks for linking the logs, @codemonkey6969!
