### ISSUE TITLE
Explorer does not display epoch details for testnet.

### ISSUE THREAD

**Issue by mschneider** [solana-labs/solana#27586]
#### Problem

Example: https://explorer.solana.com/epoch/357?cluster=testnet
Visiting this URL results in a JS error:

```
SolanaJSONRPCError: failed to get blocks: BigTable query failed (maybe timeout due to too large range?)
    at t.<anonymous> (connection.ts:3937:13)
    at u (client.js:63:40)
    at Generator._invoke (client.js:293:22)
    at Generator.next (client.js:118:21)
    at o (asyncToGenerator.js:3:20)
    at r (asyncToGenerator.js:25:9) 'failed to get blocks: BigTable query failed (maybe timeout due to too large range?)'
```

**Comment by jstarry** [comment]
Works fine for me, please reopen if you're still seeing this

**Comment by mschneider** [comment]
yes
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/144124/193246014-352781f1-aa2a-4be1-9229-6ca5fa6d8877.png">

**Comment by mschneider** [comment]
@jstarry can't reopen myself
