### ISSUE TITLE
Error in main TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by seal** [solana-labs/solana#28023]
```js
const {Connection, clusterApiUrl, LAMPORTS_PER_SOL, Keypair, StakeProgram, Authorized, Lockup, sendAndConfirmTransaction} = require("@solana/web3.js");
const main = async() =>{
    const connection = new Connection(clusterApiUrl("devnet"), "processed")
    const wallet = Keypair.generate()
    const airdropSignature = await connection.requestAirdrop(wallet.publicKey, 1 * LAMPORTS_PER_SOL);
    const latestBlockHash = await connection.getLatestBlockhash();
    await connection.confirmTransaction({
      blockhash: latestBlockHash.blockhash,
      lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
      signature: airdropSignature,
    });
    //const balance = await connection.getBalance(wallet.publicKey);
    //console.log("Balance in sol: ", balance / LAMPORTS_PER_SOL);

    const stakeAccount = Keypair.generate()
    const minimumRent = await connection.getMinimumBalanceForRentExemption(StakeProgram.space)
    const amountUserWantsToStake = 0.5 * LAMPORTS_PER_SOL
    const amountToStake = minimumRent + amountUserWantsToStake
    
    const createStakeAccountTx = StakeProgram.createAccount({
        authorized: new Authorized(wallet.publicKey, wallet.publicKey),
        fromPubkey: wallet.publicKey, 
        lamports: amountToStake,
        lockup: new Lockup(0, 0, wallet.publicKey),
        stakePubKey: stakeAccount.publicKey
    })
    const createStakeAccountTxID = await sendAndConfirmTransaction(connection, createStakeAccountTx, [wallet, stakeAccount])
    console.log(`Successfully staked thngy, TXID: ${createStakeAccountTxID}`) 
    let stakeBalance = await connection.getBalance(stakeAccount.publicKey)
    console.log(`Stake account baalnce: ${stakeBalance / LAMPORTS_PER_SOL} sol`)

    let stakeStatus = await connection.getStakeActivation(stakeAccount.publicKey);
    console.log(`stake account status: ${stakeAccount.state}`);
};

const runMain = async() =>{
    try{
        await main();
    }catch(error){
        console.error("Error in main", error)
    }
};
runMain();
```

Error:
```
...@debian:~/Documents/code/staking$ node create_stake_account.js
Error in main TypeError: Cannot read properties of undefined (reading 'toString')
    at /home/.../Documents/code/staking/node_modules/@solana/web3.js/lib/index.cjs.js:1539:47
    at Array.forEach (<anonymous>)
    at Transaction.compileMessage (/home/.../Documents/code/staking/node_modules/@solana/web3.js/lib/index.cjs.js:1538:18)
    at Transaction._compile (/home/.../Documents/code/staking/node_modules/@solana/web3.js/lib/index.cjs.js:1659:26)
    at Transaction.sign (/home/.../Documents/code/staking/node_modules/@solana/web3.js/lib/index.cjs.js:1764:26)
    at Connection.sendTransaction (/home/.../Documents/code/staking/node_modules/@solana/web3.js/lib/index.cjs.js:6666:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendAndConfirmTransaction (/home/.../Documents/code/staking/node_modules/@solana/web3.js/lib/index.cjs.js:2218:21)
    at async main (/home/.../Documents/code/staking/create_stake_account.js:27:36)
    at async runMain (/home/.../Documents/code/staking/create_stake_account.js:38:9)

```

**Comment by jstarry** [comment]
Please use TypeScript... to fix your error change `stakePubKey` to `stakePubkey`
