### ISSUE TITLE
Invalid vote account owner error during reserialize bank

### ISSUE THREAD

**Issue by jeffwashington** [solana-labs/solana#28400]
#### Problem
local cluster test fails
https://discord.com/channels/428295358100013066/560503042458517505/1030369022463717407
https://buildkite.com/solana-labs/solana/builds/83743#0183d475-7ece-4f4b-9f23-35a0c204f8c9
```
thread 'solAcctHashVer' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Invalid vote account owner: ExTahJGb4V2UWtrfuukGmaYKUMrBUkEY74BPwFhfUuxb")', /solana/runtime/src/serde_snapshot/newer.rs:357:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: <solana_runtime::serde_snapshot::newer::Context as solana_runtime::serde_snapshot::TypeContext>::reserialize_bank_fields_with_hash
   4: solana_runtime::serde_snapshot::reserialize_bank_with_new_accounts_hash
   5: solana_core::accounts_hash_verifier::AccountsHashVerifier::process_accounts_package
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'solAcctHashVer' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Invalid vote account owner: ExTahJGb4V2UWtrfuukGmaYKUMrBUkEY74BPwFhfUuxb")', /solana/runtime/src/serde_snapshot/newer.rs:357:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: <solana_runtime::serde_snapshot::newer::Context as solana_runtime::serde_snapshot::TypeContext>::reserialize_bank_fields_with_hash
   4: solana_runtime::serde_snapshot::reserialize_bank_with_new_accounts_hash
   5: solana_core::accounts_hash_verifier::AccountsHashVerifier::process_accounts_package


```

#### Proposed Solution
debug/fix

**Comment by jeffwashington** [comment]
maybe?
https://github.com/solana-labs/solana/blob/31c2b2994149a56edb5440e1d7923c3de00257e7/runtime/src/serde_snapshot/newer.rs#L394

**Comment by jeffwashington** [comment]
retried the ci and it passed
running it locally passed

**Comment by jeffwashington** [comment]
```
  16:     0x559b53b67ab3 - solana_core::validator::Validator::join::h11f0eeeed3c5e2fb

  17:     0x559b53a6b445 - solana_local_cluster::local_cluster::LocalCluster::close_preserve_ledgers::hab2ee0eceae93b62

  18:     0x559b539b60dd - core::ptr::drop_in_place<solana_local_cluster::local_cluster::LocalCluster>::h496a062c300cdb22
  ```
we are doing a shutdown and this join is happening.

**Comment by jeffwashington** [comment]
> maybe?
> 
> https://github.com/solana-labs/solana/blob/31c2b2994149a56edb5440e1d7923c3de00257e7/runtime/src/serde_snapshot/newer.rs#L394

I was wrong. This should be the failure:
https://github.com/solana-labs/solana/blob/31c2b2994149a56edb5440e1d7923c3de00257e7/runtime/src/serde_snapshot/newer.rs#L357
