### ISSUE TITLE
`assert__WEBPACK_IMPORTED_MODULE_10__.ok is not a function` on websocket events.

### ISSUE THREAD

**Issue by jessupjn** [solana-labs/solana#29759]
#### Problem

I am seeing this on websocket events
```
TypeError: assert__WEBPACK_IMPORTED_MODULE_10__.ok is not a function
    at ExecutionContext.program (event.ts:276:1)
    at EventParser.handleLog (event.ts:212:1)
    at EventParser.parseLogs (event.ts:184:1)
    at parseLogs.next (<anonymous>)
    at event.ts:104:1
    at connection.ts:6098:1
    at Set.forEach (<anonymous>)
    at Connection._handleServerNotification (connection.ts:6096:1)
    at Connection._wsOnLogsNotification (connection.ts:6335:1)
    at Client.emit (index.js:181:1)
```

**Comment by jessupjn** [comment]
Fixed by adding the `assert` package to my webpack config:
```
assert: require.resolve('assert/')
```
