### ISSUE TITLE
solana-validator 1.14.x panic on MB

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana#30049]
At shortly after 1100 UTC on 1 February 2023 our validator running jito-solana 1.14.13 restarted unexpectedly. Upon investigation it appears all 1.14.x nodes on mainnet-beta became delinquent.

This panic was observed in our logs: 

```
0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: solana_core::progress_map::ProgressMap::get_leader_propagation_slot_must_exist
   3: solana_core::replay_stage::ReplayStage::retransmit_latest_unpropagated_leader_slot
   4: solana_core::replay_stage::ReplayStage::new::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-02-01T10:59:25.113811498Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i message="panicked at 'slot=175475903 must exist in ProgressMap', core/src/progress_map.rs:400:32" location="core/src/progress_map.rs:400:32" version="\"1.14.13 (src:devbuild; feat:627291041)\""
```

Last 1000 log lines before restart attached

[crash-log.log](https://github.com/solana-labs/solana/files/10556335/crash-log.log)

**Comment by anoushk1234** [comment]
https://github.com/solana-labs/solana/blob/0a3e52ba8b4f63c3675fa91fc89c4f54f69e5855/core/src/replay_stage.rs#L2944-L2946
Looks like this is where the panic is from, any idea why the ForkProgress doesnt exist in the hashmap?
We could handle the None value gracefully here but i assume the panic here is by design so we should look into why ForkProgress doesnt exist for the slot

**Comment by behzadnouri** [comment]
This seems to be invoked from call path modified in https://github.com/solana-labs/solana/pull/22157
cc @carllin @jbiseda

**Comment by bw-solana** [comment]
Link to Discord channel:  https://discord.com/channels/428295358100013066/1070358366645391410

**Comment by bw-solana** [comment]
From the logs, I'm seeing we had the following sequence:
1. duplicate confirmed slots w/ different hashes
2. purged slot 175475896 and all its descendants (175475897,175475898,175475901-4)
3. panicked because 175475903 didn't exist in the progress map

So it makes sense the progress entry isn't there... we explicitly removed it just milliseconds earlier!
And thus, I think it's perfectly fine to just skip retransmitting in the case where we don't find ForkProgress entry for that slot. Seems perfectly legal that the entry has been pruned out by this point (although should be rare)

**Comment by steviez** [comment]
As noted in the Discord channel, I think there are two distinct points here:
1. The runtime divergence that kicked things off
2. The observed panic that is called out in the main issue description

I broke off a separate issue to address 1 (https://github.com/solana-labs/solana/issues/30060), I think this issue can continue down the line of looking at if we want a code change around 2 (ie if we should be panicking here).

FWIW - the nodes that hit this were in an unrecoverable state. In previous versions, the node would get in an infinite loop of replay/check/purge/repair and OOM. So, maybe we want to fix this mechanism to have proper sync, but the nodes weren't going to make progress panic or not.

And a peak at the future - we have a check in v1.15+ that observes when we're in the aforementioned loop, and explicitly breaks out:
```
thread 'solReplayStage' panicked at 'We have tried to repair duplicate slot: 175475896 more than
10 times and are unable to freeze a block with bankhash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY,
instead we have a block with bankhash Some(9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA).
This is most likely a bug in the runtime. At this point manual intervention is needed to make progress.

Exiting', core/src/replay_stage.rs:1252:25
```

**Comment by jbiseda** [comment]
Looking at this to address (2).

**Comment by AshwinSekar** [comment]
for (2) we should panic as soon as we try to dump & repair a slot for which we were the leader, because this implies either
* We are producing duplicate blocks
* There is a bug in our runtime/replay code that produces incorrect bank hashes on correct blocks

Either way, manual intervention is required so we should panic ASAP with a detailed error msg.

**Comment by behzadnouri** [comment]
So far the only scenario which we have seen this to panic was a consensus bug resulting in a hash mismatch; in fact having the check here was useful because that consensus bug was irrecoverable anyways and helped to identify which slot exactly had diverged. So in this case it was a valid sanity check identifying a consensus bug.

If there is a legit scenario (i.e. one without a consensus/runtime bug) which can cause this to panic, then we need to account for that and not always panic here. Otherwise I think it is good to keep the sanity check to avoid introducing consensus bugs. Silencing the panic would only make it harder to identify those bugs early on when they are added.

**Comment by steviez** [comment]
I took a second look at how a v1.14 node responded vs. a v1.15 (master at the time) node responded. Below are some annotated logs snippets that tell the story. I think these are useful for understanding the situation, but you can skip past to my thoughts at the bottom:
```
// Detect that we differ from the cluster
[2023-02-01T10:59:25.793734195Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175475896
with hash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY,
but our version has hash 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA

// Purge the divergent slot and descendants
[2023-02-01T10:59:25.796440873Z WARN  solana_core::replay_stage] purging slot 175475896
...
[2023-02-01T10:59:25.849008451Z WARN  solana_core::replay_stage] purging descendant: 175475898 with slot_id 110345, of slot 175475896
[2023-02-01T10:59:25.850089954Z WARN  solana_core::replay_stage] purging descendant: 175475901 with slot_id 110347, of slot 175475896
[2023-02-01T10:59:25.850935088Z INFO  solana_ledger::blockstore] Pruning expired primary index 0 up to slot 0 (max requested: 175475902)
[2023-02-01T10:59:25.852300660Z WARN  solana_core::replay_stage] purging descendant: 175475903 with slot_id 110349, of slot 175475896
[2023-02-01T10:59:25.852733973Z INFO  solana_ledger::blockstore] Pruning expired primary index 1 up to slot 0 (max requested: 175475904)
[2023-02-01T10:59:25.852811670Z WARN  solana_core::replay_stage] purging descendant: 175475902 with slot_id 110348, of slot 175475896
[2023-02-01T10:59:25.854624140Z INFO  solana_ledger::blockstore] Pruning expired primary index 0 up to slot 0 (max requested: 175475903)
[2023-02-01T10:59:25.855813187Z WARN  solana_core::replay_stage] purging descendant: 175475897 with slot_id 110344, of slot 175475896
[2023-02-01T10:59:25.856166939Z INFO  solana_ledger::blockstore] Pruning expired primary index 1 up to slot 0 (max requested: 175475898)
[2023-02-01T10:59:25.857392255Z WARN  solana_core::replay_stage] purging descendant: 175475896 with slot_id 110343, of slot 175475896
[2023-02-01T10:59:25.860762562Z INFO  solana_ledger::blockstore] Pruning expired primary index 0 up to slot 0 (max requested: 175475897)
[2023-02-01T10:59:25.862009358Z WARN  solana_core::replay_stage] Notifying repair service to repair duplicate slot: 175475896

// Hit the ProgressMap panic
thread 'solReplayStage' panicked at 'slot=175475902 must exist in ProgressMap', core/src/progress_map.rs:400:32
stack backtrace:
[2023-02-01T10:59:25.883806341Z INFO  solana_metrics::metrics] datapoint: vote-processing-timing vote_txn_processing_us=12177i slot_confirming_time_us=3956i
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: solana_core::progress_map::ProgressMap::get_leader_propagation_slot_must_exist
   3: solana_core::replay_stage::ReplayStage::retransmit_latest_unpropagated_leader_slot
   4: solana_core::replay_stage::ReplayStage::new::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-02-01T10:59:25.902646652Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i message="panicked at 'slot=175475902 must exist in ProgressMap', core/src/progress_map.rs:400:32" location="core/src/progress_map.rs:400:32" version="\"1.14.13 (src:devbuild; feat:627291041)\""

// Node automatically restarted via systemd configuration
[2023-02-01T10:59:36.027864253Z INFO  solana_validator] Starting validator with: ArgsOs {

// Replay already held ledger, still computes incorrect hash
[2023-02-01T11:04:21.735361710Z INFO  solana_ledger::blockstore_processor] Processing ledger from slot 175475670...
[2023-02-01T11:04:21.735478611Z INFO  solana_ledger::blockstore_processor] ledger holds data through slot 175475904
...
[2023-02-01T11:05:33.756040299Z INFO  solana_runtime::bank] bank frozen: 175475896
hash: 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA accounts_delta: 7n8XBwGB11PrkkDtWfjeTuXsy549u6sj3BjtZi7MXyd signature_count: 5451 last_blockhash: 5iXEeC4g2kxhBQdJxguQNneqriXjBLhgsaMzcUpCnrkg capitalization: 539871054781159143
...
[2023-02-01T11:05:35.287769996Z INFO  solana_ledger::blockstore_processor] ledger processed in 1 minute, 13 seconds, 551 ms, 485 µs and 595 ns. root slot is 175475866, 37 banks: 175475866, 175475867, 175475868, 175475869, 175475870, 175475871, 175475872, 175475873, 175475874, 175475875, 175475876, 175475877, 175475878, 175475879, 175475880, 175475881, 175475882, 175475883, 175475884, 175475885, 175475886, 175475887, 175475888, 175475889, 175475890, 175475891, 175475892, 175475893, 175475894, 175475895, 175475896, 175475897, 175475899, 175475901, 175475902, 175475903, 175475904


// Get stuck in replay/check/purge/repair loop on a new slot until I killed the node
[2023-02-01T11:08:25.379514157Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175476569
with hash H3g7BUs55CVw1AYBYik6omAJ3y3g9aVswa623mQMf4u9,
but our version has hash 6jVmiDqzzgbrewWG4ey1GWoeRRm2k48gozXyZzmZdnhj
...
[2023-02-01T11:08:26.837206955Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175476569
with hash H3g7BUs55CVw1AYBYik6omAJ3y3g9aVswa623mQMf4u9,
but our version has hash 6jVmiDqzzgbrewWG4ey1GWoeRRm2k48gozXyZzmZdnhj
...
```
vs. the v1.15 / master logs:
```
// Detect that we differ from the cluster
[2023-02-01T10:59:26.190250593Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175475896
with hash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY,
but our version has hash 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA

// Attempt to purge/repair/replay/check 10 times
[2023-02-01T10:59:27.767082656Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175475896
with hash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY,
but our version has hash 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA
...
[2023-02-01T10:59:42.795659863Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175475896
with hash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY,
but our version has hash 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA

// Encounter the new-to-v1.15 panic that bails out of retry loop
thread 'solReplayStage' panicked at 'We have tried to repair duplicate slot: 175475896 more than 10 times and are unable to freeze a block with bankhash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY, instead we have a block with bankhash Some(9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', core/src/replay_stage.rs:1252:25
             at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
[2023-02-01T10:59:42.889806014Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i
message="panicked at 'We have tried to repair duplicate slot: 175475896 more than 10 times and are unable to freeze a block with bankhash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY, instead we have a block with bankhash Some(9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', core/src/replay_stage.rs:1252:25" location="core/src/replay_stage.rs:1252:25" version="1.15.0 (src:00000000; feat:1218305229, client:SolanaLabs)"

// Node automatically restarts via systemd configuration
[2023-02-01T10:59:36.027864253Z INFO  solana_validator] Starting validator with: ArgsOs {

// Replay already held ledger, still computes incorrect hash
[2023-02-01T11:04:29.784250539Z INFO  solana_ledger::blockstore_processor] Processing ledger from slot 175475782...
[2023-02-01T11:04:29.784719551Z INFO  solana_ledger::blockstore_processor] ledger holds data through slot 175475943
...
[2023-02-01T11:05:17.923220765Z INFO  solana_runtime::bank] bank frozen: 175475896
hash: 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA accounts_delta: 7n8XBwGB11PrkkDtWfjeTuXsy549u6sj3BjtZi7MXyd signature_count: 5451 last_blockhash: 5iXEeC4g2kxhBQdJxguQNneqriXjBLhgsaMzcUpCnrkg capitalization: 539871054781159143, stats: BankHashStats { num_updated_accounts: 11554, num_removed_accounts: 15, num_lamports_stored: 2302459823051189, total_data_len: 16173352, num_executable_accounts: 0 }
...
[2023-02-01T11:05:33.963619601Z INFO  solana_ledger::blockstore_processor] ledger processed in 1 minute, 4 seconds, 176 ms, 274 µs and 344 ns. root slot is 175475869, 69 banks: 175475869, 175475870, 175475871, 175475872, 175475873, 175475874, 175475875, 175475876, 175475877, 175475878, 175475879, 175475880, 175475881, 175475882, 175475883, 175475884, 175475885, 175475886, 175475887, 175475888, 175475889, 175475890, 175475891, 175475892, 175475893, 175475894, 175475895, 175475896, 175475897, 175475899, 175475901, 175475902, 175475903, 175475904, 175475905, 175475906, 175475907, 175475908, 175475909, 175475910, 175475911, 175475912, 175475913, 175475914, 175475915, 175475916, 175475917, 175475918, 175475919, 175475920, 175475921, 175475922, 175475923, 175475924, 175475925, 175475926, 175475927, 175475928, 175475929, 175475930, 175475931, 175475932, 175475933, 175475934, 175475935, 175475940, 175475941, 175475942, 175475943

// Do replay/check/purge/repair loop until we encounter same panic
[2023-02-01T11:08:44.853077789Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175476569
with hash H3g7BUs55CVw1AYBYik6omAJ3y3g9aVswa623mQMf4u9,
but our version has hash 6jVmiDqzzgbrewWG4ey1GWoeRRm2k48gozXyZzmZdnhj
[2023-02-01T11:09:00.884109849Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i message="panicked at 'We have tried to repair duplicate slot: 175476569 more than 10 times and are unable to freeze a block with bankhash H3g7BUs55CVw1AYBYik6omAJ3y3g9aVswa623mQMf4u9, instead we have a block with bankhash Some(6jVmiDqzzgbrewWG4ey1GWoeRRm2k48gozXyZzmZdnhj). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', core/src/replay_stage.rs:1252:25" location="core/src/replay_stage.rs:1252:25" version="1.15.0 (src:00000000; feat:1218305229, client:SolanaLabs)"

// Repeat above of restart, replay local ledger, get stuck on some new, later slot until I killed node
...
[2023-02-01T11:26:52.899767686Z WARN  solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 175478133
with hash AcU2WGVLvd494g9wCAGapZe2At7bBV5hMRxxqYXxf782,
but our version has hash 4Zwda4T3Vv289KU6oGYagLdm4g2MJ5y2hbGCCtHoLMZf
```

Takeaways:
- For the sake of v1.14, I agree with Behzad
    - This ProgressMap panic was useful because it caused a louder failure faster when we diverged on consensus
    - But, if the ProgressMap panic could be encountered in a legit scenario, panic not good
- For the sake of v1.15+, the ProgressMap panic doesn't seem to occur anymore. However, we have a new, more explicit TooManyRetry panic that more clearly states what is wrong. This is good.
- In both cases, the behavior of getting stuck in purge/repair/replay/check loop on different slot(s) is a bit undesirable given that it masks the initial failure (ie these are a byproduct of first failure)
    - I guess this is due to the divergent slot getting replayed via `ReplayStage` the first time, but getting replayed via `blockstore_processor::process_blockstore_from_root()` on system reboots. In this latter case, the node isn't fully up yet and won't be checking bank against the cluster.
    - If nodes happen to have something like systemd to auto-restart validator process, even with the new TooManyRetry panic in v1.15, a divergent node will continue to repair slots until the node is corrected
        - At least the restart that takes multiple minutes in essence rate limits this
        - I'm not sure if there would be anything to do here aside from making sure that nodes can't be abused too heavily via repair (this probably already exists, I'm just not the most as familiar with this aspect of codebase)
