### ISSUE TITLE
Thread 'solReplayStage' panic

### ISSUE THREAD

**Issue by harshsingh-cs** [solana-labs/solana#32273]
#### Problem
Facing panic errors on solana devnet 
```
thread 'solReplayStage' panicked at 'We have tried to repair duplicate slot: 225076776 more than 10 times and are unable to freeze a block with bankhash 6RmHDmkQh9BrSnuRkuYK7qjDMFZDVgnmh8AtW1VvMaGA, instead we have a block with bankhash Some(BPgSFsDeF55C7Hdt5hm3wkzexmfpdJStSr9EbbvJe1rz). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', core/src/replay_stage.rs:1239:25
stack backtrace:
   0:     0x5645a259dcbd - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5645a259dcbd - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5645a259dcbd - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5645a259dcbd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5645a25c610c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x5645a2594538 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x5645a25a0307 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5645a25a0307 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5645a25a0307 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x5645a259ffd0 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x5645a1f64f30 - solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}::hb3e823cbdaa04294
  11:     0x5645a25a0a94 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  12:     0x5645a25a0747 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  13:     0x5645a259e184 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x5645a25a0459 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  15:     0x5645a082bd73 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  16:     0x5645a0b08e7d - hashbrown::map::HashMap<K,V,S,A>::retain::hc92d8e1fb90fb932
  17:     0x5645a0c36534 - solana_core::replay_stage::ReplayStage::dump_then_repair_correct_slots::hc10b24d69269672d
  18:     0x5645a0bb2882 - solana_core::replay_stage::ReplayStage::new::{{closure}}::hd0f1172b8aa6934d
  19:     0x5645a0bcb734 - std::sys_common::backtrace::__rust_begin_short_backtrace::he094ba635f5eeb22
  20:     0x5645a0af724d - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc1e1a1c41de0358b
  21:     0x5645a25a6613 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  22:     0x5645a25a6613 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  23:     0x5645a25a6613 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  24:     0x7fe165fe0ea7 - start_thread
  25:     0x7fe165d96a2f - clone
  26:                0x0 - <unknown>
[2023-06-24T21:06:59.411375321Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i message="panicked at 'We have tried to repair duplicate slot: 225076776 more than 10 times and are unable to freeze a block with bankhash 6RmHDmkQh9BrSnuRkuYK7qjDMFZDVgnmh8AtW1VvMaGA, instead we have a block with bankhash Some(BPgSFsDeF55C7Hdt5hm3wkzexmfpdJStSr9EbbvJe1rz). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', core/src/replay_stage.rs:1239:25" location="core/src/replay_stage.rs:1239:25" version="\"1.14.17 (src:b29a37cf; feat:3488713414)\""
``` 

solana devnet - 1.14.17

**Comment by steviez** [comment]
`v1.14.17` is too old for devnet. It was announced > 2 weeks ago that feature activations would resume on devnet:
https://discord.com/channels/428295358100013066/749059399875690557/1115680677514461205.

Namely, the feature `Bj2jmUsM2iRhfdLLDSTkhM5UQRQvQHm57HSmPibPtEyu` was activated, which requires v1.14.18:
```
$ solana feature status -u devent
Feature                                      | Status                  | Activation Slot | Description
...
Bj2jmUsM2iRhfdLLDSTkhM5UQRQvQHm57HSmPibPtEyu | active since epoch 521  | 225072000       | Return InsufficientDelegation instead of InsufficientFunds or InsufficientStake where applicable #31206
```

That being said, we do not offer support on GitHub. Instead, you should join us on Discord, and especially pay attention to announcement channels. The announcement have messages about when validators will be required to upgrade their version.
https://solana.com/discord
