### ISSUE TITLE
Program failed to complete: Instruction passed to inner instruction is too large (12884933924 > 1280)

### ISSUE THREAD

**Issue by JamesW940516** [solana-labs/solana#32569]
#### Problem

Current Solana Version 1.16.4
Anchor Version 0.25.0
Smart Contract Deploy and Build succeed.
When I call the Smart Contract function, an error comes out.

SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/home/test4/node_modules/@solana/web3.js/src/connection.ts:5922:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/test4/node_modules/@solana/web3.js/src/connection.ts:5881:20)
    at async sendAndConfirmRawTransaction (/home/test4/node_modules/@project-serum/anchor/src/provider.ts:288:21)
    at async AnchorProvider.sendAndConfirm (/home/test4/node_modules/@project-serum/anchor/src/provider.ts:148:14)
    at async MethodsBuilder.rpc [as _rpcFn] (/home/test4/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:29:16) {
  logs: [
    'Program PdJWNJVtSMToEVBoXjqHCC8sysMC1D5f6uCwxLfXYHg invoke [1]',
    'Program log: Instruction: Initialize',
    'Program PdJWNJVtSMToEVBoXjqHCC8sysMC1D5f6uCwxLfXYHg consumed 9100 of 200000 compute units',
    'Program failed to complete: Instruction passed to inner instruction is too large (12884933924 > 1280)',
    'Program PdJWNJVtSMToEVBoXjqHCC8sysMC1D5f6uCwxLfXYHg failed: Program failed to complete'
  ],
  programErrorStack: ProgramErrorStack {
    stack: [
      [PublicKey [PublicKey(PdJWNJVtSMToEVBoXjqHCC8sysMC1D5f6uCwxLfXYHg)]]
    ]
  }
}

#### Proposed Solution

I think this is a kind of problem which comes from version crash or version crash between dependencies.

**Comment by steviez** [comment]
A quick glance at the Anchor repo indicates that Anchor 0.25.0 is using solana v1.10.x dependencies:
https://github.com/coral-xyz/anchor/blob/v0.25.0/client/Cargo.toml#L19

So yes, you will need to get your versions in sync (ie use the solana version that tagged anchor version is using)

As a more general note, we do not use this GitHub for developer support. Incase you were unaware, you should check out:
https://solana.stackexchange.com/
