### ISSUE TITLE
Validator version 1.16.13 JITO assert at core/src/unprocessed_transaction_storage.rs:819:9

### ISSUE THREAD

**Issue by bji** [solana-labs/solana#33232]
#### Problem

Validator running 1.16.13 JITO crashed about half an hour ago.  Logs show this immediately preceeding the solana-validator process exit and systemctl restart of the service:

```
[2023-09-13T04:25:34.298200991Z INFO  solana_metrics::metrics] datapoint: qos-service-errors id=1i bank_slot=217248296i retried_txs_per_block_limit_count=0i retried_txs_per_vote_limit_count=0i r
etried_txs_per_account_limit_count=0i retried_txs_per_account_data_block_limit_count=0i dropped_txs_per_account_data_total_limit_count=0i
thread 'solBanknStgTx03' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', core/src/unprocessed_transaction_storage.rs:819:9
stack backtrace:
[2023-09-13T04:25:34.311850899Z INFO  solana_metrics::metrics] datapoint: qos-service-stats id=2i bank_slot=217248296i compute_cost_time=233i compute_cost_count=668i cost_tracking_time=280i sele
cted_txs_count=615i estimated_signature_cu=442800i estimated_write_lock_cu=669300i estimated_data_bytes_cu=16977i estimated_builtins_execute_cu=52050i estimated_bpf_execute_cu=139820000i actual_
bpf_execute_cu=859870i actual_execute_time_us=11069i
[2023-09-13T04:25:34.311878121Z INFO  solana_metrics::metrics] datapoint: qos-service-errors id=2i bank_slot=217248296i retried_txs_per_block_limit_count=53i retried_txs_per_vote_limit_count=0i 
retried_txs_per_account_limit_count=0i retried_txs_per_account_data_block_limit_count=0i dropped_txs_per_account_data_total_limit_count=0i
[2023-09-13T04:25:34.325990535Z INFO  solana_metrics::metrics] datapoint: qos-service-stats id=5i bank_slot=217248296i compute_cost_time=309i compute_cost_count=759i cost_tracking_time=264i sele
cted_txs_count=752i estimated_signature_cu=542160i estimated_write_lock_cu=856200i estimated_data_bytes_cu=18256i estimated_builtins_execute_cu=46950i estimated_bpf_execute_cu=186150000i actual_
bpf_execute_cu=2323406i actual_execute_time_us=26054i
[2023-09-13T04:25:34.326031883Z INFO  solana_metrics::metrics] datapoint: qos-service-errors id=5i bank_slot=217248296i retried_txs_per_block_limit_count=7i retried_txs_per_vote_limit_count=0i r
etried_txs_per_account_limit_count=0i retried_txs_per_account_data_block_limit_count=0i dropped_txs_per_account_data_total_limit_count=0i
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: solana_core::unprocessed_transaction_storage::UnprocessedTransactionStorage::process_packets
   5: solana_core::banking_stage::consumer::Consumer::consume_buffered_packets
   6: solana_core::banking_stage::BankingStage::process_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-09-13T04:25:34.366116768Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solBanknStgTx03" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `0`,
     right: `1`', core/src/unprocessed_transaction_storage.rs:819:9" location="core/src/unprocessed_transaction_storage.rs:819:9" version="1.16.13 (src:00000000; feat:3949673676, client:JitoLabs)"
```

**Comment by bji** [comment]
NOTE: I have compared this file between JITO and non-JITO versions.  The file is different in the JITO version.  This may be an issue caused by JITO changes.

**Comment by bji** [comment]
Definitely this is a JITO issue as the assert is in their modifications.  I have created an issue on JITO github for this:

https://github.com/jito-foundation/jito-solana/issues/373

I am closing this issue here because I believe it should be handled by JITO.

**Comment by bji** [comment]
Sorry I was confused - the function is not newly added by JITO.  It's just that the function moved within the file due to JITO additions above it.  That confused me due to line numbers and I thought that it was a function added by JITO.  I am re-opening this issue.

**Comment by michaelh-laine** [comment]
```[2023-09-13T04:50:28.910250955Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solBanknStgTx05" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `21`,
     right: `22`', core/src/unprocessed_transaction_storage.rs:819:9" location="core/src/unprocessed_transaction_storage.rs:819:9" version="1.16.12 (src:00000000; feat:3949673676, client:JitoLabs)"```
     
     Hit it 3x in under an hour here in jito-solana v1.16.12, moving to Labs client right now

**Comment by bji** [comment]
Here are 10,000 lines of my logs preceeding the restart:

[log.txt](https://github.com/solana-labs/solana/files/12593681/log.txt)

**Comment by bji** [comment]
To be clear here is the code that crashed; it's at a different line number in the stock validator code:

```rust

    /// Verify that the priority queue and map are consistent and that original capacity is maintained.
    fn verify_priority_queue(&self, original_capacity: usize) {
        // Assert unprocessed queue is still consistent and maintains original capacity
        assert_eq!(
            self.unprocessed_packet_batches
                .packet_priority_queue
                .capacity(),
            original_capacity
        );
        assert_eq!(
            self.unprocessed_packet_batches.packet_priority_queue.len(),
            self.unprocessed_packet_batches
                .message_hash_to_transaction
                .len()
        );
    }
```

It was the second assert_eq! that crashed.

**Comment by michaelh-laine** [comment]
[Uploading assert_panic_1.log…]()

Here's my logs surrounding the first panic (of 3)

**Comment by bji** [comment]
Sorry to have created such confusion but buffalu at JITO confirms that this *IS* a JITO specific crash, caused by something that they forgot to do in 1.16 that they were doing in 1.14.  I will leave this open but request that Solana Labs close it after review.  Thanks.

**Comment by mvines** [comment]
Looks like no action required here as this was a jito bug
