### ISSUE TITLE
process_ledger_simple failing

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#3921]
#### Problem
observed failure of test_process_ledger_simple

```
[rwalker@ip-172-30-0-159 solana]$ RUST_BACKTRACE=full cargo test --manifest-path core/Cargo.toml process_ledger_simple -- --nocapture --test-threads 1
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running target/debug/deps/solana-a183764a73efda3a

running 1 test
test blocktree_processor::tests::test_process_ledger_simple ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LedgerVerificationFailed', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x55e8af9b0b23 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd71462e61ec5c76e
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55e8af9ab39b - std::sys_common::backtrace::_print::hae2106692f421f30
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x55e8af9ae606 - std::panicking::default_hook::{{closure}}::h4e372307f318ae92
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x55e8af9ae384 - std::panicking::default_hook::hb6f777c87029e950
                               at src/libstd/panicking.rs:215
   4:     0x55e8af9aed0f - std::panicking::rust_panic_with_hook::h49d43efebcb63d45
                               at src/libstd/panicking.rs:478
   5:     0x55e8af9ae891 - std::panicking::continue_panic_fmt::h87cb4de2c26b0fa7
                               at src/libstd/panicking.rs:385
   6:     0x55e8af9ae775 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   7:     0x55e8af9ccc7c - core::panicking::panic_fmt::h472d766e4dff71a2
                               at src/libcore/panicking.rs:85
   8:     0x55e8ae26e548 - core::result::unwrap_failed::hcd7ba4c5472c663c
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/macros.rs:17
   9:     0x55e8ae2551db - <core::result::Result<T, E>>::unwrap::hd6ab05508151c03f
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:798
  10:     0x55e8ae459d80 - solana::blocktree_processor::tests::test_process_ledger_simple::h297159e581358c37
                               at core/src/blocktree_processor.rs:550
  11:     0x55e8adefd389 - solana::blocktree_processor::tests::test_process_ledger_simple::{{closure}}::h054ab33301c1e127
                               at core/src/blocktree_processor.rs:502
  12:     0x55e8ade80bfd - core::ops::function::FnOnce::call_once::h6705309ac5e16ec6
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/ops/function.rs:231
  13:     0x55e8ae5ffe2e - <F as alloc::boxed::FnBox<A>>::call_box::hfbd4c212fba9fc44
                               at src/libtest/lib.rs:1497
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/ops/function.rs:231
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/liballoc/boxed.rs:749
  14:     0x55e8af9b8d29 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  15:     0x55e8ae61cf37 - test::run_test::run_test_inner::{{closure}}::hcc6f0e4297f8f095
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
                               at src/libtest/lib.rs:1452
  16:     0x55e8ae61c85c - test::run_test::run_test_inner::h168d3da694d78c7b
                               at src/libtest/lib.rs:1474
  17:     0x55e8ae61afdf - test::run_test::he560aaf799e77ab1
                               at src/libtest/lib.rs:1493
  18:     0x55e8ae613b08 - test::run_tests_console::h50c0882d75e0f844
                               at src/libtest/lib.rs:1156
                               at src/libtest/lib.rs:961
  19:     0x55e8ae60b6d7 - test::test_main::h92fd1d6423bf4360
                               at src/libtest/lib.rs:293
  20:     0x55e8ae60bf03 - test::test_main_static::hdb803077e0fae811
                               at src/libtest/lib.rs:327
  21:     0x55e8ae58b455 - solana::main::ha2904028831fa809
  22:     0x55e8ade1d81f - std::rt::lang_start::{{closure}}::h3fd4f9bf3c26ec1e
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  23:     0x55e8af9ae712 - std::panicking::try::do_call::hf75bca0b71ecc6e0
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:297
  24:     0x55e8af9b8d29 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  25:     0x55e8af9af2dc - std::rt::lang_start_internal::h5a74da15a365d5aa
                               at src/libstd/panicking.rs:276
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  26:     0x55e8ade1d7f8 - std::rt::lang_start::hc49cf7e71dac92ad
                               at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  27:     0x55e8ae58b489 - main
  28:     0x7f7307aed029 - __libc_start_main
  29:     0x55e8add25129 - _start
  30:                0x0 - <unknown>
FAILED

failures:

failures:
    blocktree_processor::tests::test_process_ledger_simple
```

#### Proposed Solution
diagnose and fix

**Comment by rob-solana** [comment]
@aeyakovenko 
```
running 1 test
test blocktree_processor::tests::test_process_ledger_simple ... [2019-04-22T18:44:29.416161324Z INFO  solana::blocktree_processor] processing ledger...
[2019-04-22T18:44:29.427472876Z WARN  solana::blocktree_processor] Failed to process entries for slot 1: AccountNotFound
thread 'main' panicked at 'process_blocktree(): LedgerVerificationFailed', src/libcore/result.rs:997:5
stack backtrace:
```
looks like you have introduced a new bug in accounts
