### ISSUE TITLE
locktower.rs: thread 'solana-replay-stage' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4853]
##### STR:
On the v0.16 branch, 
1. Run `cargo build --release`
1. Run `./multinode-demo/clear-config.sh`
2. Run `NDEBUG=1 ./multinode-demo/validator.sh testnet.solana.com`
3. Wait for the validator to catch up the network (confirm block height at http://testnet.solana.com)
4. ^C
5. Run `NDEBUG=1 ./multinode-demo/validator.sh testnet.solana.com` again

--------

```
thread 'solana-replay-stage' panicked at 'assertion failed: `(left == right)`
  left: `Some(14385)`,
 right: `Some(14306)`', core/src/locktower.rs:187:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   8: solana::locktower::Locktower::collect_vote_lockouts
   9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  11: solana::replay_stage::ReplayStage::generate_votable_banks
```

**Comment by rob-solana** [comment]
does the validator start from a snapshot in this case?  if so, what happens when that's disabled?

**Comment by mvines** [comment]
Yes it starts from a snapshot.

**Comment by mvines** [comment]
Weird, I can't reproduce today with the given STR

**Comment by mvines** [comment]
Unable to reproduce now 🤷‍♂
