### ISSUE TITLE
`solana-validator-info get` UX feels a little awkward to use

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5120]
### Attempt 1
```bash
$ solana-validator-info get --all
[("GRUP8YUGASLdu2gBwHstFgeVH28qppfuCaTzq5Yo7wRo", Account { lamports: 1 data.len: 257 owner: Config1111111111111111111111111111111111111 executable: false data: 00382a2d5d000000006a0000000000000068747470733a2f2f6769746875622e636f6d2f736f6c616e612d6c6162732f736f6c616e612f72656c65617365732f }), ("FnKt2ES9iUJkjoprf2rL62xxBAxZLVgyA4SFexPGotFE", Account { lamports: 1 data.len: 257 owner: Config1111111111111111111111111111111111111 executable: false data: 002c2a2d5d000000006f0000000000000068747470733a2f2f6769746875622e636f6d2f736f6c616e612d6c6162732f736f6c616e612f72656c65617365732f })]
```

1. It's not really obvious what I'm looking at.  The config account itself is not decoded and it's all on one line
2. `--all` feels a little weird.  Perhaps replace `--all` with `solana-validator-info  get` with no further arguments?

### Attempt 2
```
$ solana-validator-info get GRUP8YUGASLdu2gBwHstFgeVH28qppfuCaTzq5Yo7wRo
error: Found argument 'GRUP8YUGASLdu2gBwHstFgeVH28qppfuCaTzq5Yo7wRo' which wasn't expected, or isn't valid in this context

USAGE:
    solana-validator-info get [FLAGS] [OPTIONS] --all --info-pubkey <PUBKEY>

For more information try --help
```

Oof, I was sorta expecting that to work :)

### Attempt 3
```bash
$ RUST_BACKTRACE=1 solana-validator-info  get --info-pubkey GRUP8YUGASLdu2gBwHstFgeVH28qppfuCaTzq5Yo7wRo
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1', /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2686:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: solana_validator_info::parse_validator_info
  10: solana_validator_info::main
```

Ack!
1. `panic!` obviously...
2.  That `--info-pubkey` is pretty hard to type, I like attempt 2's syntax much more!

**Comment by mvines** [comment]
@CriesofCarrots hey I think tuning the `solana-validator-info publish` slightly would be of benefit too, since --name/--validator-keypair are mandatory should we make them positional parameters?

eg:
```
$ solana-validator-info publish [OPTIONS] <KEYPAIR_PATH> <NAME_STRING> 
```

**Comment by CriesofCarrots** [comment]
That ugly data presentation and panic is all because `GRUP8YUGASLdu2gBwHstFgeVH28qppfuCaTzq5Yo7wRo` is not a properly configured ValidatorInfo account (but some other Config account). Adding fixes for empty handling!
I totally agree about the `get` argument syntax. I'll PR those fixes together, and then give a thought to the `publish` argument syntax to PR separately.
