### ISSUE TITLE
solana-broadcaster: solana::weighted_shuffle::weighted_shuffle panics

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5148]
STR:
1) Start the TdS cluster
2) Let it run for a minute or two
3) Observe a panic on the bootstrap leader node:

```
thread 'solana-broadcaster' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: rust_begin_unwind
             at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::panicking::panic
             at src/libcore/panicking.rs:49
  10: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  12: solana::weighted_shuffle::weighted_shuffle
  13: solana::cluster_info::ClusterInfo::stake_weighted_shuffle
  14: solana::cluster_info::ClusterInfo::sorted_tvu_peers
  15: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  16: solana::cluster_info::ClusterInfo::broadcast
  17: <solana::broadcast_stage::standard_broadcast_run::StandardBroadcastRun as solana::broadcast_stage::BroadcastRun>::run
  18: solana::broadcast_stage::BroadcastStage::run
```

**Comment by mvines** [comment]
I see a bunch of downcasts to u32 and u16 around here: https://github.com/solana-labs/solana/blob/7aad4275110ed6b1d3071802d49dbb8b5abee3eb/core/src/weighted_shuffle.rs#L20

I bet that's not playing nice with the larger stakes at https://github.com/solana-labs/tour-de-sol/blob/master/stage1/validator.yml#L2-L8

**Comment by sagar-solana** [comment]
So it crashes if total_stake/some1s_stake > u32::max. 

The problem I'm trying to fix right now overflowing in https://github.com/solana-labs/solana/blob/7aad4275110ed6b1d3071802d49dbb8b5abee3eb/core/src/weighted_shuffle.rs#L15

It seems to silently overflow which is bad. 
Basically the sum of all input cannot be greater than T::max and there needs to be a check for that. ideas?
