### ISSUE TITLE
Re-enable failing banking benches

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#5351]
#### Problem

https://github.com/solana-labs/solana/pull/5347 disabled benches: bench_bank_sync_process_builtin_transactions and friends.

Because they crash in CI intermittently with an `unwrap()` in `bank::process_transactions`

#### Proposed Solution

Debug and re-enabled with fix.

**Comment by sakridge** [comment]
Failure:
https://buildkite.com/solana-labs/solana/builds/9824#7c3bd9f7-f3ec-467d-a1cd-cd460902c2d8

**Comment by sakridge** [comment]
```

{ "type": "test", "event": "started", "name": "bench_bank_async_process_builtin_transactions" }
--
  | thread 'solana-bank-client' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
  | stack backtrace:
  | 0: backtrace::backtrace::libunwind::trace
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
  | 1: backtrace::backtrace::trace_unsynchronized
  | at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
  | 2: std::sys_common::backtrace::_print
  | at src/libstd/sys_common/backtrace.rs:47
  | 3: std::sys_common::backtrace::print
  | at src/libstd/sys_common/backtrace.rs:36
  | 4: std::panicking::default_hook::{{closure}}
  | at src/libstd/panicking.rs:200
  | 5: std::panicking::default_hook
  | at src/libstd/panicking.rs:214
  | 6: std::panicking::rust_panic_with_hook
  | at src/libstd/panicking.rs:477
  | 7: std::panicking::continue_panic_fmt
  | at src/libstd/panicking.rs:384
  | 8: rust_begin_unwind
  | at src/libstd/panicking.rs:311
  | 9: core::panicking::panic_fmt
  | at src/libcore/panicking.rs:85
  | 10: core::panicking::panic
  | at src/libcore/panicking.rs:49
  | 11: solana_runtime::bank::Bank::process_transaction
  | 12: solana_runtime::bank_client::BankClient::run
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
