### ISSUE TITLE
Snapshot file size is limited to 32bits (Snapshot packager crash)

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#5411]
#### Problem

```
[2019-08-02T07:37:48.943843352Z INFO  solana::replay_stage] @1564731468943 tower duration: 13 len: 1 weights: [631360189572]
[2019-08-02T07:37:49.056477672Z INFO  solana::poh_recorder] reset poh from: 5cZyrSBrncf1vr4QFAz5xHq9NyhnUVzjhSPyVVnqSiYa,1378
7,3446 to: 7h2hCkdpCT3gWpWM1YjNRYmkuFYHaT62n54FfHiqDXyc,3446
[2019-08-02T07:37:49.057016622Z INFO  solana::replay_stage] 7XsVeUa3vAwSa1hRGGtJVqAVMg1d8JEs584kM931mo1R voted and reset poh
at 13787. My next leader slot is #3447
[2019-08-02T07:37:49.558281536Z INFO  solana::poh_recorder] poh_record: max_tick_height 13791 reached, clearing working_bank
3447
[2019-08-02T07:37:49.604592144Z INFO  solana::replay_stage] bank frozen 3447
[2019-08-02T07:37:49.618039438Z INFO  solana::replay_stage] @1564731469618 tower duration: 13 len: 1 weights: [631360189572]
[2019-08-02T07:37:49.690476928Z INFO  solana::poh_recorder] reset poh from: 5NC3zQtK45z4arPUuP2Ex4cfcGUe8SkyBBigo2xP68g9,1379
1,3447 to: Cvhm22UE8RZW7wTw8BcRrqTZTxMeRyRwj9WGE57AYEdg,3447
[2019-08-02T07:37:49.690726907Z INFO  solana::replay_stage] 7XsVeUa3vAwSa1hRGGtJVqAVMg1d8JEs584kM931mo1R voted and reset poh
at 13791. My next leader slot is #3448
thread 'solana-snapshot-packager' panicked at 'attempt to add with overflow', /root/.cargo/registry/src/github.com-1ecc6299db
9ec823/miniz_oxide-0.3.0/src/deflate/core.rs:1547:31
[2019-08-02T07:37:50.318787126Z INFO  solana::poh_recorder] poh_record: max_tick_height 13795 reached, clearing working_bank
3448
[2019-08-02T07:37:50.321122256Z INFO  solana::broadcast_stage::standard_broadcast_run] broadcast: entries: [1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] blob times ms: [3, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1] broadcast times ms: [3, 2, 2,
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2]
[2019-08-02T07:37:50.364073031Z INFO  solana::replay_stage] bank frozen 3448
[2019-08-02T07:37:50.374822387Z INFO  solana::replay_stage] @1564731470374 tower duration: 10 len: 1 weights: [631360189572]
[2019-08-02T07:37:50.424473920Z INFO  solana::poh_recorder] reset poh from: 3jnK4H9PLSQynMTwaaBPXBSUmzmHg8VZo762TYvk1knR,1379
5,3448 to: HtmrZHhnzhrbxQze83nGpTJriNtnLnL6FQeqMeJGvfm,3448
[2019-08-02T07:37:50.424630729Z INFO  solana::replay_stage] 7XsVeUa3vAwSa1hRGGtJVqAVMg1d8JEs584kM931mo1R voted and reset poh
at 13795. My next leader slot is #3449
[2019-08-02T07:37:50.976453813Z INFO  solana::poh_recorder] poh_record: max_tick_height 13799 reached, clearing working_bank
3449
[2019-08-02T07:37:51.015161601Z INFO  solana::replay_stage] bank frozen 3449
[2019-08-02T07:37:51.022411125Z INFO  solana::replay_stage] @1564731471022 tower duration: 7 len: 1 weights: [631360189572]
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:718
   5: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
             at metrics/src/metrics.rs:423
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   8: rust_begin_unwind
             at src/libstd/panicking.rs:308
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: miniz_oxide::deflate::core::compress_normal
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.3.0/src/deflate/core.rs:1547
  12: miniz_oxide::deflate::core::compress_inner
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.3.0/src/deflate/core.rs:2013
  13: miniz_oxide::deflate::core::compress
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.3.0/src/deflate/core.rs:1955
  14: miniz_oxide_c_api::lib_oxide::mz_deflate_oxide
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide_c_api-0.2.3/src/lib_oxide.rs:442
  15: miniz_oxide_c_api::mz_deflate::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide_c_api-0.2.3/src/lib.rs:151
  16: core::ops::function::FnOnce::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  17: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
  18: std::panicking::try::do_call
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  20: std::panicking::try
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
  21: std::panic::catch_unwind
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
  22: miniz_oxide_c_api::mz_deflate
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide_c_api-0.2.3/src/lib.rs:147
  23: flate2::mem::Compress::compress
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/mem.rs:338
  24: flate2::mem::Compress::compress_vec
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/mem.rs:376
  25: <flate2::mem::Compress as flate2::zio::Ops>::run_vec
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:54
  26: flate2::zio::Writer<W,D>::write_with_status
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:217
  27: <flate2::zio::Writer<W,D> as std::io::Write>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:256
  28: <flate2::gz::write::GzEncoder<W> as std::io::Write>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/gz/write.rs:149
  29: std::io::Write::write_all
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/io/mod.rs:1208
  30: std::io::impls::<impl std::io::Write for &mut W>::write_all
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/io/impls.rs:57
  31: std::io::util::copy
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/io/util.rs:60
  32: tar::builder::append
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:358
  33: tar::builder::append_fs
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:497
  34: tar::builder::append_path_with_name
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:394
  35: tar::builder::Builder<W>::append_path_with_name
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:228
  36: solana::snapshot_package::SnapshotPackagerService::package_snapshots
             at core/src/snapshot_package.rs:110
  37: solana::snapshot_package::SnapshotPackagerService::new::{{closure}}
             at core/src/snapshot_package.rs:60
FATAL ERROR: Caught panic!
thread 'solana-snapshot-packager' panicked at 'called `Result::unwrap()` on an `Err` value: CompressError(())', src/libcore/r
esult.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::[2019-08-02T07:37:51.072472273Z INFO  solana::poh_recorder] reset poh from: 3RFPVLCpbqVjT
PPmT5HvCZnJi1PfngHDeibARZdkqQnt,13799,3449 to: 3vJwT9a4rH97jkd9d8ufuGdPA53KuRrTFF5xUfUxhy4Q,3449
{{[2019-08-02T07:37:51.072619575Z INFO  solana::replay_stage] 7XsVeUa3vAwSa1hRGGtJVqAVMg1d8JEs584kM931mo1R voted and reset po
h at 13799. My next leader slot is #3450
closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:718
   5: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
             at metrics/src/metrics.rs:423
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   8: rust_begin_unwind
             at src/libstd/panicking.rs:308
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  12: <flate2::mem::Compress as flate2::zio::Ops>::run_vec
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:54
  13: flate2::zio::Writer<W,D>::write_with_status
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:217
  14: <flate2::zio::Writer<W,D> as std::io::Write>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:256
  15: <flate2::gz::write::GzEncoder<W> as std::io::Write>::write
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/gz/write.rs:149
  16: std::io::Write::write_all
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/io/mod.rs:1208
  17: std::io::impls::<impl std::io::Write for &mut W>::write_all
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/io/impls.rs:57
  18: std::io::util::copy
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/io/util.rs:60
  19: tar::builder::append
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:358
  20: tar::builder::append_fs
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:497
  21: tar::builder::append_path_with_name
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:394
  22: tar::builder::Builder<W>::append_path_with_name
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:228
  23: solana::snapshot_package::SnapshotPackagerService::package_snapshots
             at core/src/snapshot_package.rs:110
  24: solana::snapshot_package::SnapshotPackagerService::new::{{closure}}
             at core/src/snapshot_package.rs:60
thread 'solana-snapshot-packager' panicked at 'unknown return code: -10000', /root/.cargo/registry/src/github.com-1ecc6299db9
ec823/flate2-1.0.9/src/mem.rs:350:18
stack backtrace:
   0:     0x560301057d73 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h6485381528590a55
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x560301051a7b - std::sys_common::backtrace::_print::h49a82ae9552e35c7
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x5603010557a6 - std::panicking::default_hook::{{closure}}::he20974adbefcc046
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x560301055539 - std::panicking::default_hook::he4af6af4ac7fef7b
                               at src/libstd/panicking.rs:211
   4:     0x560300454a2f - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h4148c34642b23613
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:718
   5:     0x56030044c76f - solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}::hd5046197dfc7e214
                               at metrics/src/metrics.rs:423
   6:     0x560301055f98 - std::panicking::rust_panic_with_hook::h057ff03eb4c8000f
                               at src/libstd/panicking.rs:478
   7:     0x560301055a31 - std::panicking::continue_panic_fmt::ha6d6ae144369025b
                               at src/libstd/panicking.rs:381
   8:     0x56030105597e - std::panicking::begin_panic_fmt::he54eae869ed71eb1
                               at src/libstd/panicking.rs:336
   9:     0x5603004863c2 - flate2::mem::Compress::compress::h6d6bde255f1f134c
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/mem.rs:350
  10:     0x56030048652c - flate2::mem::Compress::compress_vec::h9e42102ceedb50fb
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/mem.rs:376
  11:     0x560300486731 - <flate2::mem::Compress as flate2::zio::Ops>::run_vec::h8c8cbad7388baeea
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:54
  12:     0x5602ff8038a8 - flate2::zio::Writer<W,D>::write_with_status::hb49d8a17b2b2bb82
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:217
  13:     0x5602ff80364b - <flate2::zio::Writer<W,D> as std::io::Write>::write::h23ef9febfe1da48f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/zio.rs:256
  14:     0x5602ff8df760 - <flate2::gz::write::GzEncoder<W> as std::io::Write>::write::hd75ce116925bebba
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/gz/write.rs:149
  15:     0x5602ff8de21a - std::io::Write::write_all::hc30d59af0072612d
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/io/mod.rs:1208
  16:     0x5602ff48a24e - tar::builder::Builder<W>::finish::h580e1270687e5a1b
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:352
  17:     0x5602ff48a2b6 - <tar::builder::Builder<W> as core::ops::drop::Drop>::drop::hc333ece98bedb8ed
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.4.26/src/builder.rs:533
  18:     0x5602ff0f8e14 - core::ptr::real_drop_in_place::h21a8cc5c0e8bdf8c
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ptr.rs:195
  19:     0x5602ff550402 - solana::snapshot_package::SnapshotPackagerService::package_snapshots::hed1ef1d6435590ff
                               at core/src/snapshot_package.rs:119
  20:     0x5602ffadc9bc - solana::snapshot_package::SnapshotPackagerService::new::{{closure}}::h1bc2dcd8aab3dfc2
                               at core/src/snapshot_package.rs:60
  21:     0x5602ffa1ef47 - std::sys_common::backtrace::__rust_begin_short_backtrace::h35fe2ea368a11553
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/sys_common/backtrace.rs:136
  22:     0x5602ff685205 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h9f45aa2090fde0cd
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/mod.rs:470
  23:     0x5602ffa8f428 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7c360b87bf7a13ac
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:315
  24:     0x5602ffac2d91 - std::panicking::try::do_call::hee918746ad46e390
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:293
  25:     0x56030105fdb9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  26:     0x5602ffab99d2 - std::panicking::try::h6e43d4adbbbcbb94
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
  27:     0x5602ffa91208 - std::panic::catch_unwind::h5e4d24ba9a890370
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
  28:     0x5602ff680895 - std::thread::Builder::spawn_unchecked::{{closure}}::h62cb854e2f552308
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/thread/mod.rs:469
  29:     0x5602ff0eccb3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h53eb497e56145751
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  30:     0x5603010420ee - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  31:     0x56030105f0ff - std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
                               at src/libstd/sys_common/thread.rs:13
                               at src/libstd/sys/unix/thread.rs:79
  32:     0x7fcf696fedd4 - start_thread
  33:     0x7fcf6921202c - __clone
  34:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction
```

#### Proposed Solution

debug and fix.

**Comment by sakridge** [comment]
Repro with `dd if=/dev/urandom bs=194 > /dev/udp/127.0.0.1/<port>`

**Comment by aeyakovenko** [comment]
compiled from 911dee24c53f274b03281d91aaa5613b20cd7033

**Comment by mvines** [comment]
heh, nice.  Give `<port>`

**Comment by aeyakovenko** [comment]
@mvines Leo ran it on all the ports :)

**Comment by mvines** [comment]
Turns out this has nothing to do with the fuzzing.   The compression library we are using for snapshots has u32 assumptions in it, and panics on larger files.

**Comment by mvines** [comment]
This *maybe* has been fixed, we switched from gzip to bzip2 and the 32bit limit was in the gzip encoder.  🤞

**Comment by mvines** [comment]
(def fixed)
