### ISSUE TITLE
replay stage panic 'no entry found for key'

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#5568]
#### Problem

Panic seen in TDS run:

```
[2019-08-20T19:40:41.521585868Z INFO  solana::replay_stage] bank frozen 29812
[2019-08-20T19:40:46.446573527Z INFO  solana::cluster_info] RequestWindowIndex took: 6 ms
[2019-08-20T19:40:50.196069464Z INFO  solana::cluster_info] ReceiveUpdates took: 9 ms  len: 1
[2019-08-20T19:40:50.720417213Z INFO  solana::cluster_info] ReceiveUpdates took: 16 ms  len: 1
thread 'solana-replay-stage' panicked at 'no entry found for key', src/libcore/option.rs:1166:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   7: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   8: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   9: rust_begin_unwind
             at src/libstd/panicking.rs:311
  10: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  11: core::option::expect_failed
             at src/libcore/option.rs:1166
  12: solana::consensus::Tower::is_locked_out
  13: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  14: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  15: solana::replay_stage::ReplayStage::generate_votable_banks
```

Believe restarting the node after running for a while without resetting the ledger may be related to reproducing this case.

#### Proposed Solution

Debug and fix.

**Comment by mvines** [comment]
Ah I think I've seen this before as well.   When you restart a validator with a bunch of ledger, once blocktree_processor finishes loading the ledger and hands off to replay stage, the bank_forks doesn't have all the previous banks in it that locktower expects to find and this panic occurs

**Comment by carllin** [comment]
On startup, locktower is initialized with the vote state of the leader of the highest bank weight. This locktower stack may contain slots older than the local root due to varying voting behvaior between nodes. Should be addressed by https://github.com/solana-labs/solana/issues/4132
