### ISSUE TITLE
thread 'solana-window' panicked at 'assertion failed: `(left == right)`, core/src/blocktree.rs:1668:17

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5570]
tds-solana-com-bootstrap-leader panicked in the middle of TdS stage 0 dry run 3 with:

```
thread 'solana-window' panicked at 'assertion failed: `(left == right)`
  left: `28393`,
 right: `8934`', core/src/blocktree.rs:1668:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   8: solana::blocktree::handle_recovery
   9: solana::blocktree::Blocktree::write_shared_blobs
  10: solana::window_service::recv_window
thread 'main' panicked at 'validator exit: Any', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: rust_begin_unwind
             at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::result::unwrap_failed
  10: solana_validator::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start
```

Full log: [tds-solana-com-bootstrap-leader.log](https://drive.google.com/file/d/13S2s0GNsWf5Due1-LzRDeV3d6xGoGM-c/view?usp=sharing)

https://github.com/solana-labs/solana/blob/32de5e6e7ae62c96610cd3c8831710b7fa6a4a57/core/src/blocktree.rs#L1668

**Comment by mvines** [comment]
Observed on multiple DR3 nodes...

**Comment by rob-solana** [comment]
those assert!()s need to be errors, failures, and probably promoted to slashing offenses

**Comment by rob-solana** [comment]
was the slot being broadcast by the chorusone guys?

**Comment by mvines** [comment]
Observed on another validator during DR3: (looks the same as tds-solana-com-europe-west4-a-fullnode.log):
```
[2019-08-20T20:11:56.452501380Z WARN  solana::blocktree] [handle_recovery] failed verification at slot=8918, index=23, discarding
thread 'solana-window' panicked at 'assertion failed: `(left == right)`
  left: `48066`,
 right: `8918`', core/src/blocktree.rs:1668:17
```

**Comment by carllin** [comment]
From the combination of blocktree errors of this type: 

`Received last blob with index 109 >= slot.last_index 30` and what looks like 
the erasure corruption posted above, it seems a node has been retransmitting blobs for the same slot after a restart. 

Will remove the assert and make some changes to make erasure more robust
