### ISSUE TITLE
bootstrap-leader.sh panicked in the middle of bench-tps

### ISSUE THREAD

**Issue by winslyn** [solana-labs/solana#5764]
#### Problem

bootstrap-leader.sh panicked after client.sh finished allocating balances and while sending transactions to each other. 

Solana version v0.18.0

First Panic

```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:                                                                                                           
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39                                                          
1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71                                                                      
2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59                                                                                
at src/libstd/panicking.rs:197
   3: std::panicking::default_hook                                                                                                   
at src/libstd/panicking.rs:211
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook                                                                                           
at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt                                                                                             
at src/libstd/panicking.rs:381
   7: rust_begin_unwind                                                                                                             
 at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt                                                                                                     
at src/libcore/panicking.rs:85
   9: core::panicking::panic                                                                                                         
at src/libcore/panicking.rs:49
  10: <solana_core::broadcast_stage::standard_broadcast_run::StandardBroadcastRun as solana_core::broadcast_stage::BroadcastRun>::run
  11: solana_core::broadcast_stage::BroadcastStage::run
```

Second Panic

```
thread 'solana-broadcaster' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   7: rust_begin_unwind
             at src/libstd/panicking.rs:308
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::panicking::panic
             at src/libcore/panicking.rs:49
  10: <solana_core::broadcast_stage::standard_broadcast_run::StandardBroadcastRun as solana_core::broadcast_stage::BroadcastRun>::run
  11: solana_core::broadcast_stage::BroadcastStage::run
[2019-09-01T01:30:33.581503844Z INFO  solana_core::poh_recorder] poh_record: max_tick_height 4603 reached, clearing working_bank 1150
[2019-09-01T01:30:33.583373150Z INFO  solana_core::poh_recorder] WorkingBank::sender disconnected Err("SendError(..)")
[2019-09-01T01:31:17.461519026Z INFO  solana_core::snapshot_package] Successfully created tarball for root: 1100, elapsed ms: 53025
END OF BOOTSTRAP-LEADER.SH
```

**Comment by mvines** [comment]
No line number in `run()` :( but my money is on this unwrap: https://github.com/solana-labs/solana/blob/47535b9ff1d86617df3a77ef6e0e3f5c5bd08e06/core/src/broadcast_stage/standard_broadcast_run.rs#L112

wdyt @pgarg66?

**Comment by pgarg66** [comment]
It should not fail in deserialize there. All shreds are generated using the shredder. So, ideally it should be able to deserialize.
We can change unwrap to expect. It’ll be interesting if it’s failing there.

**Comment by mvines** [comment]
🤔 please re-open if this reproduces on 0.20.  This code has changed dramatically since 0.18
