### ISSUE TITLE
install gnuplot for criterion-plot 

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#599]
criterion-plot has a dependency on gnuplot for generation of its (very pretty) reports

CI and dev machines need to therefore have installed gnuplot before running "cargo bench" in our tree.

Without gnuplot installed, you get:
```
     Running `/home/rwalker/dev/rob-solana/solana/target/release/deps/bank-1c4e984a5222d651 --bench`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: criterion_plot::version
  10: <criterion::Criterion as core::default::Default>::default
  11: bank::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
error: bench failed
```

this is a known issue with criterion_plot, "documented" as a FIXME

**Comment by mvines** [comment]
Manually running `sudo apt-get install gnuplot` on the ci disk images now. 
cc: #570

**Comment by mvines** [comment]
Done, all CI instances now updated with gnuplot
