### ISSUE TITLE
validator:  thread 'solana-listen' panicked 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#652]
I've seen this crash a couple times from testnet validator logs, first time was totally by accident
(cc: #651)

```
2018-07-16T23:32:54Z solana.daemon-validator[9389]: thread 'solana-listen' panicked at 'assertion failed: `(left != right)`
2018-07-16T23:32:54Z solana.daemon-validator[9389]:   left: `V4(35.231.86.32:9004)`,
2018-07-16T23:32:54Z solana.daemon-validator[9389]:  right: `V4(35.231.86.32:9004)`', src/crdt.rs:1003:17
2018-07-16T23:32:55Z solana.daemon-validator[9389]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2018-07-16T23:32:55Z solana.daemon-validator[9389]: stack backtrace:
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
2018-07-16T23:32:55Z solana.daemon-validator[9389]:              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    1: std::sys_common::backtrace::print
2018-07-16T23:32:55Z solana.daemon-validator[9389]:              at libstd/sys_common/backtrace.rs:71
2018-07-16T23:32:55Z solana.daemon-validator[9389]:              at libstd/sys_common/backtrace.rs:59
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    2: std::panicking::default_hook::{{closure}}
2018-07-16T23:32:55Z solana.daemon-validator[9389]:              at libstd/panicking.rs:211
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    3: std::panicking::default_hook
2018-07-16T23:32:55Z solana.daemon-validator[9389]:              at libstd/panicking.rs:227
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    4: std::panicking::rust_panic_with_hook
2018-07-16T23:32:55Z solana.daemon-validator[9389]:              at libstd/panicking.rs:463
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    5: std::panicking::begin_panic_fmt
2018-07-16T23:32:55Z solana.daemon-validator[9389]:              at libstd/panicking.rs:350
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    6: solana::crdt::Crdt::handle_blob
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    7: <alloc::vec_deque::VecDeque<A> as core::iter::traits::FromIterator<A>>::from_iter
2018-07-16T23:32:55Z solana.daemon-validator[9389]:    8: solana::crdt::Crdt::run_listen
```

**Comment by mvines** [comment]
We're hitting this assert:
```rust
assert_ne!(from.contact_info.tvu_window, me.contact_info.tvu_window);
```
https://github.com/solana-labs/solana/blob/73ae3c3301805e0f5e643c8a3c081143dfe65235/src/crdt.rs#L1003

**Comment by mvines** [comment]
In the above backtrace, `35.231.86.32` is the public IP address of the validator that the crash occurred on

**Comment by aeyakovenko** [comment]
did a node restart under a different identity on the same port?

**Comment by mvines** [comment]
No I’m pretty sure that didn’t occur
