### ISSUE TITLE
Leader restart can see LedgerVerificationFailed message

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#706]
With the steps:
* Start leader
* send txes using client demo
* kill leader
* start leader

On the start sometimes I see:

```
 INFO 2018-07-19T17:38:59Z: solana::fullnode: creating bank...
 INFO 2018-07-19T17:38:59Z: solana::fullnode: processing ledger...
ERROR 2018-07-19T17:39:00Z: solana::ledger: entry invalid!: [42, 123, 148, 120, 232, 113, 29, 175, 214, 10, 72, 97, 129, 32, 146, 137, 216, 53, 82, 96, 43, 68, 147, 56, 83, 21, 75, 178, 143, 184, 64, 230] num txs: 157
ERROR 2018-07-19T17:39:00Z: solana::bank: Ledger proof of history failed at entry: 1488
thread 'main' panicked at 'process_ledger: LedgerVerificationFailed', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
```

Also I see there are many duplicate hashes at the end:
```
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
{"num_hashes":0,"id":[248,123,210,18,44,101,105,146,158,148,204,3,85,24,38,201,143,176,43,245,54,25,243,238,127,61,61,54,58,63,187,241]
```

**Comment by mvines** [comment]
This continues to reproduce with frequency on the testnets:
![image](https://user-images.githubusercontent.com/1281082/43700347-1d8735c8-9907-11e8-859f-1872a8cffddd.png)

But this issue is mostly on hold until the ledger format settles down.

**Comment by rob-solana** [comment]
in my most recent testing of this issue, a full multinode-demo run of:

1. setup
2. drone
3. leader
4. client
5. wait until leader looks quiet, kill leader with ^C
6. restart leader => panic on ledger entry 336 (out of 4350 entries in entire log)

**Comment by mvines** [comment]
This doesn't reproduce for me when I limit `bench-tps` to a single transmit thread (`--threads 1`), repros with `--threads 2` though

**Comment by mvines** [comment]
I think this is due to Entries from multiple concurrent transaction batches getting interleaved in the ledger.
