### ISSUE TITLE
thread 'main' panicked at 'Snapshot bank failed to verify'

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7117]
#6890 appears to still reproduce on the TdS testnet with the tip of master (d5beb8a9e4efcbee6fbd666b34938e8efffb6a43).

STR:
1. `solana-validator -l l -n tds.solana.com:8001 -o - `

Output:
```
[2019-11-25T16:34:12.115958676Z INFO  solana_core::validator] local retransmit address: 0.0.0.0:9757
[2019-11-25T16:34:12.115967876Z INFO  solana_core::validator] Initializing sigverify, this could take a while...
[2019-11-25T16:34:12.115977276Z INFO  solana_core::validator] Done.
[2019-11-25T16:34:12.115985377Z INFO  solana_core::validator] creating bank...
[2019-11-25T16:34:12.118331915Z INFO  solana_core::validator] genesis hash: H7zfo6f7NEYMCXfZnjvVbt565oZiw6hxFAguSCppvfFx
[2019-11-25T16:34:12.118488017Z INFO  solana_ledger::blocktree] Maximum open file descriptors: 65000
[2019-11-25T16:34:13.537219725Z INFO  solana_ledger::blocktree] "l/rocksdb" open running
[2019-11-25T16:34:13.538683149Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "l/snapshot"
[2019-11-25T16:34:13.538775250Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "l/snapshot.tar.bz2"
[2019-11-25T16:34:14.137411559Z INFO  solana_ledger::snapshot_utils] snapshot untar took 598ms
[2019-11-25T16:34:14.137592862Z INFO  solana_ledger::snapshot_utils] Loading from "/home/mvines/l/snapshot/.tmpfHPe5D/snapshots/425913/425913"
[2019-11-25T16:34:14.568162144Z INFO  solana_runtime::accounts_db] accounts_db: total_stores: 65 newest_slot: 425913 oldest_slot: 0 max_slot: 0 (num=7) min_slot: 356 (num=1)
[2019-11-25T16:34:14.568315247Z INFO  solana_metrics::metrics] datapoint: accounts_db-stores total_count=65i
thread 'main' panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:228:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[2019-11-25T16:34:14.570606184Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:228:9" location="ledger/src/snapshot_utils.rs:228:9"
```

**Comment by mvines** [comment]
When the TdS cluster goes down, here's now to reproduce:

1. Extract [ledger.zip](https://github.com/solana-labs/solana/files/3887700/ledger.zip)
2. Run `solana-validator -l ledger --no-genesis-fetch  --no-snapshot-fetch -o - -n edge.testnet.solana.com:8001`

**Comment by sakridge** [comment]
@mvines 

I get this with the ledger.zip:
Failed to load genesis from "ledger": Unable to open "ledger/genesis.bin": Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by mvines** [comment]
A better [ledger.zip](https://github.com/solana-labs/solana/files/3887777/ledger.zip)

**Comment by sakridge** [comment]
cc @ryoqun who can also take a look. This seems to be a hash mismatch in the bank.

**Comment by ryoqun** [comment]
oof. ;)

**Comment by ryoqun** [comment]
Curently, this is worked on https://github.com/solana-labs/solana/pull/7157
