### ISSUE TITLE
thread 'solana-replicate-stage' panicked at 'index 65488 out of range for slice of length 65472', libcore/slice/mod.rs:2256:5

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#752]
This panic has been observed on validators on the tip of `master`.    It seems to shutdown the validator and it stops voting

```
thread 'solana-replicate-stage' panicked at 'index 65488 out of range for slice of length 65472', libcore/slice/mod.rs:2256:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::slice::slice_index_len_fail
```

**Comment by mvines** [comment]
Here's an example of a validator log at the time of the panic:
[panic.log](https://github.com/solana-labs/solana/files/2226545/panic.log)
