### ISSUE TITLE
leader: thread 'solana-writer' panicked at 'assertion failed: pos < BLOB_DATA_SIZE', src/ledger.rs:47:13

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#756]
Observed on the tip of `master` testnet.
```
@400000005b58ad981d064664 thread 'solana-writer' panicked at 'assertion failed: pos < BLOB_DATA_SIZE', src/ledger.rs:47:13
@400000005b58ad982361ee14 stack backtrace:
@400000005b58ad982362a1c4    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
@400000005b58ad98253cd44c              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
@400000005b58ad98253cd44c    1: std::sys_common::backtrace::print
@400000005b58ad9825a5fa44              at libstd/sys_common/backtrace.rs:71
@400000005b58ad9825a71f3c              at libstd/sys_common/backtrace.rs:59
@400000005b58ad9825a75204    2: std::panicking::default_hook::{{closure}}
@400000005b58ad9825c482ac              at libstd/panicking.rs:211
@400000005b58ad9825c618ec    3: std::panicking::default_hook
@400000005b58ad9825c618ec              at libstd/panicking.rs:227
@400000005b58ad9825c61cd4    4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
@400000005b58ad9825c6a1a4    5: std::panicking::rust_panic_with_hook
@400000005b58ad9825c6c0e4              at libstd/panicking.rs:467
@400000005b58ad9825c6ebdc    6: std::panicking::begin_panic
@400000005b58ad9825c891bc    7: <[solana::entry::Entry] as solana::ledger::Block>::to_blobs
@400000005b58ad9825c8c484    8: solana::write_stage::WriteStage::write_and_send_entries
```
[dontpanic.log](https://github.com/solana-labs/solana/files/2228865/dontpanic.log)

**Comment by rob-solana** [comment]
super interesting, digging in

**Comment by mvines** [comment]
Maybe we're now shoving too much into an Entry sometimes by accident?

**Comment by rob-solana** [comment]
I'll check

**Comment by rob-solana** [comment]
that code should have been "maybe fixes #756"...

**Comment by rob-solana** [comment]
Mike, can you try my PR?

**Comment by mvines** [comment]
It’s way easier if you can just merge it and it’ll auto deploy out to the net.  Maybe write a test if possible to confirm the off-by-one then land!

**Comment by rob-solana** [comment]
ug...  need infinitely variable transaction sizes...
