### ISSUE TITLE
bench-tps panics after a couple minutes on the testnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#786]
This panic did not manifest on Friday morning.  Likely regression window: https://github.com/solana-labs/solana/compare/678b2870f...81db33349

```
thread 'solana-client-sample' panicked at 'expected tx_count(20216801) >= initial_tx_count(20217328)', src/bin/bench-tps.rs:72:9
 87574 stack backtrace:
 87575 V   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
 87576              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
 87577    1: std::sys_common::backtrace::print
 87578    2: std::panicking::default_hook::{{closure}}
 87579              at libstd/panicking.rs:211
 87580    3: std::panicking::default_hook
 87581              at libstd/panicking.rs:227
 87582    4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
 87583    5: std::panicking::rust_panic_with_hook
 87584              at libstd/panicking.rs:467
 87585    6: std::panicking::begin_panic_fmt
 87586              at libstd/panicking.rs:350
 87587    7: solana_bench_tps::sample_tx_count
``
cc: #784

**Comment by mvines** [comment]
Issue no longer reproduces, hmm.  😬

**Comment by mvines** [comment]
Yes it does, darn

**Comment by mvines** [comment]
This hasn't been observed for quite a while, will continue to monitor ...

**Comment by mvines** [comment]
Closing until this pops up again
