### ISSUE TITLE
show-stake-account CLI is broken

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#8067]
`solana show-stake-account` is broken on master.  Same behavior if passed a pubkey/address or a keypair file for <STAKE_ACCOUNT>

`solana account` works and shows this pubkey is valid.

@t-nelson looks like the issue is in your SigningAuthority code.

```
dan@cabbage-patch:~$ solana account 23UkMfdhtknu8Jr2mYAGff1ppshvZT71NW7fCyNnMtR5

Public Key: 23UkMfdhtknu8Jr2mYAGff1ppshvZT71NW7fCyNnMtR5
Balance: 10 SOL
Owner: Stake11111111111111111111111111111111111111
Executable: false
Length: 200 (0xc8) bytes
0000:   01 00 00 00  80 d5 22 00  00 00 00 00  a2 a8 a1 34   ......"........4
0010:   da de 73 5d  3e 37 89 68  57 7c 76 5e  f8 e3 e9 e5   ..s]>7.hW|v^....
0020:   08 eb 96 73  65 33 f9 55  b8 d1 ed 68  51 77 42 61   ...se3.U...hQwBa
0030:   ea 75 27 f7  1f 56 66 a5  e9 3d a5 72  3c a8 ed cb   .u'..Vf..=.r<...
0040:   0b 40 6d 83  47 60 d9 db  c6 31 df 97  00 00 00 00   .@m.G`...1......
0050:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
0060:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
0070:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
0080:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
0090:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
00a0:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
00b0:   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00   ................
00c0:   00 00 00 00  00 00 00 00                             ........

dan@cabbage-patch:~$
dan@cabbage-patch:~$ RUST_BACKTRACE=1 solana show-stake-account 23UkMfdhtknu8Jr2mYAGff1ppshvZT71NW7fCyNnMtR5
thread 'main' panicked at 'internal error: entered unreachable code', cli/src/cli.rs:686:14
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12: solana_cli::cli::parse_command
             at cli/src/cli.rs:686
  13: solana::parse_args
             at cli/src/main.rs:100
  14: solana::main
             at cli/src/main.rs:243
  15: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  19: std::panicking::try
             at src/libstd/panicking.rs:265
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  22: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  23: main
  24: __libc_start_main
  25: _start
```

**Comment by mvines** [comment]
Fixed by #8061
