### ISSUE TITLE
solana-fullnode[27576]: segfault at 8 ip 00007f4e0f0b1841 sp 00007f4e2affc040 error 4 in libnvidia-ptxjitcompiler.so.396.26[7f4e0efd8000+904000]

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#817]
STR:
1. `sudo snap install --devmode --edge`
2. `sudo snap set solana mode=leader+drone enable-cuda=1`
3. `sudo tail -f /var/log/syslog`

OK: https://buildkite.com/solana-labs/solana-snap/builds/238
KO: https://buildkite.com/solana-labs/solana-snap/builds/239

**Comment by mvines** [comment]
The suspects are:
* https://github.com/solana-labs/solana/commit/a58df52205d1ce30aacb411cc0ebd887018c37e4
* https://github.com/solana-labs/solana/commit/2ea6f861995ac58a612365761067067339a8087b

**Comment by mvines** [comment]
Better STR:
1. ` ./multinode-demo/setup.sh`
2. ` ./multinode-demo/drone.sh`
3. `SOLANA_CUDA=1  ./multinode-demo/leader.sh`

```
thread 'main' panicked at 'assertion failed: balance > 0', src/bin/fullnode.rs:110:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic
   7: solana_fullnode::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  11: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
```

**Comment by mvines** [comment]
No longer reproduces
