### ISSUE TITLE
Update unit tests to return Result

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#833]
As of Rust 1.28: "Unit test functions marked with the #[test] attribute can now return Result<(), E: Debug> in addition to ()."

Add that to all our tests and change all `unwrap()` calls to `?`.

**Comment by kzys** [comment]
Hey. I've just submitted the above pull request to address the issue.

Regarding line numbers, having an error on `?` triggers

```
---- crdt_retransmit stdout ----
Error: IO(Custom { kind: Other, error: StringError("hello") })
thread 'crdt_retransmit' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', libtest/lib.rs:326:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I agree that having `libtest/lib.rs` is annoying, but that can be mitigated by RUST_BACKTRACE=1. The below backtrace contains `tests/data_replicator.rs:140`

```
---- crdt_retransmit stdout ----
Error: IO(Custom { kind: Other, error: StringError("hello") })
thread 'crdt_retransmit' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', libtest/lib.rs:326:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::try::do_call
             at libstd/panicking.rs:413
   7: test::assert_test_result
             at ./<panic macros>:8
   8: data_replicator::__test::TESTS::{{closure}}
             at tests/data_replicator.rs:140
   9: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  11: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
```

**Comment by aeyakovenko** [comment]
lets try it.  it will clean up the code.    worst case, the dev can printf to bisect the line failure :)

**Comment by kzys** [comment]
Thanks. As you mentioned on the pull request, the backtrace sadly points the beginning of the function, not `?`.

```
failures:

---- test_multi_node_validator_catchup_from_zero stdout ----                   
Error: IO(Custom { kind: Other, error: StringError("error") })                 
thread 'test_multi_node_validator_catchup_from_zero' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', libtest/lib.rs:326:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                  
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71                              
             at libstd/sys_common/backtrace.rs:59                              
   2: std::panicking::default_hook::{{closure}}                                
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt                                       
             at libstd/panicking.rs:426
   6: std::panicking::try::do_call
             at libstd/panicking.rs:413
   7: test::assert_test_result
             at ./<panic macros>:8
   8: multinode::__test::TESTS::{{closure}}                                    
             at tests/multinode.rs:115
   9: core::ops::function::FnOnce::call_once                                   
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  10: <F as alloc::boxed::FnBox<A>>::call_box                                  
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640   
  11: panic_unwind::dwarf::eh::read_encoded_pointer                            
             at libpanic_unwind/lib.rs:105                                     


failures:
    test_multi_node_validator_catchup_from_zero                                

test result: FAILED. 2 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out 

error: test failed, to rerun pass '--test multinode'                           
```

Here is the branch where I intentionally break the test.

https://github.com/kzys/solana/tree/reduce-unwrap-fail

**Comment by mvines** [comment]
hmm, yeah that's something of a downgrade in usability.

**Comment by garious** [comment]
I agree that it's a usability failure, but it's the same usability failure being exposed to the production code. If the there's not enough context in that error message to quickly debug a short unit test, what chance would the production code have?

**Comment by garious** [comment]
meh, closing.  We use this technique in a few places. I like it, but we're getting by just fine without using it everywhere.
