### ISSUE TITLE
Validator:  thread 'main' panicked at 'opening ledger

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#838]
We're getting this panic on validator startup, I mostly suspect #830
```
  INFO 2018-08-03T05:22:24.415789656Z: solana::fullnode: creating bank...
 thread 'main' panicked at 'opening ledger: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
 stack backtrace:
    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1: std::sys_common::backtrace::print
              at libstd/sys_common/backtrace.rs:71
              at libstd/sys_common/backtrace.rs:59
    2: std::panicking::default_hook::{{closure}}
              at libstd/panicking.rs:211
    3: std::panicking::default_hook
              at libstd/panicking.rs:227
    4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
    5: std::panicking::rust_panic_with_hook
              at libstd/panicking.rs:467
    6: std::panicking::begin_panic_fmt
              at libstd/panicking.rs:350
    7: rust_begin_unwind
              at libstd/panicking.rs:328
    8: core::panicking::panic_fmt
              at libcore/panicking.rs:71
    9: core::result::unwrap_failed
   10: solana::fullnode::FullNode::new_internal
   11: solana::fullnode::FullNode::new
   12: solana_fullnode::main
   13: std::rt::lang_start::{{closure}}
   14: std::panicking::try::do_call
              at libstd/rt.rs:59
              at libstd/panicking.rs:310
   15: __rust_maybe_catch_panic
              at libpanic_unwind/lib.rs:105
   16: std::rt::lang_start_internal
              at libstd/panicking.rs:289
              at libstd/panic.rs:374
              at libstd/rt.rs:58
   17: main
   18: __libc_start_main
   19: _start
```

**Comment by mvines** [comment]
Might not be #830, this panic has been observed at least once after #830 was reverted.   I'll monitor...

**Comment by rob-solana** [comment]
I'm seeing ledger/data disappear sometimes when a validator dies.  When this happens and the ledger is large, validator restart (which rsyncs the ledger) will often omit ledger/data because of its size.

I haven't been able to figure out the first issue, but the 2nd issue is soluble with a mod to validator.sh.

**Comment by rob-solana** [comment]
I'm pretty sure this is fixed in 859 (not rsyncing enough data).

I only see disappearing ledgers on the snap boxes

**Comment by mvines** [comment]
nice

**Comment by mvines** [comment]
No longer reproduces on the testnet

**Comment by rob-solana** [comment]
w00t!
