### ISSUE TITLE
Leader: thread 'main' panicked at 'process_ledger: LedgerVerificationFailed'

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#839]
Observed on the leader node of `testnet-perf` multiple times this evening
```
  WARN 2018-08-03T05:26:21.940601471Z: solana::entry: next_hash is invalid expected: 521tgrzavYZ6Xe5hvovDKLsPyrJ81VQmxky5K6n4DYBg actual: 5c7fhopxckMWqaqk6hC1Yr6ZRE5TXhvXAHuRuyurAuTb
  WARN 2018-08-03T05:26:21.940634074Z: solana::ledger: entry invalid!: 521tgrzavYZ6Xe5hvovDKLsPyrJ81VQmxky5K6n4DYBg num txs: 286
  WARN 2018-08-03T05:26:21.940921736Z: solana::bank: Ledger proof of history failed at entry: 1408
 thread 'main' panicked at 'process_ledger: LedgerVerificationFailed', libcore/result.rs:945:5
 stack backtrace:
    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1: std::sys_common::backtrace::print
              at libstd/sys_common/backtrace.rs:71
              at libstd/sys_common/backtrace.rs:59
    2: std::panicking::default_hook::{{closure}}
              at libstd/panicking.rs:211
    3: std::panicking::default_hook
              at libstd/panicking.rs:227
    4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
    5: std::panicking::rust_panic_with_hook
              at libstd/panicking.rs:467
    6: std::panicking::begin_panic_fmt
              at libstd/panicking.rs:350
    7: rust_begin_unwind
              at libstd/panicking.rs:328
    8: core::panicking::panic_fmt
              at libcore/panicking.rs:71
    9: core::result::unwrap_failed
   10: solana::fullnode::FullNode::new_internal
   11: solana::fullnode::FullNode::new
   12: solana_fullnode::main
   13: std::rt::lang_start::{{closure}}
   14: std::panicking::try::do_call
              at libstd/rt.rs:59
              at libstd/panicking.rs:310
   15: __rust_maybe_catch_panic
              at libpanic_unwind/lib.rs:105
   16: std::rt::lang_start_internal
              at libstd/panicking.rs:289
              at libstd/panic.rs:374
              at libstd/rt.rs:58
   17: main
   18: __libc_start_main
   19: _start
```

**Comment by mvines** [comment]
Dup of #706
