### ISSUE TITLE
validator boot crashloop on master-testnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#895]
```
 INFO 2018-08-07T18:02:29.997675021Z: solana::fullnode: processing ledger...
 INFO 2018-08-07T18:02:30.012927771Z: solana::bank: tx error: Err(AccountNotFound(86pj4ibSj61Bh9zgK1TtBHbDvMoNfV6sWZweK27WUr4w))
 INFO 2018-08-07T18:02:30.013004129Z: solana::bank: 1 errors of 4 txs
thread 'main' panicked at 'process_ledger: AccountNotFound(86pj4ibSj61Bh9zgK1TtBHbDvMoNfV6sWZweK27WUr4w)', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: solana::fullnode::FullNode::new_internal
  11: solana::fullnode::FullNode::new
  12: solana_fullnode::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: _start'
```

**Comment by mvines** [comment]
Network redeploy made this go away, unclear what happened :-/
