### ISSUE TITLE
Since v1.1.3 solana-validator doesn't connect via a firewall any more

### ISSUE THREAD

**Issue by vkomenda** [solana-labs/solana#9488]
#### Problem

On a machine with ports forwarded from the firewall, `solana-validator` always exits immediately with this error:
```
[2020-04-13T16:18:31.929079979Z ERROR solana_validator] Unable to bind to tcp/8821: Address already in use (os error 98)
```

Versions prior to 1.1.3 don't have this error.

#### Proposed Solution

I suspect d5ae85016 but that needs to be tested. Could be a dependent crate as well.

**Comment by mvines** [comment]
I'm pretty sure your `--rpc-port` + 1 overlays with `--dynamic-port-range`

**Comment by vkomenda** [comment]
I tried with overlap and without to the same result.

**Comment by mvines** [comment]
Can I see your `solana-validator` arguments please?

**Comment by vkomenda** [comment]
Sure.
```
[2020-04-14T17:43:00.253818734Z INFO  solana_validator] solana-validator 1.1.3
[2020-04-14T17:43:00.253852025Z INFO  solana_validator] Starting validator with: ArgsOs {
        inner: [
            "solana-validator",
            "--identity",
            "/home/vk/validator-keypair.json",
            "--vote-account",
            "/home/vk/validator-vote-keypair.json",
            "--authorized-voter",
            "/home/vk/validator-vote-keypair.json",
            "--authorized-voter",
            "/home/vk/validator-keypair.json",
            "--ledger",
            "/home/vk/validator-ledger",
            "--rpc-port",
            "8820",
            "--dynamic-port-range",
            "8822-8830",
            "--entrypoint",
            "35.203.170.30:8001",
            "--limit-ledger-size",
            "--cuda",
            "--wait-for-supermajority",
            "2492465",
            "--expected-shred-version",
            "18216",
            "--trusted-validator",
            "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
            "--trusted-validator",
            "9jh8c14x3bfnzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ",
            "--no-untrusted-rpc",
        ],
    }
[2020-04-14T17:43:00.253968428Z INFO  solana_metrics::metrics] host id: GuKn8nEJwUPjBfxpwyq2MXU2JNrSpj7gqnKptCZeEk7j
[2020-04-14T17:43:00.254003942Z INFO  solana_perf::perf_libs] perf-libs found at "/home/vk/.local/share/solana/install/releases/1.1.3/solana-release/bin/perf-libs"
[2020-04-14T17:43:00.254079637Z WARN  solana_perf::perf_libs] CUDA installation not found
[2020-04-14T17:43:00.254087498Z INFO  solana_perf::perf_libs] Loading "libcuda-crypt.so"
[2020-04-14T17:43:00.542233448Z INFO  solana_validator] 35.203.170.30:8001 reports the IP address for this machine as 195.171.215.154
thread 'main' panicked at 'broadcast multi_bind: Custom { kind: Other, error: "No available UDP ports in (8822, 8830)" }', core/src/cluster_info.rs:1808:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2020-04-14T17:43:00.543481084Z INFO  solana_metrics::metrics] metrics disabled: SOLANA_METRICS_CONFIG: environment variable not found
[2020-04-14T17:43:00.544722633Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'broadcast multi_bind: Custom { kind: Other, error: \"No available UDP ports in (8822, 8830)\" }', core/src/cluster_info.rs:1808:13" location="core/src/cluster_info.rs:1808:13"
```

**Comment by vkomenda** [comment]
```
[2020-04-14T17:45:28.409478794Z INFO  solana_validator] solana-validator 1.1.3
[2020-04-14T17:45:28.409526391Z INFO  solana_validator] Starting validator with: ArgsOs {
        inner: [
            "solana-validator",
            "--identity",
            "/home/vk/validator-keypair.json",
            "--vote-account",
            "/home/vk/validator-vote-keypair.json",
            "--authorized-voter",
            "/home/vk/validator-vote-keypair.json",
            "--authorized-voter",
            "/home/vk/validator-keypair.json",
            "--ledger",
            "/home/vk/validator-ledger",
            "--rpc-port",
            "8820",
            "--dynamic-port-range",
            "8821-8830",
            "--entrypoint",
            "35.203.170.30:8001",
            "--limit-ledger-size",
            "--cuda",
            "--wait-for-supermajority",
            "2492465",
            "--expected-shred-version",
            "18216",
            "--trusted-validator",
            "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
            "--trusted-validator",
            "9jh8c14x3bfnzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ",
            "--no-untrusted-rpc",
        ],
    }
[2020-04-14T17:45:28.409652556Z INFO  solana_metrics::metrics] host id: GuKn8nEJwUPjBfxpwyq2MXU2JNrSpj7gqnKptCZeEk7j
[2020-04-14T17:45:28.409689944Z INFO  solana_perf::perf_libs] perf-libs found at "/home/vk/.local/share/solana/install/releases/1.1.3/solana-release/bin/perf-libs"
[2020-04-14T17:45:28.409773912Z WARN  solana_perf::perf_libs] CUDA installation not found
[2020-04-14T17:45:28.409782514Z INFO  solana_perf::perf_libs] Loading "libcuda-crypt.so"
[2020-04-14T17:45:28.689019973Z INFO  solana_validator] 35.203.170.30:8001 reports the IP address for this machine as 195.171.215.154
[2020-04-14T17:45:28.689793365Z ERROR solana_validator] Unable to bind to tcp/8821: Address already in use (os error 98)
```

**Comment by mvines** [comment]
This, https://github.com/solana-labs/solana/issues/9488#issuecomment-613584239, should fail because `--rpc-port` + 1 overlaps with `--dynamic-port-range`.   This error message has been slightly improved via https://github.com/solana-labs/solana/pull/9464

This, https://github.com/solana-labs/solana/issues/9488#issuecomment-613583601, fails because `--dynamic-port-range` is too small.   Increase the upper-end of the port range.   But the validator should cleanly error in this case for sure, I'll make an improvement here

**Comment by vkomenda** [comment]
And, for completeness' sake,
```
[2020-04-14T17:55:18.350685255Z INFO  solana_validator] solana-validator 1.1.3
[2020-04-14T17:55:18.350715768Z INFO  solana_validator] Starting validator with: ArgsOs {
        inner: [
            "solana-validator",
            "--identity",
            "/home/vk/validator-keypair.json",
            "--vote-account",
            "/home/vk/validator-vote-keypair.json",
            "--authorized-voter",
            "/home/vk/validator-vote-keypair.json",
            "--authorized-voter",
            "/home/vk/validator-keypair.json",
            "--ledger",
            "/home/vk/validator-ledger",
            "--rpc-port",
            "8820",
            "--dynamic-port-range",
            "8820-8830",
            "--entrypoint",
            "35.203.170.30:8001",
            "--limit-ledger-size",
            "--cuda",
            "--wait-for-supermajority",
            "2492465",
            "--expected-shred-version",
            "18216",
            "--trusted-validator",
            "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
            "--trusted-validator",
            "9jh8c14x3bfnzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ",
            "--no-untrusted-rpc",
        ],
    }
[2020-04-14T17:55:18.350813437Z INFO  solana_metrics::metrics] host id: GuKn8nEJwUPjBfxpwyq2MXU2JNrSpj7gqnKptCZeEk7j
[2020-04-14T17:55:18.350844433Z INFO  solana_perf::perf_libs] perf-libs found at "/home/vk/.local/share/solana/install/releases/1.1.3/solana-release/bin/perf-libs"
[2020-04-14T17:55:18.350912399Z WARN  solana_perf::perf_libs] CUDA installation not found
[2020-04-14T17:55:18.350919146Z INFO  solana_perf::perf_libs] Loading "libcuda-crypt.so"
[2020-04-14T17:55:18.634117235Z INFO  solana_validator] 35.203.170.30:8001 reports the IP address for this machine as 195.171.215.154
[2020-04-14T17:55:18.635098685Z ERROR solana_validator] Unable to bind to tcp/8820: Address already in use (os error 98)
```

**Comment by vkomenda** [comment]
> This, [#9488 (comment)](https://github.com/solana-labs/solana/issues/9488#issuecomment-613583601), fails because `--dynamic-port-range` is too small. Increase the upper-end of the port range. But the validator should cleanly error in this case for sure, I'll make an improvement here

Thanks, that started it but then it died without any panic or ERROR. The last log was
```
[2020-04-14T17:58:09.289494408Z INFO  solana_core::replay_stage] GuKn8nEJwUPjBfxpwyq2MXU2JNrSpj7gqnKptCZeEk7j reset PoH to tick 564650752 (within slot 8822667). My next leader slot is 8822840
[2020-04-14T17:58:09.289535814Z INFO  solana_metrics::metrics] datapoint: blocks_produced num_blocks_on_fork=0i num_dropped_blocks_on_fork=0i
[2020-04-14T17:58:09.290219549Z WARN  solana_core::storage_stage] Storage account not found: 4ty3vXBpKdRJ3AU313Pyf88mQs6TaoEUUpNzBGXGJYD7
[2020-04-14T17:58:09.504054615Z WARN  solana_metrics::counter] COUNTER:{"name": "cluster_info-gossip_pull_response_value_timeout", "counts": 75001, "samples": 75000,  "now": 1586887089504, "events": 1}
```

**Comment by vkomenda** [comment]
Sorry, there was an `Err` earlier in the logs:
```
[2020-04-14T18:02:01.621109420Z INFO  solana_sys_tuner] Sending tuning request
[2020-04-14T18:02:01.621189404Z INFO  solana_sys_tuner] Tuning request status Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by mvines** [comment]
> Tuning request status Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

This is non-fatal but I'll improve this error message while I'm here too.

**Comment by vkomenda** [comment]
With the documentation added in https://github.com/solana-labs/solana/pull/9494 it is now clear how to specify ports. I've been running 1.1.3 without any trouble for a day, so I'm going to close the issue as no longer relevant. Please reopen if you think otherwise.

**Comment by mvines** [comment]
Thanks for the update!
