### ISSUE TITLE
EpochSlots first_slot / num_slots integer overflow

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9704]
#### Problem

Crashed my local testnet.

Test Case:

```
[2020-04-24T14:21:59.339879638Z INFO  solana_core::crds_value] CrdsValue DEBUG: CrdsValue { signature: 4XqN2yYtx9mXniKAFQEaFBSfFaadRjTNYaVcmfEZfPYPd3Mdjmbib54KmuuxRn6ARv9pfizgzuNxUy9BiJV9Ewp5, data: EpochSlots(225, EpochSlots { from: AmPwEfSwC9V13sQciYLSiD6tsQdTisSz3L2U5FLv6Sv6, slots: [Flate2(Flate2 { first_slot: 6771846344006181954, num: 777657523183, compressed: [149, 3, 59, 72, 22, 65, 16, 125, 104, 35, 136, 11, 40, 138, 141, 104, 176, 209, 82, 176, 143, 208, 70, 68, 191, 225, 38, 250, 157, 222, 40, 106, 97, 239, 129, 8, 138, 10, 130, 136, 214, 66, 185, 109, 8, 130, 164, 110, 25, 82, 132, 144, 128, 169, 8, 170, 144, 50, 129, 144, 38, 41, 242, 185, 100, 230, 110, 238, 179, 255, 4, 242, 138, 55, 111, 22, 106, 236, 206, 238, 173, 105, 18, 90, 166, 141, 186, 105, 112, 70, 93, 27, 159, 0, 168, 130, 208, 142, 18, 71, 136, 108, 217, 192, 59, 2, 48, 238, 77, 118, 149, 226, 88, 134, 67, 8, 195, 177, 67, 244, 97, 39, 143, 204, 233, 224, 57, 69, 28, 120, 118, 62, 156, 137, 52, 240, 36, 201, 146, 69, 145, 132, 219, 139, 188, 37, 154, 78, 121, 135, 22, 26, 250, 176, 107, 127, 151, 123, 41, 127, 249, 186, 19, 78, 168, 1, 70, 192, 120, 19, 142, 50, 197, 205, 150, 234, 17, 121, 223, 145, 68, 235, 123, 57, 70, 245, 70, 198, 231, 238, 62, 238, 181, 192, 224, 243, 97, 208, 249, 76, 36, 121, 84, 71, 181, 59, 138, 110, 21, 85, 35, 83, 60, 103, 93, 187, 37, 77, 236, 243, 230, 117, 124, 137, 85, 224, 235, 154, 182, 194, 41, 233, 145, 190, 205, 157, 206, 37, 194, 148, 88, 191, 68, 89, 78, 29, 212, 108, 51, 29, 45, 119, 87, 132, 190, 160, 230, 68, 132, 68, 25, 255, 223, 44, 32, 121, 142, 145, 177, 204, 255, 175, 0, 108, 97, 9, 248, 173, 118, 231, 151, 181, 49, 86, 58, 82, 112, 44, 77, 239, 149, 89, 31] }), Flate2(Flate2 { first_slot: 173236853049140519, num: 833226997783, compressed: [237, 206, 177, 17, 0, 0, 4, 151, 64, 139, 152, 210, 0, 38, 50, 136, 137, 148, 156, 78, 198, 69, 231, 32, 160, 201, 220, 157, 33, 103, 188, 6, 149, 140, 171, 203, 122, 121, 178, 6, 87, 215] }), Flate2(Flate2 { first_slot: 4611966393892480397, num: 14555633996257493198, compressed: [157, 119, 177, 11, 26, 81, 20, 172, 127, 202, 224, 111, 48, 202, 96, 83, 70, 163, 82, 254, 0, 147, 137, 87, 6, 44, 0, 54, 6, 171, 50, 88, 93, 35, 70, 165, 40, 171, 137, 241, 137, 212, 179, 189, 36, 155, 92, 247, 62, 247, 190, 227, 151, 162, 247, 213, 249, 238, 119, 190, 206, 215, 61, 71, 8, 133, 167, 226, 89, 145, 154, 133, 134, 107, 68, 2, 84, 96, 5, 149, 208, 10, 121, 126, 161, 49, 159, 210, 19, 221, 121, 138, 82, 13, 73, 53, 152, 194, 210, 140, 237, 144, 185, 230, 131, 139, 232, 65, 97, 146, 27, 107, 184, 234, 208, 219, 112, 35, 101, 184, 112, 12, 185, 41, 52, 75, 251, 28, 17, 174, 61, 58, 252, 8, 206, 2, 30, 156, 77, 63, 150, 110, 100, 63, 187, 180, 185, 196, 225, 9, 253, 210, 211, 239, 214, 54, 59, 19, 67, 221, 146, 108, 83, 34, 247, 172, 205, 115, 200, 188, 85, 103, 244, 54, 240, 2] }), Uncompressed(Uncompressed { first_slot: 9854, num: 7628555, slots: bit_vec![...] })], wallclock: 1587738119271 }) }
```

Crash:

```
[2020-04-24T14:22:00.569200993Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=10133i block_height=10097i
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1029
  11: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
             at metrics/src/metrics.rs:429
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  13: rust_begin_unwind
             at src/libstd/panicking.rs:380
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::panicking::panic
             at src/libcore/panicking.rs:52
  16: solana_core::epoch_slots::EpochSlots::to_slots::{{closure}}
             at core/src/epoch_slots.rs:243                                                                                                    
  17: core::iter::adapters::filter_try_fold::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:921
  18: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1776
  19: <core::iter::adapters::Filter<I,P> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:970
  20: core::iter::traits::iterator::Iterator::find_map
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:2104
  21: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/mod.rs:1070
  22: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/flatten.rs:268
  23: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/adapters/flatten.rs:173
  24: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:2007
  25: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1919
  26: core::iter::traits::iterator::Iterator::collect
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/iter/traits/iterator.rs:1558
  27: solana_core::epoch_slots::EpochSlots::to_slots
             at core/src/epoch_slots.rs:241
  28: solana_core::cluster_slots::ClusterSlots::update_internal
             at core/src/cluster_slots.rs:39
  29: solana_core::cluster_slots::ClusterSlots::update
             at core/src/cluster_slots.rs:34
  30: solana_core::repair_service::RepairService::run
             at core/src/repair_service.rs:152
  31: solana_core::repair_service::RepairService::new::{{closure}}
             at core/src/repair_service.rs:91
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-04-24T14:22:00.663693744Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-repair-service" one=1i message="panicked at 'attempt to add with overflow', core/src/epoch_slots.rs:243:36" location="core/src/epo
ch_slots.rs:243:36"
```

https://github.com/solana-labs/solana/blob/1cc2f6739188e2c41b60496557f069466745e8b7/core/src/epoch_slots.rs#L238

    Flate2(Flate2 { first_slot: 4611966393892480397, num: 14555633996257493198, ...

#### Proposed Solution

TBD

**Comment by mvines** [comment]
Fixed by #9706
