### ISSUE TITLE
Epoch Slots BitVec::set_bit crash

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9732]
#### Problem

Reproducible on 1.1.7 by corrupting CrdsData.

Crash:

```
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1029
  11: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
             at metrics/src/metrics.rs:429
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  13: std::panicking::begin_panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/panicking.rs:399
  14: bv::bit_vec::impls::<impl bv::traits::bits_mut::BitsMut for bv::bit_vec::BitVec<Block>>::set_bit
             at ./<::std::macros::panic macros>:2
  15: bv::bit_vec::BitVec<Block>::set
             at /data/solana-dev/.cargo/registry/src/github.com-1ecc6299db9ec823/bv-0.11.1/src/bit_vec/mod.rs:553
  16: solana_core::epoch_slots::Uncompressed::add
             at core/src/epoch_slots.rs:112
  17: solana_core::epoch_slots::CompressedSlots::add
             at core/src/epoch_slots.rs:152
  18: solana_core::epoch_slots::EpochSlots::add
             at core/src/epoch_slots.rs:217
  19: solana_core::epoch_slots::EpochSlots::fill
             at core/src/epoch_slots.rs:198
  20: solana_core::cluster_info::ClusterInfo::push_epoch_slots
             at core/src/cluster_info.rs:478
  21: solana_core::repair_service::RepairService::update_completed_slots
             at core/src/repair_service.rs:329
  22: solana_core::repair_service::RepairService::run
             at core/src/repair_service.rs:151
  23: solana_core::repair_service::RepairService::new::{{closure}}
             at core/src/repair_service.rs:91
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2020-04-26T06:07:39.666373652Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-repair-service" one=1i message="panicked at 'BitVec::set_bit: out of
bounds', <::std::macros::panic macros>:2:4" location="<::std::macros::panic macros>:2:4"
```

https://github.com/solana-labs/solana/blob/34f5f48e43ddfb49c833e8ed919470e38b46a978/core/src/epoch_slots.rs#L193

https://github.com/solana-labs/solana/blob/34f5f48e43ddfb49c833e8ed919470e38b46a978/core/src/cluster_info.rs#L477

https://github.com/solana-labs/solana/blob/dabbdcf98871112798bf9cfecb5557637ed35b2d/core/src/repair_service.rs#L329

Not sure if the bad Slot can make it far enough to trigger this remotely.

#### Proposed Solution

TBD

**Comment by mvines** [comment]
If this reproduces on v1.1.8 please re-open.  For now I'll assume the sanitize improvements in v1.1.8 will catch this one
