### ISSUE TITLE
get_epoch_schedule largest_confirmed_root does not exist on node

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9791]
#### Problem

Crash:

```
[2020-04-29T16:08:23.227835711Z INFO  solana_core::replay_stage] Couldn't vote on heaviest fork: Some(33637), failure_reasons: [FailedThreshold(33637)]
[2020-04-29T16:08:23.259855861Z INFO  solana_core::replay_stage] bank frozen: 33638
[2020-04-29T16:08:23.259880871Z INFO  solana_metrics::metrics] datapoint: replay-slot-stats slot=33638i fetch_entries_time=3208i fetch_entries_fail_time=0i entry_verification_time=33i replay_time=8320i replay_total_elapsed=455871i total_entries=17i total_shreds=17i
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1029
  11: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
             at metrics/src/metrics.rs:429
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  13: rust_begin_unwind
             at src/libstd/panicking.rs:380
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  16: core::result::Result<T,E>::unwrap
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:963
  17: <solana_core::rpc::RpcSolImpl as solana_core::rpc::rpc_impl_RpcSol::gen_server::RpcSol>::get_epoch_schedule
             at core/src/rpc.rs:916
  18: solana_core::rpc::rpc_impl_RpcSol::gen_server::RpcSol::to_delegate::{{closure}}
[2020-04-29T16:08:23.306371498Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="http.worker180" one=1i message="panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: ServerError(-32000), message: \"Cluster largest_confirmed_root 32040 does not exist on node. Node root: 32678\", data: None }', core/src/rpc.rs:916:12" location="core/src/rpc.rs:916:12"
```

Testnet state:

```
$ solana validators
  Identity Pubkey                               Vote Account Pubkey                           Commission  Last Vote  Root Block  Credits  Active Stake
  4Qmkj4pYTW6KWffRVLdmSz8UZJCYWjy6hnFjZf2gTMBN  DrmCRkdWXcWJMCscboWtYxHa2zAMEqNptP7oRnGeXY1R        100%      33525	  32678    27317  0.762596718 SOL (40.17%)
  9t9giLKS28ArTWELmVpP7VUmue4atRkjgL3gZVcQDHH   FU9RRP5RBDvN5rUUNE9Ak7rXsrrc3sXWMX2JBoecYUjT        100%      33525	  32678    27521  0.49771712 SOL (26.21%)
! 4Pbqae2nzGrn5dZ8dt2gyymaUUbCNcGsxheJUgqupkc7  6uhLdidSdMSzZPeHTmwsXfSzpdRjuKXktqjDUihydEQY        100%      32071	  32040        0  0.638326291 SOL (33.62%)
```

Crash occurs when viewing the vote account of the deliquent 4Pbqae2nzGrn5dZ8dt2gyymaUUbCNcGsxheJUgqupkc7 validator:

    target/debug/solana --keypair /data/solana-dev/solana/net/../config/validator-three/identity.json --url 'http://127.0.0.1:9898' vote-account /data/solana-dev/solana/net/../config/validator-three/vote-account.json

Full log: https://drive.google.com/drive/u/0/folders/1vYU_KNGHicYH4xLQclJwz66RXhmUl5PN

#### Proposed Solution

TBD

**Comment by mvines** [comment]
@leoluk - are you working off the master branch here?

**Comment by leoluk** [comment]
I'm on 972381efff9a28b39ad01d11f834f22c88beb880

**Comment by leoluk** [comment]
Added more context on the crash - seems it's triggered when requesting the vote account of a deliquent validator which is way behind.

**Comment by CriesofCarrots** [comment]
Thanks, @leoluk , I've identified the bug. We recently made some changes to rpc to query the cluster's largest-confirmed-root by default, which is a fallible operation. But there are two methods that incorrectly assume it is infallible. You hit one of them.
Pushing a fix now!
