### ISSUE TITLE
Solana catchup panics due to underflow converting float to duration

### ISSUE THREAD

**Issue by svenski123** [solana-labs/solana#9866]
#### Problem

`solana catchup --follow` as of v1.1.8 will panic (eventually) due to an underflow converting a float to a duration.

```
$ RUST_BACKTRACE=1 solana catchup --verbose --follow 9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv http://127.0.0.1:8899
RPC URL: http://tds.solana.com
Default Signer Path: /home/solana/key/solana-validator-keypair.json
? 0 slots behind (us:12180561 them:12180561)
thread 'main' panicked at 'underflow when converting float to duration', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/macros/mod.rs:10:9
? 0 slots behind (us:12180561 them:12180561)
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: solana_cli::cluster_query::process_catchup
  15: solana_cli::cli::process_command
  16: solana::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
             at ../csu/libc-start.c:266
  26: <unknown>
```

#### Proposed Solution
TBD

**Comment by mvines** [comment]
Fixed by #9867
