### ISSUE TITLE
panicked at 'Bank in descendants map must exist in BankForks', core/src/replay_stage.rs:519

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#9907]
Multiple TdS nodes running 1.1.9 panicked with at `panicked at 'Bank in descendants map must exist in BankForks', core/src/replay_stage.rs:519` shortly after upgrading from 1.1.8

Options:
* Try to fix it forward
* Back out https://github.com/solana-labs/solana/pull/9886

**Comment by mvines** [comment]
This [1] log from Brian doesn't contain any panics, but his node was one of the delinquents after the v1.1.9 upgrade and I see messages like this:
```
[2020-05-07T03:34:25.182772906Z WARN  solana_core::repair_service] Repaired version of slot 12680954 most recently (but maybe not entirely)
                            from Some(V4(91.90.148.195:8008)) has failed again
[2020-05-07T03:34:25.182819431Z WARN  solana_core::repair_service] Repaired version of slot 12680962 most recently (but maybe not entirely)
                            from Some(V4(159.69.244.44:8007)) has failed again
[2020-05-07T03:34:25.182834604Z WARN  solana_core::repair_service] Repaired version of slot 12681038 most recently (but maybe not entirely)
                            from Some(V4(116.203.110.213:8007)) has failed again
[2020-05-07T03:34:25.182845066Z WARN  solana_core::repair_service] Repaired version of slot 12681092 most recently (but maybe not entirely)
                            from Some(V4(159.69.244.44:8007)) has failed again
``` 
hopefully this helps a bit @carllin 


[1] http://165.227.100.142/solana-validator-71bhKKL89U3dNHzuZVZ7KarqV6XtHEgjXjvJTsguD11B.log.gz
